### ISSUE TITLE
helper containers does not have c++11 operators

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#107]
helper::vector, helper::set, helper::list, etc. lack of important c++11 functionalities
such as move constructor, initializer_list and maybe other stuffs.

helper::vector is adding several stuffs to std::vector, so it makes sense to add these functionalities.

But is derivating helper::set, helper::list from stl container the right design since they are simply adding the stream operators (for string serialization)? Could not we simply add these operators outside of the class, and always use std containers?

**Comment by matthieu-nesme** [comment]
helper/map.h is implemented that way, and it works.
We should do the same for set, list, pair, deque, stable_vector.

And we should add the new operators to helper::vector and helper::SVector.

**Comment by matthieu-nesme** [comment]
started in https://github.com/anatoscope/sofa/tree/containers

**Comment by damienmarchal** [comment]
Wouldn't it make sense to alias the std container to sofa::helper ? 

So that the general guideline could be to always use sofa::helper::* and not "if your are using a list then use std::list, if it is a vector then use a sofa::helper::vector, ...". 

More generally 
- it would make the source code more consistent 
- it would ease newcommer's life to get into sofa.

**Comment by matthieu-nesme** [comment]
Also we could just define the stream operators << >> directly on std::vector (with the actual helper::vector implementations). So std::vector could be used in Data and helper::vector would be useful only for advanced users (like cuda-vector, stuff that is not necessary for regular Data).

**Comment by damienmarchal** [comment]
There is a PR that resulted from this discussion and it was merged. 
I close the Issue, do not hesitate to reopen in case it is too early.
