### ISSUE TITLE
StiffSpringForceField doesn't support topology change

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1072]
Setting springs between 2 objects:
For example here are 51 springs between 2 cylinders well placed.
![MeshRefinement_bench-04_resection_00000001](https://user-images.githubusercontent.com/21199245/58867221-59320480-86ba-11e9-9d0e-cacf6440a279.png)

Removing one point will not delete the spring(s) concerned but keep springs with wrong id.
Can potentially crash if id of point kept is out of mechanicalObject size. 
![MeshRefinement_bench-04_resection_00000002](https://user-images.githubusercontent.com/21199245/58867230-5b945e80-86ba-11e9-9a8c-98a305e556b4.png)

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
:)

**Comment by epernod** [comment]
This has been solved in PR #1093
