### ISSUE TITLE
Use std::string instead of char* in Data and BaseData

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#1092]
The usage of `char*` leads to eventual null pointers which may lead to segfaults.

Using `std::string` would be easier and safer for
- `BaseData::name`
- `BaseData::ownerClass`
- `BaseData::group`
- `BaseData::widget`
- `BaseData::helpMsg`

After doing this, don't forget to revert #1090 (temporary fix).

**Comment by lizzyd710** [comment]
I would be interested in working on this. Should I just look for all instances of `char *` in all files, or just in `.cpp` files, or anything else specific?

**Comment by guparan** [comment]
Hi @lizzyd710 thanks for your interest! 

The idea would be to replace the `char*` type of the 5 members I listed in the description by `std::string`. This change will need to be propagated everywhere in SOFA like in the BaseData constructors, in the members' getters/setters, in QDisplayDataWidget (see #1090), etc.
I can't tell precisely how much those members are used in SOFA codebase.

Do not hesitate to ask for help and open a pull-request as soon as you get some results :+1:

**Comment by lizzyd710** [comment]
Cool, thanks for the clarification!

**Comment by guparan** [comment]
Fixed by #1152
