### ISSUE TITLE
sofa.ini

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#114]
This file is mandatory but is not created w/o SOFA_INSTALL_RESOURCES_FILES.

I think /sofa/CMakeLists.txt lines 206-211 should be outside the if(SOFA_INSTALL_RESOURCES_FILES)
as the sofa.ini file has nothing to do with an installation.

**Comment by guparan** [comment]
`if(SOFA_INSTALL_RESOURCES_FILES)` was added by @fredroy in 374a42f0 and is related to CPack usage.

@fredroy, could you help on this?

**Comment by fredroy** [comment]
I thought at that moment that sofa.ini was a resource but apparently no.
(it was related to CPack and Mac when creating a .app/dmg).
So yes, it should be processed outside this test then.

**Comment by damienmarchal** [comment]
Who can fix the problem ?

**Comment by epernod** [comment]
I have faced this issue as I'm using the install of sofaPhysicsAPI. I will give a look

**Comment by matthieu-nesme** [comment]
@epernod did you look at it?

**Comment by damienmarchal** [comment]
@epernod  up :)

**Comment by epernod** [comment]
Sorry, in fact, I'm not facing the same problem. 
I'm not sure to understand the problem (but I can still work on it) 
For me, sofa.ini is generated in build/etc/
