### ISSUE TITLE
copyright.txt

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#117]
sofa/applications/copyright.txt needs to be fixed.
There are maybe others.

**Comment by guparan** [comment]
Yes, this is part of a big license cleaning task that has to be done. There are indeed some inconsistencies in license headers and copyright files, particularly in plugins. There are even sometimes several license headers on the same file.
About this single copyright.txt file, I think we should remove it. Everything in applications/ is not GPL.
Actually I think we should remove all the copyright.txt files in SOFA and stick to a main LICENCE.txt + license headers in files. That could also apply to each plugin independently.

**Comment by guparan** [comment]
Fixed by #139
