### ISSUE TITLE
SofaSimulationCore is missing its include directory when installed

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#1180]
When compiling an external project, doing the following:

**CMakeLists.txt**
```
project(MyProject)
find_package(SofaSimulation)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME}  SofaSimulationCore)
```

**main.cpp**
`#include <sofa/simulation/MechanicalMatrixVisitor.h>`

Will fail to find the `sofa/simulation/MechanicalMatrixVisitor.h` file, which is supposed to be in the `SofaSimulationCore` target.

Looking closer, we have

 **SofaSimulationTargets.cmake**
```
(...)
# Create imported target SofaSimulationCore
add_library(SofaSimulationCore SHARED IMPORTED)

set_target_properties(SofaSimulationCore PROPERTIES
  INTERFACE_LINK_LIBRARIES "SofaCore"
)

# Create imported target SofaSimulationCommon
add_library(SofaSimulationCommon SHARED IMPORTED)

set_target_properties(SofaSimulationCommon PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/SofaSimulation"
  INTERFACE_LINK_LIBRARIES "SofaCore;SofaSimulationCore"
)
(...)
```

It seems that the target SofaSimulationCore is missing the line
`INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/SofaSimulation"`

@guparan I tried to play a little bit with the `sofa/simulation/CMakeLists.txt` to make it work but I failed miserably. You probably have a better idea why this is happening.
______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Well spotted @jnbrunet :+1: 

This is due to the fact that SofaSimulationCore is part of the SofaFramework package and NOT the SofaSimulation package.
I think I wanted to make things simpler by installing SofaSimulationCore under SofaSimulation but I forgot to set the target_include_directories accordingly (as you saw by yourself).

I think the most consistent solution is to install SofaSimulationCore back in SofaFramework by setting, in sofa/simulation/CMakeLists.txt, `sofa_install_targets(SofaFramework ${PROJECT_NAME} "SofaFramework/sofa/simulation")`.

**Comment by jnbrunet** [comment]
Okay, I guess we will also need to change SofaSimulationCommon and others since right now they are installing into the package SofaSimulation.

**Comment by guparan** [comment]
That's were it goes non-logical...
Historically, in SOFA we have:
```
SofaFramework package
    SofaCore: SofaKernel/framework/sofa/core
    SofaDefaultType: SofaKernel/framework/sofa/defaulttype
    SofaHelper: SofaKernel/framework/sofa/helper
    SofaSimulationCore: SofaKernel/framework/sofa/simulation
SofaSimulation package
    SofaSimulationCommon: SofaKernel/modules/SofaSimulation/SofaSimulationCommon
    SofaSimulationGraph: SofaKernel/modules/SofaSimulation/SofaSimulationGraph
    SofaSimulationTree: SofaKernel/modules/SofaSimulation/SofaSimulationTree
```

So by just changing the install dir of SofaSimulationCore we will retrieve consistency between install architecture and CMake packages.

**Comment by jnbrunet** [comment]
Alright, it seems the config.h is also needed. This is what I have by simply putting back SofaSimulationCore in SofaFramework.

**CMakeLists.txt**
```
cmake_minimum_required(VERSION 3.1)
project(mymy)

find_package(SofaFramework)
add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} SofaSimulationCore)
```

**main.cpp**
```
#include <sofa/simulation/MechanicalMatrixVisitor.h>
int main () { return 0;} 
```
**Result**
```
sofa/build/install/include/SofaFramework/sofa/simulation/simulationcore.h:25:10: fatal error: sofa/simulation/config.h: No such file or directory
   25 | #include <sofa/simulation/config.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by guparan** [comment]
How can you do `#include <sofa/simulation/simulationcore.h>` and not `#include <sofa/simulation/config.h>` ? 
Both files are in the same place :confused:

**Comment by jnbrunet** [comment]
Except it is not !

`install/include/SofaSimulation/sofa/simulation/config.h`
`install/include/SofaFramework/sofa/simulation/simulationcore.h`

**SofaSimulation** include path is only included if I link against **SofaSimulationCommon**, **SofaSimulationTree** or **SofaSimulationGraph**. Here I don't need those targets, but only the **SofaSimulationCore** target.

**Comment by jnbrunet** [comment]
The config.h here clearly seems to be used within SofaSimulation modules. I guess the clean solution here is to remove the inclusion of this file in SofaFramework.
