### ISSUE TITLE
Bug in sofa::defaulttype::Quat fromEuler method

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1209]
```cpp
sofa::defaulttype::Quatd::fromEuler(0.0, 180*(M_PI/180), 20*(M_PI/180)); 
> -0.173648 0.984808 -1.16901e-07 -6.62978e-07
```
Instead of 
[ 0.1736482, 0.9848078, 0, 0 ]

according to https://www.andre-gaschler.com/rotationconverter/ which is using three.js code.

______________________________________________________

Suggested labels:

**Comment by fredroy** [comment]
After discussion with @epernod, Quat::FromEuler creates Quaternion with ZYX order (which is implied, no doc says this 😿 ).
Therefore there is actually no bug with the actual code, but a nice addition would to have a "order" parameter, with the value "ZYX" by default.

**Comment by epernod** [comment]
kdo: https://github.com/mrdoob/three.js/blob/dev/src/math/Quaternion.js#L199
