### ISSUE TITLE
Small bug in TopologicalChangeProcessor.cpp

### ISSUE THREAD

**Issue by fangzhouzisb** [sofa-framework/sofa#1213]
In TopologicalChangeProcessor.cpp, there is a line:
SReal d = - (points[0][0] * c + points[0][1] * b + points[0][2] * c );
![1](https://user-images.githubusercontent.com/44138988/68838628-fa0cfd00-06f9-11ea-8280-a7161df695a2.jpg)
I think it should be changed to 
SReal d = - (points[0][0] * a + points[0][1] * b + points[0][2] * c );

______________________________________________________

Suggested labels:

**Comment by epernod** [comment]
Hi,

yes you are right, thanks!
Do you have a small use case where you could see that bug? (it could be helpful to create a test).

Could you push the fix in a PR?

**Comment by fangzhouzisb** [comment]
Hello @epernod 
I did not pull a request because I thought I had to clone the branch and it would be a long time.
I just want to know about how the topological modification is working in Sofa.
And what about your progress in volumetric cutting?  I recently read a paper and I think I may help out.
