### ISSUE TITLE
CMake error in SofaGui.cmake when Modeler is compiled

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/sofa#1271]
If you compile Modeler, in SofaGuiTargets.cmake there are some references to tinyxml but that target is never searched. In that scenario, SofaPython3 can't be built out of tree (and probably any other cmake project that does `find_package(SofaGui)`) as the cmake fails for not finding tinyxml. 

Removing the Modeler removes the tinyxml references.

**Comment by damienmarchal** [comment]
Hi @jjcasmar,

Thanks for reporting. I let our cmake wizard @guparan have a look at that :).

**Comment by jnbrunet** [comment]
> Hi @jjcasmar,
> 
> Thanks for reporting. I let our cmake wizard @guparan have a look at that :).

Too late @damienmarchal  ;-)

We had this problem in the team and never figured out it was coming from some people having the Modeler activated. Thanks @jjcasmar for finding where it was coming from

**Comment by guparan** [comment]
Thanks for the quick fix @jnbrunet :+1: 

@jjcasmar @sofa-framework/reviewers 
**Please note that Modeler support has been discontinued since March 2019.**

**Comment by jjcasmar** [comment]
@guparan I normally use the Modeler as a way to view what's in the factory. I write my scenes in python, but I dont know the name of the objects or which properties it has, so the Modeler is a way to view that. Is there any other way?
