### ISSUE TITLE
Unable to create component

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/sofa#1293]
I have a multimap in a plugin and I am unable to create it. 
The header file looks like this
```
template <typename TIn>
class CPFMapping : public sofa::core::MultiMapping<TIn, TIn>
public:
    SOFA_CLASS(SOFA_TEMPLATE(CPFMapping, TIn),  //
               SOFA_TEMPLATE2(sofa::core::MultiMapping, TIn, TIn));
    CPFMapping()
        : Inherit()
        , m_C(initData(&m_C, "C", "Cluster Matrix"))
    {
    }
...
};
```

and I register in the factory like this:
```
static int register_testComponent =
    sofa::core::RegisterObject("CPFMapping").add<CPFMapping<sofa::defaulttype::Vec3Types>>();
```

When trying to create the component with python
```
    final.addObject("CPFMapping",
                              template="Vec3",
```

I get the following error
```
The object is in the factory but cannot be created.  
Requested template: Vec3d,Vec3d(Vec3d,Vec3d)  
Available templates: Vec3d,Vec3d, 
```
I have tried `Vec3`, `Vec3d`, `Vec3,Vec3` and `Vec3d,Vec3d` without success. 
Not sure if this is a bug in SOFA or if I am doing something wrong with my component.

**Comment by jnbrunet** [comment]
Hi @jjcasmar 

MultiMapping need both an 'input' and 'output' data attributes pointing to valid mechanical objects.

With your example:
`final.addObject("CPFMapping", template="Vec3", input="path/to/mo1", output="path/to/mo2" )`

We are working on better diagnostic message for such failed object creation, see #1266 and #1294

**Comment by jjcasmar** [comment]
Hi. I completely thought it was fromModels and toModels. I'll test with input and output, thanks!

**Comment by jjcasmar** [comment]
Its working fine with the input/output. Sorry for the noise
