### ISSUE TITLE
Cmake  cfg creates "MinSizeRel, Release, RelWithDebInfo" files in CMakeCache/bin

### ISSUE THREAD

**Issue by IngmarVoigt2** [sofa-framework/sofa#1331]
When I try to compile SOFA (on Windows), I observed that apparently some part of the build system (CMake? Or some pre/post-build event) tries to create output folders in the `bin` subfolder  of the CMake cache for all the different MSVC build configurations created by  Cmake (i.e. Debug, MinSizeRel, Release, RelWithDebInfo), **but instead of creating folders generates some obscure binary files with the same name**

This seems to be ok for the first compilation, where MSVC seems to be faster than the faulty script. E.g. when starting with Debug, I do not see any issues, however after finishing that and trying to compile in Release, MSVC compiler complains that e.g. (same for all other targets)

> Error	MSB3191	Unable to create directory "E:\work\dev\SOFA\sofa\build\bin\Release\". Cannot create "E:\work\dev\SOFA\sofa\build\bin\Release" because a file or directory with the same name already exists.	

until I manually remove this useless extra **"Release" file** (which was meant to be a folder)

______________________________________________________

Suggested labels: bug (minor)

**Comment by IngmarVoigt2** [comment]
actually this seems to happen during CMake config (not during "normal" MSVC compilation).
Also note that I am using v19.12, not master (so you might have already solved this?)

**Comment by epernod** [comment]
Hi @IngmarVoigt2 ,
thanks for the report. Indeed we noticed that as well with recent version of SOFA.
I'll investigate asap and let you know.

**Comment by fredroy** [comment]
Fixed in #1347
