### ISSUE TITLE
CGALPlugin not compiling with latest CGAL

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/sofa#1334]
CGALPlugin fails to compile with the newest CGAL version. There is an error related with std::enable_if_t, which I have workarounded setting the minimum c++ version of CGALPlugin to C++14 but then it gives several error when compiling the MeshGenerationFromImage component and I am not sure how to fix it.

**Comment by epernod** [comment]
Hi, 
could you specify which version of CGAL and which version of SOFA you are using.
Could you past the error log as well
Thanks

**Comment by epernod** [comment]
Fix by PR #1522
