### ISSUE TITLE
Runsofa.exe can't find entry

### ISSUE THREAD

**Issue by YulinLi0** [sofa-framework/sofa#1364]
I have installed via the souce code method of SOFA
All the build and compile process has successed but I can not open the runsofa test binary file successfully.
It always says that: the runsofa can not find its entry to link to the libpng16.dll 
![image](https://user-images.githubusercontent.com/27597690/81058246-e78ea780-8e82-11ea-8cfc-2d698a2637dd.png)
That is very weird because I don't know how is this .exe related to my anaconda 3 which include a python 3.7 (I have python 2.7 installed and my  sofapython is built successfully). And then I find that the "sofa-windows-dependency-pack" include this .dll file so I replace it in the anaconda directory and  it can find  its entry but gives me another error like this:
![image](https://user-images.githubusercontent.com/27597690/81058659-ba8ec480-8e83-11ea-8069-504741e99e43.png)
I really don't know why sofa go to my anaconda directory to find that .dll and I don't know where I was wrong, I use vs2019 to generate the runsofa binary successfully

Hope to be reply!

______________________________________________________

Suggested labels:

**Comment by fredroy** [comment]
Sorry for the (big) delay 😥
Usually this problem with libpng means that you compile and link SOFA with the libpng.h. libpng.lib included from the sofa-windows-dependency-pack but your system is using an other libpng.dll in your SYSTEM. 

I suppose you have ..../Anaconda3/Library/bin in the PATH environment variable. 
So you have a mismatch between libpng's version (and libpng is bothersome for that).
Make sure you load the good dll when executing runSofa. 
The "good" dll is supposed to be copied from sofa-windows-dependency-pack with the binaries of the build directory.

**Comment by fredroy** [comment]
I will suppose `no news, good news` and close this issue 🤫
Feel free to re-open if necessary.
