### ISSUE TITLE
In pdb, autocompletion on Sofa objects behave in a strange way

### ISSUE THREAD

**Issue by MarcoMagl** [sofa-framework/sofa#1374]
When setting a breakpoint with `pdb` in python, Sofa objects' attributes tend to arranged in a strange way. 
For instance, in the screenshot attached, I typed `obj.` + TAB to visualize the different methods/attributes available for `obj` where `obj` is a `Sofa.Node` object, and everything get mixed up in the terminal.

Note: I tested with other native python classes and numpy objects, and everything is displayed fine in my terminal in those cases.

<img width="1214" alt="Screenshot 2020-05-08 at 12 13 39" src="https://user-images.githubusercontent.com/24277749/81396283-686cce00-9125-11ea-936b-34b66e67cfb2.png">

______________________________________________________

Suggested labels: bug (minor)

**Comment by fredroy** [comment]
SofaPython2 is deprecated, please try in SofaPython3 and reopen the issue if needed
