### ISSUE TITLE
DefaultMultiMatrixAccessor suspicious warning

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#145]
Clang compiler gives a suspicious warning (for a long time now):
`sofa/SofaKernel/modules/SofaBaseLinearSolver/DefaultMultiMatrixAccessor.cpp:485: warning: variable 'it' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]`

It is just an information to people that may use DefaultMultiMatrixAccessor massively.
(Hadrien and François J could also be interested)

**Comment by damienmarchal** [comment]
Is this issue solve and ready to be closed ?

**Comment by damienmarchal** [comment]
No one seems to care about this issue.

**Comment by JeremieA** [comment]
I flagged your message to have a look later. It does seem like a bug, however it is in a part of the code that was never finished (creating mechanical matrices including contributions below mappings), so is not currently used. As far as I know, for the same functionality within the Compliant/Flexible plugins they used a completely rewritten matrix construction code. This issue might be one reason why this version of the algorithm is not working, but there are probably other bugs in this code as well...

Thanks for the notification !

**Comment by guparan** [comment]
Fixed by #364 
Double incrementation was due to a mistake changing a while into a for. See 44ca866ec17a4c6fcb9facec338423e3d2b3f4c4
