### ISSUE TITLE
framework_test: existing.txt

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#146]
What is the file SofaKernel/framework/framework_test/resources/existing.txt?
Does it really need to be pushed? Could it be removed and added to .gitignore?
It seems to be modified when running the test.

**Comment by damienmarchal** [comment]
@matthieu-nesme  you are right the "existing.txt" file is created to validate the behavior of the FileMonitor API. It should be added to .gitignore as well as probably removed when the test terminates.
Edit: typos

**Comment by damienmarchal** [comment]
Let's close it (even before the merge of the PR)
