### ISSUE TITLE
Confusing error when compiling sofa

### ISSUE THREAD

**Issue by AlbanOdot** [sofa-framework/sofa#1462]
Hello,

I'm trying to compile sofa from a fresh ubuntu install (so there is no conflict between software versions) and I can't process what this error means. Is it found or not? Is it the version that's too old or too new ? The displayed version correspond to the one installed by aptitude. Any hint / solution is welcome.

``
$ cmake ..
``
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Install prefix: /home/thebigone/projects/sofa/build/install
-- Found PythonInterp: /usr/bin/python3.8 (found version "3.8.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
CMake Deprecation Warning at CMakeLists.txt:225 (message):
  Deprecated components are activated (SOFA_WITH_DEPRECATED_COMPONENTS
  variable is ON)

-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
**CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: system filesystem program_options) (found
  version "1.71.0")**
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  SofaKernel/SofaFramework/SofaMacros.cmake:526 (find_package)
  SofaKernel/modules/SofaHelper/CMakeLists.txt:6 (sofa_find_package)

-- Configuring incomplete, errors occurred!
See also "/home/thebigone/projects/sofa/build/CMakeFiles/CMakeOutput.log".
See also "/home/thebigone/projects/sofa/build/CMakeFiles/CMakeError.log".

``
$ sudo apt install libboost-dev
``
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**libboost-dev is already the newest version (1.71.0.0ubuntu2).**
The following packages were automatically installed and are no longer required:
  libdrm2:i386 libexpat1:i386 libglapi-mesa:i386 libglvnd0:i386 libx11-xcb1:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386 libxdamage1:i386 libxfixes3:i386
  libxshmfence1:i386 libxxf86vm1:i386
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 107 not upgraded.

Alban.

______________________________________________________

Suggested labels:

**Comment by jnbrunet** [comment]
Hey @AlbanOdot ,

From the [documentation](https://www.sofa-framework.org/community/doc/getting-started/build/linux/#core-required):

> - Boost (>= 1.65.1)
`sudo apt install libboost-all-dev`

So you need to install  **libboost-all-dev** and not just **libboost-dev**

J-N

**Comment by AlbanOdot** [comment]
Yup i just saw it now... my bad.
Thanks !
