### ISSUE TITLE
Wrong boost dll copy while building On Windows in Debug mode

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1501]
Building in Debug on Windows copy dll like boost_program_options-vc141-mt-x64-1_72.dll instead of boost_program_options-vc141-mt-gd-x64-1_72.dll 
into the /bin/Debug/ folder.

Config: New build from scratch, master version ~15th August

______________________________________________________

Suggested labels:

**Comment by fredroy** [comment]
Is it still on-going ?
On my setup `(Win10/MSVC19/CMake3.19.2/boost1.74)`, the Debug build contains both versions of the boost dll's mt-gd and mt.
So it seems it has been fixed since.

**Comment by fredroy** [comment]
Seems to be fixed and anyway SOFA does not use (compiled) boost libraries anymore.
