### ISSUE TITLE
Assigning to rest_position of MO in Python crashes

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/sofa#1517]
I have a debug compilation of SOFA with SofaPython3 plugin and when I try to assign in python to the rest position of a mechanical object, I get a crash due to the MO having size = 0.

I am not sure how I should resize it from python or how to fix this. 

```    
xN_mo = xNObject.addObject("MechanicalObject", template="Vec1", name="xN_MO")
# xN_mo.resize(3) // Doesnt work
# xN_mo.size = 3 // Doesnt work
xN_mo.rest_position = np.array([[0,0.25,0.75]]).T
```

This is the actual code, but no idea how to actually make it work... is this a known bug? How should I make it work?

**Comment by damienmarchal** [comment]
Hello @jjcasmar, 

thanks for reporting an issue.  

My first guess is that this is not related to sofapython3 but more on the design of MechanicalObject that does not update the different data fields (position, rest_position, etc) in a coherent manner. 
I think that the recent PR made by @marques-bruno  try to fix that: https://github.com/sofa-framework/sofa/pulls 

Damien

**Comment by jjcasmar** [comment]
Thanks @damienmarchal 

Is there any workaround I can use right now to be able to set the rest_position? Maybe I need to pass the position during the creation of the object?

**Comment by damienmarchal** [comment]
Yes, 

You can set the size of all buffers at init by doing: 
```python
xN_mo = xNObject.addObject("MechanicalObject", template="Vec1", name="xN_MO", size=100000)
```

**Comment by jjcasmar** [comment]
I have tried that, but is not running yet correctly. I get the same assert

```
    xNObject = coarseObject.addChild("xN")
    xN_mo = xNObject.addObject("MechanicalObject", template="Vec1", name="xN_MO", size=3)
    xN_mo.rest_position = np.array([[0,0.25,0.75]]).T
```

Is the assignment to rest_position correct?

**Comment by jjcasmar** [comment]
Ive been able to solve by providing the size and the rest_position in the addObject line. 
Then I can easily asign to position or other datas.
