### ISSUE TITLE
SOFA-NG: Helper/Defaulttype reorganization

### ISSUE THREAD

**Issue by fredroy** [sofa-framework/sofa#1521]
1-Defaulttype is supposed to depend on Helper, and Helper on nobody (except eventual third-party library like Eigen)
But things in Helper includes stuff in Defaulttype (typically Vec, Mat and Quat, this one even worse with Quat/Quater brainf*ck)

2- The contents of those two Kernel modules are confusing.
It seems that Defaulttype was supposed to only contain type for templated element in the subsequent Sofa modules; e.g for MechanicalObject. Those types are (not extensive): VecXTypes (and their float/double template),  RigidTypes, SolidTypes.
One could theoretically not use Defauttype and creates its own "types". Actually this is what Flexible does.

So the goal would be to:
 - leave the VecTypes, etc into Defaulttype,
 - put the other "things" into Helper
 - Reorganize Helper to be less messy as well.

The issue/question is how to re-organize Helper (which is a mess by itself).

______________________________________________________

Suggested labels:

**Comment by fredroy** [comment]
A draft: (the existing ones first)
-io
-gl
-logging
-messaging
-system
-testing
-types (with Vec, Mat, Quat, Frame, BaseMatrix, BaseVector, BoundingBox, Ray)
-basictypes (fixed_array, vector, map etc)
-algo (Polynmial_LD, decompose, Mat_*, lcpsolver)
-utilities (rest of the mess)

**Comment by damienmarchal** [comment]
Hello Fred,

Thanks for re-opening the debate. 

I fully agree with you and support a move of the the "basic types" in sofa/helper/types. This is actually easy. I think you plan to also move AbstractTypeInfo (important to have to make Data out of types) there so you specify the type directly in sofa/helper/types ? 

Every types should go in sofa/helper/types.
The other re-organisation of the sofa/helper mess should be left for a different day :) 


[debate closed]

EDIT: Your suggestion is not following sofang3 doc from @guparan :)
EDIT2: And re-reading https://github.com/guparan/sofa2ng/blob/master/recipes/Sofa.Helper.Types.rcpy I think it was well done :)

**Comment by fredroy** [comment]
True that I did not really think about the NG thing 🥴
But the Helper in the doc is more or less my "utilities" and the other dir a module themselves.
I am ok with that by the way.
Most important is the types thing indeed 💋

**Comment by damienmarchal** [comment]
As we know how to do the move in a smooth way...it is only a matter of making PR :) 
Another easy move to do would be to change the few files in SofaHelper that do #include <sofa/core/XXXX> 

vectorData & vectorLink being the most weird there.

**Comment by fredroy** [comment]
STC10 Feedback: (https://annuel2.framapad.org/p/sofang-v6)

SofaFramework will be re-designed like that:
```
* Type (Vec, Mat, Quat, Frame, BaseMatrix, BaseVector, BoundingBox, Ray, ...) ( + leurs algos)
         * StdType (fixed_array, vector, map, etc)
* Geometry (Triangle, Tetra...)
         * Topology
         *  Mesh
* Helper
        * Config
        * Messaging
        * Logging
        * Image
        * BVH
        * IO
        * System
        * Visual
* DefaultType (VecTypes, RigidTypes, ...)
* Core
        * Data (#1605 #1611 .... )
             * TypeInfo (TypeInfo_Vec, TypeInfo_Quat, etc)
             * DataTypeInfo (DataTypeInfo_Vec, DataTypeInfo_Quat)

 * Simulation
 * Testing (to isolate the dependency gtest)
 * OpenGL (to isolate the dependency opengl)
```
