### ISSUE TITLE
Documentation on new MechanicalObject templates

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/sofa#1524]
I am trying to add new types to template MechanicalObject. So far I have tried to create this:

```
using Vec9 = sofa::defaulttype::Vec<9, double>;
using F33D = sofa::defaulttype::StdVectorTypes<Vec9, Vec9, double>;
```

and tried to create the specializations that I think I need, but when creating the scene from a python scene, it says 
`[WARNING] [MechanicalObject(F)] Template F33D incorrect, used Vec3d`

The final idea is to actually use a 3x3 matrix, but I decided to go first with the Vec9 approach as I thought it would be easier since it just a specialization of an already supported type for MechanicalObject, but its clear that this is not easy.

Could someone provide some documentation on how to create types for MechanicalObject? Which functions/classes/types should be specialized?

**Comment by damienmarchal** [comment]
Hello @jjcasmar 

In order to added a new template to a component you need to add that where the object is registered 
to the component factory as in MechanicalObject.
```cpp
int MechanicalObjectClass = core::RegisterObject("mechanical state vectors")
        .add< MechanicalObject<Vec3Types> >(true) // default template
        .add< MechanicalObject<Vec2Types> >()
        .add< MechanicalObject<Vec1Types> >()
        .add< MechanicalObject<Vec6Types> >()
        .add< MechanicalObject<Rigid3Types> >()
        .add< MechanicalObject<Rigid2Types> >();
```

This is where the component become accessible to the runtime point of view. The name you can use in the scene is automatically generated out of the c++ name. But you can tune that as done in RigidTypes. I'm not 100% sure but this should correspond to these lines in RigidTypes.h
```cpp
typedef StdRigidTypes<2,double> Rigid2dTypes;
typedef RigidMass<2,double> Rigid2dMass;
template<> inline const char* Rigid2dTypes::Name() { return "Rigid2d"; }
``` 

Hope this will help you,

**Comment by jjcasmar** [comment]
I have tried something like that and doesnt work. Following what I found in the Flexible plugin I have two files

DeformationGradientTypes.h
```
using Vec9 = sofa::defaulttype::Vec<9, double>;
using F33D = sofa::defaulttype::StdVectorTypes<VNCS::Vec9, VNCS::Vec9, double>;

}  // namespace VNCS

template <>
struct sofa::defaulttype::DataTypeInfo<VNCS::F33D::Deriv>
    : public FixedArrayTypeInfo<VNCS::F33D::Deriv, VNCS::F33D::Deriv::total_size> {
    static std::string name()
    {
        std::ostringstream o;
        o << "F33D";
        return o.str();
    }
};

template <>
struct sofa::defaulttype::DataTypeName<VNCS::F33D::Coord> {
    static const char *name() { return "F33D::CoordOrDeriv"; }
};

template <>
inline const char *VNCS::F33D::Name()
{
    return "F33D";
}
```

and in my initPlugin.cpp

```
#include "DeformationGradientTypes.h"
...
template class sofa::core::State<VNCS::F33D>;
template class sofa::component::container::MechanicalObject<VNCS::F33D>;
static sofa::defaulttype::RegisterTemplateAlias alias0("F33D", VNCS::F33D::Name());
```

All this gives me the error I showed previously

**Comment by damienmarchal** [comment]
I didn't spotted where your are registering the typed component in the object factory ? 

Should look like: 
```cpp
int MechanicalObjectClass = core::RegisterObject("mechanical state vectors")
        ... 
        .add< MechanicalObject<VNCS::F33D> >() 
```

**Comment by jjcasmar** [comment]
Oh you are right. It was commented a few lines below. Thanks for spotting it. Ill try to make it work now with my real data type (Mat3x3)

**Comment by damienmarchal** [comment]
Great. I close the issue then.
