### ISSUE TITLE
 [SofaGeneral] Pluginize all modules

### ISSUE THREAD

**Issue by fredroy** [sofa-framework/sofa#1529]
- [x] SofaGeneralAnimationLoop
- [x] SofaGeneralDeformable
- [x] SofaGeneralExplicitOdeSolver
- [x] SofaGeneralImplicitOdeSolver
- [x] SofaGeneralLinearSolver
- [x] SofaGeneralLoader
- [x] SofaGeneralMeshCollision
- [x] SofaGeneralObjectInteraction
- [x] SofaGeneralRigid
- [x] SofaGeneralSimpleFem
- [x] SofaGeneralTopology
- [x] SofaBoundaryCondition
- [x] SofaConstraint
- [x] SofaGeneralEngine
- [x] SofaGraphComponent
- [x] SofaTopologyMapping
- [x] SofaUserInteraction
- [x] SofaGeneralVisual

SofaGeneral is still forcefully compiled so there wont be any option to compile the modules separately until everything is done.

**Comment by guparan** [comment]
SofaGeneral is now fully pluginized! :tada: 
Thanks a lot @fredroy :+1: :+1: :+1:
