### ISSUE TITLE
Removing components xxxSetTopologyAlgorithms

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1538]
In dynamic topology you need to add 4 components:

1. TriangleSetTopologyContainer  ///< contains all the buffers to define the topology structure
2. TriangleSetTopologyModifier  ///< friend class handling all low level operation on the topology container
3. TriangleSetTopologyAlgorithms ///< class to store more complex algorithms base only on topology structure (will use Modifier and Container)
4. TriangleSetGeometryAlgorithms ///< class to store all complex algorithms involving topology and geometry (3D positions) structure (will use Modifier and Container)

After quick investigation the 3rd one is often nearly empty or contains algorithms that in fact need geometry information such as edge length, direction, area, volume etc.

So I propose to move all methods of xxxSetTopologyAlgorithms into the xxxSetTopologyModifier if it is really only topological operations or to xxxSetGeometryAlgorithms for better clarification of the code.

This will concern:
- PointSetTopologyAlgorithms
- EdgeSetTopologyAlgorithms
- TriangleSetTopologyAlgorithms
- QuadSetTopologyAlgorithms
- TetrahedronSetTopologyAlgorithms
- HexahedronSetTopologyAlgorithms

Of curse I will add Deprecated component and I can also let the methods and forward to the new one with a deprecated message. 
And start to add tests on those methods...

**Comment by fredroy** [comment]
👍
I am ok with that but I don't really use a lot of the topology POWER 💪

**Comment by epernod** [comment]
you are the voice of the consortium now! so I take that as a green light 🛩️

**Comment by fredroy** [comment]
I approve it 🙋‍♂️ but hopefully later on, guys with problems wont complain...
