### ISSUE TITLE
Tests on VS2013 crashing with exit code 53

### ISSUE THREAD

**Issue by flargilliere** [sofa-framework/sofa#155]
Hey guys,

apparently, 30 tests out of 32 crash with exit code 53. (And bring some bad red color to the beautiful dashboard)

This code is "The network path was not found". Is every binary/file where it's supposed to be ?

NB : Is this config worth the trouble ? Or should it be removed as VS2015 is freely available ? (I heard something about people **needing** it but...)

**Comment by bcarrez** [comment]
Fixed :-)

**Comment by flargilliere** [comment]
Well done !
