### ISSUE TITLE
Unable to load plugin when sofa is installed

### ISSUE THREAD

**Issue by jjcasmar** [sofa-framework/sofa#1560]
I have compiled and installed SOFA master branch with the CGAL plugin. In the compilation folder, under lib, I have libCGALPlugin.so, and if I do ldd libCGALPlugin.so, it founds all the dependencies. However, if I install SOFA, (`cmake --build . --target install`), libCGALPlugin.so is moved to a plugins folders, under `<install>/plugins/CGALPlugin/lib`, and ldd now shows that libCGALPlugin.so can't find all the dependencies. 

Ive search a bit and apparently, the rpath is set to `$ORIGIN/../lib`, which is okay when the library is directly in the `<builddir>/lib` folder, but fails if the library is in `<installdir>/plugins/CGALPlugin/lib/`. 

Due to this, its not possible to load the plugin. 

This happens not only with with plugins, but for example also with `libSofaComponentAll.so`. It tries to load `libSofaOpenglVisual.so`. In the <builddir> works fine because both are under `<builddir>/lib`, but when installed, `libSofaOpenglVisual.so` is moved to `<installdir>/lib/SofaOpenglVisual/lib`, where `libSofaComponentAll.so` is not searching.

**Comment by jnbrunet** [comment]
Thank you for the report @jjcasmar 

Indeed, this looks like a bug. We will have to look at this. Maybe @guparan or @fredroy have an idea here?

**Comment by guparan** [comment]
Hi @jjcasmar, thanks for your report! This issue is on our weekly TODO-list :wink:

**Comment by fredroy** [comment]
This issue has been fixed (or should have been 😛) since the release of the v20.12.
Install and out-of-tree compilation have been a priority for this release.
If there is still some issue on this topic, please don't hesitate to re-open this issue.
