### ISSUE TITLE
Fix duplicate usage of string 'points' for data name in PointSetTopologyContainer

### ISSUE THREAD

**Issue by loicgarry** [sofa-framework/sofa#1591]
Hi, I noticed that both the `d_initPoints` and `points` data can be initialized using the same string: "points".
```
PointSetTopologyContainer::PointSetTopologyContainer(int npoints)
    : d_initPoints (initData(&d_initPoints, "position", "Initial position of points",true,true))
    , m_pointTopologyDirty(false)
    , nbPoints (initData(&nbPoints, (unsigned int )npoints, "nbPoints", "Number of points"))
    , points(initData(&points, "points","List of point indices"))
{
    addAlias(&d_initPoints,"points");
}
```
This can lead to `d_initPoints` being initialized with a list of indices if no "positions" were set. From what I saw the alias was there first, to prevent some scenes from being broken.
This bug was last introduced in https://github.com/sofa-framework/sofa/commit/5b8648f9675dcbbe272829cfab3d6ba16d1ba16d but seems to go back to https://github.com/sofa-framework/sofa/commit/570b09b06744307e4bc1223b3d228974faab6cf5.

**Comment by damienmarchal** [comment]
Hi @loicgarry 

This seems a true problem.
