### ISSUE TITLE
Cleaning printLog mis-usage

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#160]
@thomas-lemaire pointed that in several place there is mis-usages of printLog. 
We should clean that by clearly defining what is the correct behavior. 

We can clean the printLog stuff independently but this is in fact connected to the msg_* API (https://www.sofa-framework.org/community/doc/programming-with-sofa/logger/) as well as this PR(https://github.com/sofa-framework/sofa/pull/106) which are attempts to lay down the foundations for a general handling of all the messages in Sofa.

**Comment by thomas-lemaire** [comment]
I think the clean should not be done independently, if you remove the if (printLog) test many components are going to fill their "log buffer", hence increase memory usage

**Comment by damienmarchal** [comment]
@thomas-lemaire currently I see that some components are doing
```cpp
if(printLog) sout << 
```
While the 'sout' is already checking the printLog which is redundant. This is what I'm refering as mis-usagse. To me the cleaning consist in defining what is the right pattern to employ and this may (or not) result in removing the if(printLog) from the component and replace them with the use of 'sout'. 

About the link with PR106. With the PR a dedicated message handler has to be installed in the application or the scene to activate loggin into component... this is done with the following code 
```cpp
MessageDispatcher::addHandler(&MainPerComponentLoggingMessageHandler::getInstance()) ;
```
But currently this is not done in runSofa or any other app and the messages are not added to the log. This is why I'm saying the PR is independent and is without side effect. 

When the printLog expected behavior is clear the current log 'to the big string' should be removed and replaced by installing the logging proposed in PR106.

**Comment by damienmarchal** [comment]
My best solution is currently to use the following macro
```cpp
   msg_warning_when(cond) if(cond) msg_error(this) 
   msg_error_when(cond) if(cond) msg_error(this) 
```

This allow to write onliner's  as in 
```cpp
   msg_warning_when(printLog) << "Something goes wrong" << std::endl;
   msg_warning_when(fileNotOpen) << "Unable to open file" ;
```

I suggest to rename 'printLog' by 'verbosityLevel'.

**Comment by damienmarchal** [comment]
Actually i think 'msgInfoVerbosity' may be a better name because it explain that the control is only on the amount of INFO messages and that it left untouched  the warning or error (that are import functional messages and shouldn't probably be removed).

**Comment by thomas-lemaire** [comment]
I see the benefit of having generic msg_xyz_when(cond) message, maybe they should be more general and not tied to a "this" pointer, like msg_xyz_when(sender, cond)

In the component itself, I would rather see
component_msg_info() if (printLog) msg_info(this)
with "printLog" data name updated
I also think "warning" and above (error...) levels should not depend on a flag
And last, I would call that flag "msgInfoVerbose" to better match what is a boolean flag name

here my 2 cents ;-)

**Comment by damienmarchal** [comment]
My dream would be to have: 
```cpp
msg_warning() 
msg_error() 
msg_info()

msg_info_when(printLog > 5)
msg_warning_when( fileNotFound) 
msg_error_when(toto==tata) 
```
With an an automatic selection between the 'this' and 'string' version. 

I in my mind msgInfoVerbosity was not a boolean but something with different levels (NONE, LOW, MEDIUM, HIGH) . Maybe useful as well as overkilling.

**Comment by thomas-lemaire** [comment]
if msgInfoVerbosity is a level,and you have s.t. like 
> msg_info_when(printLog > 5) 
then the level is not homogeneous : first name of the macro (error, warning, info - isn't there a msg_debug() macro too ?), and then in the condition in msg_info_when() 

well, this might be "my" concept of level (this is also the one in the qt libs I am familiar with) 

about the automatic switch between "this" and "string" versions, this would be awesome, however I have no idea on how to achieve this with c++ macro (maybe a special include that would replace the string version by the this version when you are in a component source file ?) 

thomas 

----- Mail original -----

**Comment by damienmarchal** [comment]
Hi thomas,

Maybe the use of 'printLog' in my example was ambiuous sorry... 

To me the 'error', 'warning', 'info' specifiers is the message 'type' and the set of types is un-ordred so it cannot be controlled via a single level. 
Eg of valid pattern: 
```cpp
   msg_info_when( msgInfoVerbosity < LOW ) << "This is printed often";
   msg_info_when( msgInfoVerbosity >= HIGH ) << "This is printed not so often";
``` 

Eg of in-valid pattern (should be rejected in the PR :)): 
```cpp
   msg_error_when( msgInfoVerbosity < LOW ) << "This is printed often";
``` 

'msgInfoVerbosity' only control the amount of info messages emitted so is nothing related to 
error/warning. 

Instead of level we may also have a 'verbosityMask' to control precisely which message are emitted 
Eg:
```cpp
    msg_info_when( verbosityMask & INFO ) << "blabha";
```
but I think *we shouldn't do that*.

About the 'msg_debug'...it is problematic because there is also a different set of macro for developers that are called dmsg_info, dmsg_warning, dmsg_error()...these dmsg_* macros leads to NO-op when compiled in RELEASE.  So my thinking is that we should remove the msg_debug macro and use their dmsg_* ones instead.

**Comment by damienmarchal** [comment]
@thomas-lemaire After some digging into internet I found a non-portable solution to support the 'non this' version. 

```cpp 
#define INFO_0()    ldmsg_info(this)
#define INFO_1(A)  oldmsg_info(A)
#define INFO_X(x, A, FUNC, ...)  FUNC
#define msg_info(...) INFO_X(, \
                                      ##__VA_ARGS__,\
                                      INFO_1(__VA_ARGS__),\
                                      INFO_0(__VA_ARGS__))
```

I hate (and love) so much these macro trick (template wizard are welcome for a better solution)... 
but with this macro we can now write:
```cpp
   msg_info() << "This is sended with an automatic 'this' parameter' provided as emitter;
   msg_info(this) << "This is sended with an explicit BaseObject provided as emitter " ; 
   msg_info("SomeSPecifcSource") << "This is sended with a string as emitter";
```
which look perfect to me. 

The problem is that this solution is not portable because it uses the ## GCC extension. 
Any idea on how to make a portable solution ?

**Comment by damienmarchal** [comment]
This discussion seems to be over. 
The PR needs to be finalized. 
I close the Issue.
