### ISSUE TITLE
CMake Deprecation Warning when configuring

### ISSUE THREAD

**Issue by harshakarunanayaka** [sofa-framework/sofa#1623]
Hi, I am an university student trying to use sofa for my simulation work. When I try to configure SOFA master with Cmake a "CMake Deprecation Warning at SofaAdvanced/CMakeLists.txt:15 (message):
   SofaAdvanced is deprecated.
   You should now explicitely find (find_package) and link (target_link_library) each module you need within: 
   SofaNonUniformFem

CMake Deprecation Warning at SofaMisc/CMakeLists.txt:21 (message):
   SofaMisc is deprecated.
   You should now explicitely find (find_package) and link (target_link_library) each module you need within: 
   SofaMiscExtra;SofaMiscEngine;SofaMiscFem;SofaMiscForceField;SofaMiscMapping;SofaMiscSolver;SofaMiscTopology"
warning is appearing. however, without crashing it get configured and generates the files. I have build the system on Visual Studio 2019 and it complies without any errors. However, when loading the RunSofa "SofaPython" and "SofaExporter" modules are not loading. I tried using the plugin manager and it reports erros that .dll file is not there. but it is there in the bin and could not add to the plugin manager. So my questions are as follows.
(1)I want to know whether do I have to change any configuration to avoid deprecation warning messages?
(2) loading the sofaphython to runSofa application 
My Cmake out put is as follows.

Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
Install prefix: C:/SOFA/build/master/install
Adding module SofaGeneralVisual
Adding module SofaGraphComponent
Adding module SofaGeneralMeshCollision
Adding module SofaBoundaryCondition
Adding module SofaGeneralAnimationLoop
Adding module SofaGeneralDeformable
Adding module SofaGeneralEngine
Adding module SofaGeneralExplicitOdeSolver
Adding module SofaGeneralImplicitOdeSolver
Adding module SofaGeneralLinearSolver
Adding module SofaGeneralRigid
Adding module SofaGeneralObjectInteraction
Adding module SofaGeneralSimpleFem
Adding module SofaGeneralTopology
Adding module SofaTopologyMapping
Adding module SofaUserInteraction
Adding module SofaSparseSolver
SofaSparseSolver: using built-in metis library
Adding module SofaPreconditioner
Adding module SofaHaptics
Adding module SofaValidation
Adding module SofaDenseSolver
Adding module SofaNonUniformFem
Adding module SofaOpenglVisual
Adding module SofaMiscTopology
Adding module SofaMiscExtra
Adding module SofaMiscForceField
Adding module SofaMiscEngine
Adding module SofaMiscSolver
Adding module SofaMiscFem
Adding module SofaMiscMapping
Adding plugin SofaPython
Adding module SofaExporter
CMake Deprecation Warning at SofaAdvanced/CMakeLists.txt:15 (message):
   SofaAdvanced is deprecated.
   You should now explicitely find (find_package) and link (target_link_library) each module you need within: 
   SofaNonUniformFem

CMake Deprecation Warning at SofaMisc/CMakeLists.txt:21 (message):
   SofaMisc is deprecated.
   You should now explicitely find (find_package) and link (target_link_library) each module you need within: 
   SofaMiscExtra;SofaMiscEngine;SofaMiscFem;SofaMiscForceField;SofaMiscMapping;SofaMiscSolver;SofaMiscTopology

Adding collection SofaComponentAll
SofaTest: optional dependency SofaPython found, Python_test will be built
Adding plugin CImgPlugin
CImgPlugin: TIFF Image Format disabled
CImgPlugin: JPEG Image Format enabled
CImgPlugin: PNG Image Format enabled
Adding plugin SofaMiscCollision
SofaMiscModule: build all maintained sofa components.
SofaMiscCollision: optional dependency SofaSphFluid not found de-activing: <SpatialGridPointModel>
Adding application getDeprecatedComponents
Adding application runSofa
Write Plugin list at C:/SOFA/build/master/bin/plugin_list.conf.default
Configuring done
Generating done

**Comment by fredroy** [comment]
This is WIP in #1696 ...
