### ISSUE TITLE
FileRepository and special characters

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#17]
FileRepository needs to be checked and fixed.

It does not work for sure in some situations, e.g. if a sofa install is copied in a path containing accents on windows, FileRepository does not find the files.

Note I have not go any further, and everything needs to be investigated.
I did not test with the distributed, precompiled package. I did not test on linux...

**Comment by matthieu-nesme** [comment]
I added a test (FileRepository_test) empathizing the problem.
Successing on linux, failing on windows.

**Comment by matthieu-nesme** [comment]
I guess the easiest and safest way to handle that would be to use boost::filesystem
http://www.boost.org/doc/libs/1_62_0/libs/filesystem/doc/index.htm

**Comment by damienmarchal** [comment]
Isn't this issued solved ? by recent comits so we can close it ?

**Comment by matthieu-nesme** [comment]
not it is not
FileRepository_test.findFileWithAccents on windows
