### ISSUE TITLE
MechanicalObject: SOFA_HAVE_NEW_TOPOLOGYCHANGES never defined

### ISSUE THREAD

**Issue by fredroy** [sofa-framework/sofa#1786]
Some code is only enabled if SOFA_HAVE_NEW_TOPOLOGYCHANGES  is defined (and adds a dependency on SofaBaseTopology).
I guess this is related with a new (old?) way to manage topology changes.
But this macro can never be enabled anywhere so I suppose that actually the code is not used at all.
Waiting the opinion of @epernod and if necessary, we will make a PR with the removal of the potential dead code.

(issue coming from #242)

**Comment by epernod** [comment]
will be use soon... I hope... or delete

**Comment by epernod** [comment]
This has been fixed in PR #2867
