### ISSUE TITLE
Preprocessor endif without if

### ISSUE THREAD

**Issue by maddin200** [sofa-framework/sofa#1841]
/modules/SofaGuiQt/src/sofa/gui/qt/GraphVisitor.h line 91

`   bool initSize;
};
}
}
}

#endif // <-- no corresponding if (pragma once used`

same holds for:
sofa-master/modules/SofaGuiQt/src/sofa/gui/qt/WindowVisitor.h line 127

**Comment by fredroy** [comment]
Thank you @maddin200 for your report, this issue should be fixed with #1914
