### ISSUE TITLE
SofaTest<> unrelevant tests

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1935]
Tests inheriting from SofaTest create by default several tests which have no meaning. It was the case for example for SofaMiscTopology_test:

SofaMiscTopology_test/AffinePatch_sofa_test 
SofaMiscTopology_test/LinearElasticity_test 
SofaMiscTopology_test/TopologicalChangeProcessor_test

This is not really an issue... but this means we have a bunch of fake tests

**Comment by fredroy** [comment]
As those tests does not inherit SofaTest anymore, I think this issue is kind of fixed.
Feel free to re-open if it is not actually the case
