### ISSUE TITLE
[RayTraceDetection] Move RayTraceDetection

### ISSUE THREAD

**Issue by alxbilger** [sofa-framework/sofa#2008]
- The scene located in examples/Components/collision/RayTraceCollision.scn freezes after some time (Ubuntu, clang, compiled from sources commit a21a07efcba5e1f814fa2986a45811613bdb8e41)
- The component `RayTraceDetection` is probably not at the right location in `SofaUserInteraction`. I suggest `SofaBaseCollision` or `SofaGeneralMeshCollision`. `BruteForceDetection`, which is similar component, is located in `SofaBaseCollision`. `DirectSAP` and `IncrSAP` are both located in `SofaGeneralMeshCollision`.

**Comment by alxbilger** [comment]
The first point of this issue should be solved with #2076

**Comment by fredroy** [comment]
And the second point should have been fixed with the new architecture.
Setting this issue as fixed and closing then.
