### ISSUE TITLE
GenericWidget has way too many closing brackets '}'

### ISSUE THREAD

**Issue by pedroperrusi** [sofa-framework/sofa#2019]
Hello everyone,

It seems PR (#1719) modernized the namespace opening brackets but not their closing.

I've noticed when updating our repos to post-v20.12 and I'll prepare a PR with a small fix soon.

**Comment by fredroy** [comment]
I am curious about this file, as nobody seems to include it (thus that' s why we did not notice any error)
Where do you use it ?

**Comment by pedroperrusi** [comment]
@fredroy, in our code base we have a few calls like the one below
```
sofa::helper::Creator<sofa::gui::qt::DataWidgetFactory, sofa::gui::qt::GenericDataWidget< Data<TTrackBar<1> >, QTrackBarWidget<1> > >	DWClass_graphUCTrackBar1("TTrackBar<1>",true);
```
To create a trackbar with a custom `QImageWidget`:
```
class QImageWidget : public QLabel {
    Q_OBJECT
public:
    QImageWidget(sofa::gui::qt::DataWidget * parent,const MyData& /*data*/)
    ...
```

Although, personally, I'm not familiar with their usage and haven't coded one of these yet.

**Comment by pedroperrusi** [comment]
QTrackbarWidget is also a custom class that looks like this
```(C++)
template<int C>
class QTrackBarWidget : public QWidget {
//    Q_OBJECT //Cannot declare a Q_OBJECT as the object is template
public:
    typedef Data<TTrackBar<C> > MyData;

    QTrackBarWidget(sofa::gui::qt::DataWidget * parent,const MyData & /*data*/) : QWidget(parent)
```

If I'm not mistaken, the result is an image Data in SOFA associated with a trackbar to update some parameter (eg. filter parameter)
