### ISSUE TITLE
MacOS : 3D viewport is blank (had to downgrade Qt version to fix it)

### ISSUE THREAD

**Issue by bcarrez** [sofa-framework/sofa#2028]
On MacOS, I experienced a big problem since my OS upgrade to Big Sur. 
runSofa viewport remaining blank, either with QGL viewer or OpenGL viewer, with the following error message in the terminal:
```
qt.qpa.openglcontext: Could not create NSOpenGLContext with shared context, falling back to unshared context.
```
I finally figured it out: My Qt version was 5.15.x (installed with brew or the Unified Installer) and there seems to be a problem here, at least with my configuration : Intel Mac, with ATI GPU, MacOS 11.2.3.
**Downgrading Qt to 5.12.5 is a workaround.** It's a dirty fix that works, where a complete reinstall of Xcode and dependencies did not. At least I have a working build of runSofa now :-)

I really have no idea of the exact cause of the problem, maybe related to my Mac configuration, GPU drivers or use of deprecated API by SOFA, but I hope this could help someone with the same problem.

**Comment by fredroy** [comment]
Hello, I tried on a MBA M1, macOS 11.3.1 and 
```shell 
brew list --versions qt5
qt@5 5.15.2
```
and the 3D viewport is displaying the expected scene.
Maybe the 11.3 update fixed few things about OpenGL ?

**Comment by fredroy** [comment]
I am closing the issue for now @bcarrez . If you still encounter the issue with an updated macOS, feel free to re-open.
