### ISSUE TITLE
CGAL Plugin error when compiling SOFA

### ISSUE THREAD

**Issue by Marconefs** [sofa-framework/sofa#2075]
Can someone help me? I am stuck in the following error when compiling SOFA with CGAL plugin:

FAILED: applications/plugins/CGALPlugin/CMakeFiles/CGALPlugin.dir/src/CGALPlugin/CylinderMesh.cpp.o 
/usr/bin/g++ -DCGALPlugin_EXPORTS -DCGAL_MESH_3_VERBOSE=0 -DNDEBUG -DSOFA_BUILD_CGALPLUGIN -I../applications/plugins/CGALPlugin/src -Iinclude/CGALPlugin -I../SofaKernel/modules/SofaCore/src -Iinclude/Sofa.Core -I../SofaKernel/modules/SofaHelper/src -Iinclude/Sofa.Helper -I../SofaKernel/modules/Sofa.Config/src -Iinclude/Sofa.Config -I../SofaKernel/modules/Sofa.Type/src -Iinclude/Sofa.Type -I../SofaKernel/modules/Sofa.Compat/src -Iinclude/Sofa.Compat -I../SofaKernel/modules/Sofa.Topology/src -Iinclude/Sofa.Topology -I../SofaKernel/modules/Sofa.Geometry/src -Iinclude/Sofa.Geometry -I../SofaKernel/modules/SofaDefaultType/src -Iinclude/Sofa.DefaultType -I../SofaKernel/modules/SofaSimulationCommon/src -Iinclude/SofaSimulationCommon -I../SofaKernel/modules/SofaSimulationCore/src -Iinclude/Sofa.SimulationCore -isystem ../SofaKernel/extlibs/json -isystem /usr/include/eigen3 -O3 -DNDEBUG -fPIC -Wno-attributes -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -Wno-padded -pthread -frounding-math -std=gnu++17 -MD -MT applications/plugins/CGALPlugin/CMakeFiles/CGALPlugin.dir/src/CGALPlugin/CylinderMesh.cpp.o -MF applications/plugins/CGALPlugin/CMakeFiles/CGALPlugin.dir/src/CGALPlugin/CylinderMesh.cpp.o.d -o applications/plugins/CGALPlugin/CMakeFiles/CGALPlugin.dir/src/CGALPlugin/CylinderMesh.cpp.o -c ../applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.cpp
In file included from ../applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.cpp:25:
../applications/plugins/CGALPlugin/src/CGALPlugin/CylinderMesh.inl:25:10: fatal error: sofa/gl/template.h: Arquivo ou diretório inexistente
   25 | #include <sofa/gl/template.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by fredroy** [comment]
Hello!
It seems your issue has just been fixed in the latest merged PR (#2065).
So you should either update your master branch (if you are following the master), or cherry-pick the change if not.

**Comment by fredroy** [comment]
No answer since 2 years, considered as solved.
Feel free to re open if it is not the case.
