### ISSUE TITLE
DataFileNameVector and spaces

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#21]
DataFileNameVector is a Data<vector<string>> where the strings are separated by spaces in the string-serialization. So how to include spaces in one of the paths? (right now it is splitting this path into two separated paths).

**Comment by matthieu-nesme** [comment]
Problem demonstrated in the failing tests DataFileNameVector_test.

**Comment by matthieu-nesme** [comment]
In fact the problem is there for any Data<vector<string>>.
For such vectors, the string-serialization could(should) separate strings with a specific character that cannot be on a path, but it would break existing scenes.

**Comment by JeremieA** [comment]
There was a SVector<T> class added in sofa::helper simply to change the stream operators to use commas to delimit values and [ ] to delimit the vector itself (allowing for vectors inside vectors), but I don't like this design because the type itself is different affecting all the code that uses it...

**Comment by matthieu-nesme** [comment]
A solution could be to replace the concerned Data with new Data **with different names** using SVector.

The backward compatibility could be ensure by having a specific "parse" function, looking for the old data names, and filling the new SVector by splitting at every spaces (the old way). W/o forgetting the deprecated message.

A similar process has been done in RigidMapping (Data 'rigidIndexPerPoint' replacing 'repartition').

**Comment by damienmarchal** [comment]
The approach proposed by matthieu sounds ok to me. 
I strongly support the "W/o forgetting the deprecated message".

**Comment by matthieu-nesme** [comment]
Fixed in a99443a98fed8052fe1159487d73639a6a6e2624.

I finally changed DataFileNameVector that is now a SVector<string>, so be aware its string serialization changed.

I made this choice because only OglShader is using DataFileNameVector in sofa-public, so the consequences of this change are small, and at least future usage of DataFileNameVector will be ok.
Of course if your private code is using DataFileNameVector, you have to update it.
