### ISSUE TITLE
[Modules] bitwise logical operation (&)

### ISSUE THREAD

**Issue by maddin200** [sofa-framework/sofa#2108]
[D:/Data/OpenSource/sofa-master/modules/SofaGuiQt/libQGLViewer-2.7.1/QGLViewer/quaternion.cpp line 115

Code: 
if ((m[0][0] > m[1][1]) & (m[0][0] > m[2][2])) { // <- bitwise probably &&
      const qreal s = sqrt(1.0 + m[0][0] - m[1][1] - m[2][2]) * 2.0;

**Comment by guparan** [comment]
I'm pretty sure it's not a bug and it's located in an external dependency, thus not related to SOFA.
EDIT: it may be a bug actually, could you have a look @fredroy ?

**Comment by guparan** [comment]
As discussed with @fredroy QGLViewer is no longer maintained so the only way to know if this is a bug or not is to test it ourselves.
Feel free to reopen if you think this is a bug and have a way to reproduce it.
