### ISSUE TITLE
[SofaTest] sofa errors do not generate gtest errors

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#211]
Some unit tests are generating sofa errors w/o generating gtest errors (e.g. SofaBoundaryCondition_test).

To detect such problems, I had added a msg handler that was returning a gtest error at each sofa error.
It was not good enough because some tests can generate sofa errors on purpose.
But the new implementation defeat the main purpose.

**Comment by damienmarchal** [comment]
Hi Mathieu,

I see what you mean. 
 
The new implementation allows you to select precisely how gtest suceed or fail according to the messages emitted by a component by using either the MessageAsTestFailure or/and ExpectMessage RAII. 

To update the old tests with *a minimal amount of effort* to restore the behavior you described. 
I think in each test setup we can simply add something like 
```cpp
MessageAsTestFailure raii_warning(Message::Warning) ;
MessageAsTestFailure raii_error(Message::Error) ;
```
I can devote some time to do that.

**Comment by damienmarchal** [comment]
Actually on 83 files are using Sofa_test half of them are alreay using the new system so the effort will not be that big. 

EDIT: a proposition to restore that is in PR #213

**Comment by damienmarchal** [comment]
Merge.
