### ISSUE TITLE
Duplicate code in BroadPhase_test.h

### ISSUE THREAD

**Issue by alxbilger** [sofa-framework/sofa#2117]
Code is duplicated in:

- SofaKernel/modules/SofaBaseCollision/SofaBaseCollision_test/BroadPhase_test.h
- applications/plugins/SofaTest/BroadPhase_test.h

**Comment by fredroy** [comment]
The issue by itself is not fixed but SofaTest is deprecated so I doubt this issue will be fixed any day.
