### ISSUE TITLE
Regroup implementation of BaseMatrix and BaseVector (SparseMatrix, EigenWrappers, etc.) inside a single module

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#2150]
BaseMatrix
- BlocFullMatrix
- BlockDiagonalMatrix
- BTDMatrix
- CompressedRowSparseMatrix
- DiagonalMatrix
- FullMatrix
- RotationMatrix
- SparseMatrix
- TNewMatMatrix

BaseVector
- EigenVector
- EigenVectorWrapper
- FullVector
- NewMatVector

**Comment by alxbilger** [comment]
@fredroy What remains to be done?

**Comment by fredroy** [comment]
@alxbilger you are right, only NewMat* things are not moved/done but this will deprecated ASAP (as well as the LULinearSolver which is only usable with those matrices)

**Comment by fredroy** [comment]
Last things to do are described here: #2483 
But Sofa.Algebra should be finished by now.

I suppose this will be modified with the new planned EigenMatrix from Caribou but not the point of this issue.
