### ISSUE TITLE
ProjectToLineConstraint and topological changes

### ISSUE THREAD

**Issue by fredroy** [sofa-framework/sofa#2242]
ProjectToLineConstraint is crashing when trying to do projectResponse() because its jacobian matrix member is not synchronized with its respective mechanical object (especially its size).
This problem was raised from the scene: ProjectToLineConstraint_RemovingMeshTest.scn
And it seems to be detectable only in Debug mode as the CI does not complain very often.

One first fix was trying to call a method to update the Jacobian while catching the fact that a topology change event was triggered, but various problems arrived with the fact that the MechanicalObject data is not connected to the "Data" update mechanism. (a first draft on how to change this behavior here  #1489  but stalled) 

A second fix (less subtle) checks every time if the jacobian size is correct wrt to the mechanical object : #2241
Less desirable because it will check at each call but fix the problem for now.

I let this issue to remember to trigger the jacobian update when detecting a topological change, once the topological change mechanism is finished.

**Comment by damienmarchal** [comment]
This issue seems to have been solved by @fredroy.
If it is not the case please reopen.
