### ISSUE TITLE
QDocBrowser crashes when runSofa exits

### ISSUE THREAD

**Issue by alxbilger** [sofa-framework/sofa#2315]
Tested on Windows, VS 16 2019, Qt 5.15.2

**Comment by epernod** [comment]
In my case, the QtWidget doesn't close when closing runSofa. Moreover the widget doesn't have a close button. So the only way to close the execution is to kill the process. 

Windows VS 16 2019, Qt 5.10.1

**Comment by epernod** [comment]
Is this issue still relevant? @alxbilger
