### ISSUE TITLE
Update Git Bash on Windows VMs

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#234]
"If you have a version older than 2.7.4, it is highly advisable to upgrade."
See https://github.com/git-for-windows/git/wiki/FAQ

Plus: it adds **unzip** which is needed for Windows dependency pack.

**Comment by guparan** [comment]
Update is done.
Good to know: Git Bash added itself at the end of PATH, **after** MinGW.

This brings me a question: why MinGW? We don't need all these duplicated tools (sh.exe, bash.exe, ...). @damienmarchal, did you install MinGW only for Ninja?

**Comment by damienmarchal** [comment]
@guparan it was there and "already in the path" I simply dropped ninja in it :)

**Comment by guparan** [comment]
As expected, MinGW in path before Git Bash raised a problem: unzip was not found.
It is located in `/usr/bin` relatively to Git Bash but not reachable because of MinGW.
