### ISSUE TITLE
[SofaQtQuick] [QtViewer] - OpenGL Core Profile context  

### ISSUE THREAD

**Issue by marques-bruno** [sofa-framework/sofa#238]
runSofa's QtViewer and the new SofaQtQuick interface create a "Core Profile" OpenGL context on Linux, with Intel GPUs, with the following error messages:

> QtViewer: OpenGL 4.5 (Core Profile) Mesa 17.0.2 context created.
> Error: GL_ARB_multitexture not supported
> ########## SIG 11 - SIGSEGV: segfault ##########

A core profile context isn't likely to support the ARB_multitexture extension because that extension is specific to the fixed-function pipeline. (For more information: [Check this thread on OpenGL's forum](https://www.opengl.org/discussion_boards/showthread.php/199472-GL_ARB_multitexture-not-supported?p=1286582)

Bug reproduced on 3 laptops with intel graphics, with Intel's drivers installed, on Ubuntu 16.04 and Arch linux.
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
HI lagarkane,

Thank you for the bug report. I will give it a look.

**Comment by guparan** [comment]
@marques-bruno, @damienmarchal, any progress on this issue?

**Comment by damienmarchal** [comment]
OUps sorry I totally forgot that as I spend more time on github than on the qtsofaquick gitlab.

**Comment by marques-bruno** [comment]
Could someone test on windows / mac with an intel graphics? @guparan maybe?
I need to find out if I have to fix that as a cross-platform or linux-specific issue.

**Comment by marques-bruno** [comment]
Fixed by #526
