### ISSUE TITLE
Compilation issue with CGAL on 21.06

### ISSUE THREAD

**Issue by TanguyNav** [sofa-framework/sofa#2480]
Using the 21.06 sources from SOFA on Ubuntu, I faced a compilation issue with the CGAL plugin. It appears that the issue is fixed in #2246. Should it be backported in 21.06 release branch @guparan ?

**Comment by epernod** [comment]
Hi,
the 21.06 release will not be upgraded anymore. Please use the 22.12 or the incoming 23.06. CGalPlugin now have soem github action to make sure it compiles using SOFA release/master branches
