### ISSUE TITLE
List small tasks/issues

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#27]
The idea is to create issues for small stuff/cleans/bugfixes that could be done by anyone.

**Comment by damienmarchal** [comment]
Hi guparan,

When I see this kind of small issues I tend to write //TODO(dmarchal) in the sofa source code. Maybe we should all do that and report all the TODO found from time to time in the issues tracking system.

DM.

**Comment by epernod** [comment]
I agree and you should find a way to put a "rate"/"priority". I have never worked with github issue manager.. maybe it is already possible.

**Comment by damienmarchal** [comment]
You can add a thumb-up (with the Add your reaction icon... in the header of the message)) then sort by reactions in the issues listing.

**Comment by guparan** [comment]
TODOs in source code are nice. Please be sure to make them Doxygen readable. 
See https://www.stack.nl/~dimitri/doxygen/manual/commands.html

I think we could also create issues here with a special common label like "help wanted" (already existing). 
More, we could have a whole series of "difficulty" labels: difficulty 0, difficulty 1, difficulty 2, ...

**Comment by damienmarchal** [comment]
Thanks for the doxygen link.

**Comment by damienmarchal** [comment]
This discussion seems deprecated with the SofaNG activity. So I close it.
