### ISSUE TITLE
Handling deprecation in SOFA

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#272]
Hi all,

When crawling into sofa code I often found line like that:
```cpp
/** A class that define topological Data general methods
      DEPRECATED
*/
template < class T = void* >
class BaseTopologyData : public sofa::core::objectmodel::Data <T>
{...}
```
This kind of comment is problematic as I have no idea what to do and it rise a lot of questions.

Each time we want to deprecate something we should make efforts on documenting that properly to manage the changes. 
To me this means at least answering the following questions in the source code & in a github Issue: 
- why the code is deprecated and what is the replacement approach
- when it have been deprecated
- when can we remove deprecated class
- who is supposed to do the update...and if it is not the person that deprecate the code what is the implemented approach to notified calling code they are using deprecated code and that they have to be fixed. A good idea is to use dmsg_deprecated()  messages for that. 
- how are we supposed to update thing that make use of the deprecated function
 

______________________________________________________

Suggested labels:

**Comment by bcarrez** [comment]
I totally agree with Damien.
Depending on the case, the comment should at least include the following informations:
- date of deprecation
- replacement method pointers

Furthermore, the deprecated method could issue a message on the console, to warn against its use.
In extreme cases, after a reasonable time delay, the method should not work anymore, just issue an error message with the previous informations.

But as it is currently done in this example, nothing goes against its undiscontinued use in new pieces of code.

**Comment by damienmarchal** [comment]
No contribution to this discussion since months. So I close it.
