### ISSUE TITLE
Recursive ReadAccessor yields erroneous behaviour.

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#2761]
### Problem

**Description**
This bug was first reported by @AlbanOdot in https://github.com/jnbrunet/caribou/issues/104

We have a component that opens a `ReadAccessor<Data<VecCoord>>` on a Mechanical Object position vector during the **init** stage of the scene. In the same callstack, the component will open another `ReadAccessor<Data<VecCoord>>` on the same MO position vector. The following small object can be taken as an example:

_Edit: I found out that the recursive ReadAccessor isn't even needed to reproduce the issue, simply having a component opening during init a read accessor on its own data, which parent is the MO vector, is enough._

```c++
class TestComponent : public BaseObject {
public:
    SOFA_CLASS(TestComponent, BaseObject);
    using DataTypes = sofa::defaulttype::Vec3Types;
    using VecCoord = DataTypes::VecCoord;
    TestComponent() : d_position(initData(&d_position, "position", "Position vector")){}

    void init() override {
        Inherit1::init();
        auto positions = ReadAccessor<Data<VecCoord>>(d_position);
        test(positions.size());
    }
    void test(const sofa::Size & nb_of_nodes) {
        auto positions = ReadAccessor<Data<VecCoord>>(d_position);
        if (positions.size() != nb_of_nodes) {
            std::cout << "Just something to make sure the compiler compile this" << std::endl;
        }
    }
private:
    Data<VecCoord> d_position;
};
```

The consequence will be that the MO object position vector won't be updated later on during time steps. However, if the same scene is run with a GUI, the problem disappears. The following scene can be taken as an example where a random displacement is imposed on a node before the time step, and the node position is printed afterwards.

```python
class Controller(Sofa.Core.Controller):
    def __init__(self, MO):
        super().__init__()
        self.MO = MO

    def onAnimateBeginEvent(self, _):
        print("\n\nonAnimateBeginEvent")
        random_disp = np.random.normal(0, 1e-2, self.MO.position.value.shape)
        self.MO.position.value = self.MO.rest_position.value + random_disp
        print(f"{random_disp[0]=}")
        print(f"{self.MO.position.value[0]=}")

    def onAnimateEndEvent(self, _):
        print("onAnimateEndEvent")
        print(f"{self.MO.position.value[0]=}")


def createScene(root):
    root.addObject('RequiredPlugin', pluginName=['BugPosition'])
    root.addObject("MechanicalObject", name="MO", template="Vec3d", position=[1, 0, 0])
    root.addObject("TestComponent", position="@MO.position")
    root.addObject(Controller(root.MO))
```

**Steps to reproduce**
I've put everything needed to reproduce the issue here https://github.com/jnbrunet/BugPosition

Hence, the following steps can be taken (the SOFA installation path must be changed, and SofaPython3 plugin must be installed alongside SOFA):
```bash
export SOFA_ROOT=/opt/sofa
export PYTHONPATH=$PYTHONPATH:$SOFA_ROOT/plugins/SofaPython3/lib/python3/site-packages
```
Then, compile and launch the scene
```bash
git clone git@github.com:jnbrunet/BugPosition.git
cmake -DCMAKE_PREFIX_PATH=$SOFA_ROOT/lib/cmake -S BugPosition -B BugPosition/build -DCMAKE_BUILD_TYPE=Release
cmake --build BugPosition/build
python3 BugPosition/scene.py
```
which should produce the erroneous results (random displacement isn't taken into account).
```
(...)
onAnimateBeginEvent
random_disp[0]=array([-0.01092411, -0.00742505, -0.01442109])
self.MO.position.value[0]=array([1., 0., 0.])
onAnimateEndEvent
self.MO.position.value[0]=array([1., 0., 0.])
 ```

**Expected behavior**
The correct behaviour can be obtained using the GUI. In the previous example, simply adding the `gui` parameter to the scene will do the trick:

```commandline
python3 BugPosition/scene.py gui
(...)
onAnimateBeginEvent
random_disp[0]=array([-0.00746889, -0.01065234,  0.00446683])
self.MO.position.value[0]=array([ 0.99253111, -0.01065234,  0.00446683])
onAnimateEndEvent
self.MO.position.value[0]=array([ 0.99253111, -0.01065234,  0.00446683])
```

---------------------------------------------

### Environment

**Context**

- System: MacOS 12.1 but reproductible on Ubuntu 20.04
- Version of SOFA: master branch ([888a159f4c](https://github.com/sofa-framework/sofa/tree/888a159f4c))
- State: install directory

---------------------------------------------

Thank you for your report.

**Comment by jnbrunet** [comment]
Small update: seems like the recursive thing is not even the source of the problem. The following object is enough to cause the issue:

```c++
class TestComponent : public BaseObject {
public:
    SOFA_CLASS(TestComponent, BaseObject);
    using DataTypes = sofa::defaulttype::Vec3Types;
    using VecCoord = DataTypes::VecCoord;
    TestComponent() : d_position(initData(&d_position, "position", "Position vector")){}

    void init() override {
        Inherit1::init();
        ReadAccessor<Data<VecCoord>> a(d_position);
    }
private:
    Data<VecCoord> d_position;
};
```
with 
```python
root.addObject("MechanicalObject", name="MO", template="Vec3d", position=[1, 0, 0])
root.addObject("TestComponent", position="@MO.position")
```

**Comment by fredroy** [comment]
Hello @jnbrunet thank you for your expansive report !

I have tried to port your py3 example into C++, and I got the correct behavior.

```c++
class MyTestController : public sofa::core::objectmodel::BaseObject
{
public:
    SOFA_CLASS(MyTestController, BaseObject);
    using DataTypes = sofa::defaulttype::Vec3Types;
    core::behavior::MechanicalState<DataTypes>* m_mo;

    //SingleLink<MyTestController, core::behavior::MechanicalState<DataTypes>, BaseLink::FLAG_STOREPATH | BaseLink::FLAG_STRONGLINK> l_mstate;

    MyTestController(core::behavior::MechanicalState<DataTypes>* mo = nullptr)
        //    : l_mstate(initLink("MO", "Mechanical state to reorder"))
        :m_mo(mo)
    {
        this->f_listening.setValue(true);
    }

    void handleEvent(sofa::core::objectmodel::Event* event)
    {
        using namespace sofa::helper;
        using namespace sofa::core::objectmodel;
        using namespace sofa::core::behavior;

        if (simulation::AnimateBeginEvent::checkEventType(event))
        {
            std::cout << "onAnimateBeginEvent" << std::endl;
            auto moValue = sofa::helper::getWriteAccessor(*m_mo->write(core::VecCoordId::position()));
            std::cout << moValue[0] << std::endl;
            moValue[0] = moValue[0] + type::Vec3{ 1.0, 2.0, 3.0 };
            std::cout << moValue[0] << std::endl;
        }

        if (simulation::AnimateEndEvent::checkEventType(event))
        {
            std::cout << "onAnimateEndEvent" << std::endl;
            auto moValue = sofa::helper::getReadAccessor(*m_mo->read(core::VecCoordId::position()));
            std::cout << moValue[0] << std::endl;
        }
    }

};
```

```c++
    Simulation::SPtr simu = createSimulation("DAG");
    Node::SPtr root = createRootNode(simu, "root");
    sofa::component::initSofaBaseUtils();

    simpleapi::createObject(root, "RequiredPlugin", { { "pluginName", "SofaBaseMechanics"} });
    simpleapi::createObject(root, "RequiredPlugin", { { "pluginName", "PluginExample"} });

    auto meca = createObject(root, "MechanicalObject", {
                     {"name", "MO"},
                     {"template", "Vec3d"},
                     {"position", "1 0 0"}
    });
    
    using MechaObjVec3 = sofa::component::container::MechanicalObject<defaulttype::Vec3Types>;
    MechaObjVec3* mecaobj = dynamic_cast<MechaObjVec3*>(meca.get());
    
    auto tcom = createObject(root, "MyTestComponent", {
                 {"position", "@MO.position"},
    });

    //auto cont = createObject(root, "MyTestController", {
    //         {"MO", "@MO"},
    //    }); 

    sofa::component::behaviormodel::MyTestController::SPtr cont = sofa::core::objectmodel::New<sofa::component::behaviormodel::MyTestController>(mecaobj);
    root->addObject(cont);
    
    sofa::simulation::getSimulation()->init(root.get());

    sofa::simulation::getSimulation()->animate(root.get(), 0.01);
```

```
 onAnimateBeginEvent
1 0 0
2 2 3
onAnimateEndEvent
2 2 3
```

(the controller just adding {1,2,3} to the mecha.position[0])


With both cases (mechanical object given to the controller as pointer directly or as a link), I got the correct behavior.
So it would seem that the problem is somewhere in SofaPython3 (bindings?)

**Comment by jnbrunet** [comment]
> So it would seem that the problem is somewhere in SofaPython3 (bindings?)

Indeed, looks like it ! Should we move this issue to SP3 repo?

**Comment by fredroy** [comment]
After further investigations:
 - running the python script from runSofa (instead from a py env), **works** (array is modified)
 - printing pointers shows that the pointer is changing when doing `self.MO.position.value = self.MO.rest_position.value + random_disp` when running from a py env, whereas not with runSofa
 - using my c++ controller but in the python scene, works ( `root.addObject("MyTestController", name="testcontroller", MO="@MO")` )
 - weirdest of all, if **adding** my c++ controller in the scene, along the python Controller one.... the python Controller then works 😵
```
    root.addObject("MyTestController", name="testcontroller", MO="@MO")
    root.addObject(Controller(root.MO))
```

So my speculation is that the custom python Controller stuff has some memory/link/data problem, but I dont know what...

**Comment by AlbanOdot** [comment]
In addition to @fredroy answer. It is the getWriteAccessor that 'fixes' the bug. The following function makes the code run without error.

``` 
void handleEvent(sofa::core::objectmodel::Event* event)
{
   const auto& moValue = sofa::helper::getWriteAccessor(*l_mstate.get()->write(sofa::core::VecCoordId::position()));
}
```

The Component has to be added to the scene **BEFORE the Sofa.Core.Controller is initialized** in order to deal with the events before the Sofa.Core.Controller does.

**Comment by damienmarchal** [comment]
https://github.com/sofa-framework/SofaPython3/pull/243
