### ISSUE TITLE
empty() method in fixed_array returns false

### ISSUE THREAD

**Issue by marques-bruno** [sofa-framework/sofa#277]
Hi,

I noticed that the empty() method in fixed_array always returns false, and is not overloaded by any of its subclasses, such as Matrices and Vectors.
I doubt that it's a feature, but it seems wierd to me that no one ever noticed.. so I flagged this issue as discussion for now :) 

@sofa-framework/consortium 
______________________________________________________

Suggested labels:

**Comment by fjourdes** [comment]
I believe the explanation for this `empty()` method is to be able to have `fixed_array` fit into any generic code which expects its template parameter to have container concepts, and that can work both with resizeable ( like `std::vector` ) and fixed size containers ( like `fixed_array` ).

A (kind of not useful ) method like that could work both with `vectors` and `fixed_array` implementation : 

```lang=cpp
template < class Container > 
typename const Container::value_type& 
returnFirstValueOrDefaultValue( const Container& container, const Container::value_type& defaultValue)
{
  if(container.empty() )
  {
    return defaultValue;
  }
  return *container.begin();
}
```

I just wonder if there are some implementations that benefit from that fact. 

Also note that the implementation of `std::array` in c++11 also has an `empty()` method [http://fr.cppreference.com/w/cpp/container/array](http://fr.cppreference.com/w/cpp/container/array) , with the notable exception compared to `fixed_array` is that `std::array` supports "degenerate" compile time fixed size arrays of size zero.

**Comment by marques-bruno** [comment]
But then for the sake of clarity at least, wouldn't it still make sense to implement this function by checking whether or not the values are the same as the defaults?
One can argue that a zero-ed matrix doesn't mean an "empty" matrix, and some could consider the identity matrix to be an empty matrix maybe in some cases, but at least, with a little comment, it would make it clearer.
Otherwise a msg_warning in this method would be helpful for whoever tries to call it without knowing that it has a "return false" behavior?

**Comment by fjourdes** [comment]
If you want to hide methods in a inherited class because they don't really make sense in its API, private inheritance is usually the way to go. Inherited methods can still be made public in the derived class by selecting them with the `using` directive. 

See [https://stackoverflow.com/a/675451](https://stackoverflow.com/a/675451)

**Comment by fjourdes** [comment]
However in the particular case your are mentionning ( ie compile time fixed size matrices ) nothing really strikes me as a "bad behavior" or undocumented behavior of some sort that needs to be amended in the current design.

Then again in the standard which has `std::array` for compile time fixed size array, the `empty()` method always return false unless your array is degenerated ( ie it cannot contain anything at all ).

**Comment by maxime-tournier** [comment]
@lagarkane except `empty` for vectors has pretty well-defined semantics as a shortcut for `size() == 0` like in the STL.

**Comment by marques-bruno** [comment]
Ok, Thanks for the clarification :) I close the issue
