### ISSUE TITLE
No Mat::inverted() function in defaulttype::Mat

### ISSUE THREAD

**Issue by marques-bruno** [sofa-framework/sofa#280]
After spending half a day struggling on a little piece of code, I finally found out that my call to invertMatrix didn't return the correct result:

In Sofa, calling 
```
Matrix3 M;
M.invert(M);

``` 
returns a grotesque bullshit, because "from" and "dest" are the same, and no copy is made, so values are changed and read at the same time.
I understand that in terms of performance, avoiding a useless copy is good, but there is no warning message of any kind, not even as a comment over the function.

For the `transpose()` function, there is an additional` transposed()` method that directly stores the transposed matrix in its initial data structure.
I suggest that an `inverted() `method be added to `Mat`, and a little comment above the `invertMatrix()` function be added to warn about this specific problem.

What do you think?
If it sounds good to you, I can take care of it. If you see a better way of warning the user about this behavior, or consider that removing entirely the issue by making a temporary copy of the value is not aberrant, that would be even better I guess

@hugtalbot @guparan 

______________________________________________________

Suggested labels:

**Comment by fjourdes** [comment]
Indeed. I am not a big fan of having a member function `invert`
Anyway, to fix the problem you can test that the address of reference passed as an argument is different from the address of the object instance. e.g.

```lang=cpp

template< std::size_t L, std::size_t C, typename real = double >
bool Mat<L,C,real>::invert(const Mat<L,C,real>& m )
{
  if(&m == this )
  {
     // do something clever to handle "in-place" invert
  }
  else
  {
     invertMatrix(*this, m );
  }
}
```

NB: it is an usual pattern when for instance you must overload the assignment operator of a class (because it has to manage some heap allocated memory for example ), and therefore handle the special case when you self assign.

**Comment by fjourdes** [comment]
So bottomline is, there are no warnings to fire, just handle properly the case where the parameter passed to the `invert` method is the object itself, which is not handled at the moment as you pointed out.

I believe the same problem exists with the `transpose` class member method.

**Comment by IPeterlik** [comment]
Yeah, handling the self-assignment is probably the best way out; keeping the performance and addressing the issue. Shall you go ahead, Bruno?

**Comment by maxime-tournier** [comment]
FWIW, I think we all should be using Eigen for doing this anyways ;-)

**Comment by marques-bruno** [comment]
Thanks for your input =)
Will PR a fix in the upcoming days for both invert and transpose
