### ISSUE TITLE
Plugins: loading & components introspection

### ISSUE THREAD

**Issue by fredroy** [sofa-framework/sofa#281]
[ Follow-up of #253 ]

To sum up the ideas:
 - create a manifest file @ plugin post-build
 - create a configuration system where applications can find the list of plugins to load automatically at startup
 - inform the user that if you want to use `<ComponentAFromPluginXXX>`, you need to add the line `<RequiredPlugin pluginName="PluginXXX" >`

(Everything started from:
 - hard loading of SofaPython in runSofa
 - in the future we want to remove ImageBMP/ImagePNG/ImageQt and use ImageCImg from the plugin CimgPlugin, and avoid to always add the RequiredPlugin line in each scene.)

The Manifest file will be useful when the components in the Sofa trunk will be dispatched in several plugins (planned in the far future)

**Comment by fredroy** [comment]
Proposal for the 2nd point (autoload a list of plugins from a config file)
1) CMake generates a plugin_list.conf.default file containing all selected Plugins ( names & version ).
E.g
SofaPython 0.1
CImgPlugin 0.1
image 0.2
BeamAdapter 0.1
CGALPlugin 0.1
(version info is optional)
I would say that the location of this file should be where all plugins are. ( i.e bin/ )

2) runSofa application:
instead of the hard-coded line loading SofaPython:
if (exists(plugin_list.conf))
       PluginManager::readFromIniFile(plugin_list.conf); // custom
else if (exists(plugin_list.conf.default))
       PluginManager::readFromIniFile(plugin_list.conf.default); // default

--> if the user did not create its own custom plugin_list.conf file containing only the plugins he wants to load automatically, then runSofa will load automatically all compiled plugins. (and if the default file is not found then no loading)
We do not use the version information for now but could be interesting in the future maybe ?

**Comment by damienmarchal** [comment]
Hi Fred,

On my side I have implemented the "warning" behavior. It is in PR #306 and I would appreciate your feedback (and if you have time, some support to fix the linking problem on windows).

**Comment by damienmarchal** [comment]
One of the point remaining is to build an object that map the component to plugins. 

The easy path is probably to make an application that loads all thall the plugins, load them and dump the infos in a file (json, xml, whatever). 

Then having a queriable object to get that info through an API.

**Comment by fredroy** [comment]
Issue solved with #301 and #306
