### ISSUE TITLE
 ERROR: duplicate triangle 19 20 6 in tetra 37

### ISSUE THREAD

**Issue by TumVink** [sofa-framework/sofa#2854]
Heyy

When I was using the Meshgeneration.scn to generate vtu file from .obj file, I encountered such errors:

![image](https://user-images.githubusercontent.com/72047791/162650833-b850b497-8640-4533-94f5-55dd9ed06736.png)

So how could I fix such issues?

Jingsong

**Comment by epernod** [comment]
If this is still a bug, please open a GitHub discussion with an example and the mesh to reproduce the bug
