### ISSUE TITLE
"Save screenshot" button make the GUI freeze after second hit

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#30]
To reproduce the bug:
- Launch sofa with any scene
- Hit the "Save screenshot" button and save the image somewhere
- Hit again the "Save screenshot"
- The gui should now be frozen

Sofa version is 178a7b1 (current master branch)
Linked against Qt 5.5.1 and boost 1.58.0
Compiled with clang 3.8.0
Ubuntu 16.04.1 LTS

**Comment by fredroy** [comment]
On Windows10/VS2015/Qt5.6 and MacOSX 10.11/clang/Qt5.5, the gui does not freeze. 
[with QGLViewer or QtViewer]
Is it possible to try with an other version of Qt ?

**Comment by jnbrunet** [comment]
I've tried with Qt5.2 and got the same error.

The error seems to come from RealGUI::screenshot() after the first screenshot is taken 

RealGUI.cpp:2148

```
    if ( filename != "" )
    {
        std::ostringstream ofilename;
        const char* begin = filename.toStdString().c_str();
        const char* end = strrchr ( begin,'_' );
        if ( !end )
            end = begin + filename.length();
        ofilename << std::string ( begin, end );
        ofilename << "_";
        getViewer()->setPrefix ( ofilename.str() );

        getViewer()->screenshot ( filename.toStdString() );
    }
```

In my case, the pointer _begin_  is initialized to an empty string. The weird thing is that if I put a breakpoint there with gdb, and manually call  _filename.toStdString().c_str()_, the _begin_ pointer will be populated correctly, as if there was a latent initialization.

Next, even if this works with your computer, _ofilename_ will be populated with the complete path of the file until the last occurrence of "_" is found. _getViewer()->setPrefix_ will then be called and prepend the _getScreenshotDirectoryPath_ to the already full path _ofilename_. 

BaseViewer.cpp:128

```
void BaseViewer::setPrefix(const std::string& prefix)
{
    const std::string fullPrefix = sofa::gui::BaseGUI::getScreenshotDirectoryPath() + "/" + prefix;
   (...)
}
```

See pull request https://github.com/sofa-framework/sofa/pull/31
