### ISSUE TITLE
[SofaGui] No GUI available on Ubuntu

### ISSUE THREAD

**Issue by dessteph** [sofa-framework/sofa#3006]
Since the 05/06, there are no GUI available on Ubuntu on the master branch.

**Comment by epernod** [comment]
What do you mean by available? no option on the cmake? not compiling?

**Comment by dessteph** [comment]
The Cmake option is set on true, it compile but when I run runSofa there is no gui available. Even when I consult the help with runSofa -h there is only the batch in the list of GUI.

**Comment by alxbilger** [comment]
@dessteph thanks for reporting the issue. It should be fixed in #3007. Can you try it and confirm the issue is fixed?
