### ISSUE TITLE
UV coordinates ignored by MeshOBJLoader

### ISSUE THREAD

**Issue by ScheiklP** [sofa-framework/sofa#3012]
### Problem
When passing an `.obj` file and texture `.png` to `OglModel`, they are correctly loaded and mapped.

```
visual_node.addObject(
        "OglModel",
        filename="mesh.obj",
        texturename="texture.png",
)
```
![image](https://user-images.githubusercontent.com/29635054/172361782-e1d53384-a84e-4d83-bed1-8fe5eb5d3aa5.png)

For the  MeshOBJLoader the UV coordinates are ignored.

```

loader = visual_node.addObject(
        "MeshOBJLoader",
        filename="mesh.obj",
        handleSeams=True,
)

visual_node.addObject(
        "OglModel",
        texcoords=loader.texcoords,
        texturename="texture.png",
)
```

![image](https://user-images.githubusercontent.com/29635054/172362364-2533e6fc-7226-452e-88f0-a6bdcf93dbf7.png)

---------------------------------------------

### Environment

**Context**

- System: Ubuntu 20.04
- Version of SOFA: master branch at commit 06899d457fb46db82313fe3f136664d7b22e7bc9
- State: Install directory

**Comment by ScheiklP** [comment]
Did some more digging.

In the code above `texcoords=loader.texcoords,` is not valid, because the loader did not actually read any data yet.

![image](https://user-images.githubusercontent.com/29635054/172406384-33d329ef-0de6-42a3-8624-287b87d443e9.png)

Changing it to
```
loader = visual_node.addObject(
        "MeshOBJLoader",
        filename="mesh.obj",
        handleSeams=True,
)

loader.init()

visual_node.addObject(
        "OglModel",
        texcoords=loader.texcoords,
        texturename="texture.png",
)
```

fixed the issue. Is this still valid behavior?

**Comment by epernod** [comment]
yes you need to use handleSeams = true if you want to use the vertices buffer + texcoords.
But this mode can't be used as input of a mechanical mesh because some vertices are duplicated for the UV coordinates.

**Comment by ScheiklP** [comment]
`handleSeams = True` was set in both cases. The main problem was that the loader was not initialized.
It worked best (also without the init) when passing the LinkPath, and not the data container itself.
So I guess this is more a thing of having example code than a bug.

Where would be the best place to document an example like this?
```
loader = visual_node.addObject(
        "MeshOBJLoader",
        filename="mesh.obj",
)

visual_node.addObject(
        "OglModel",
        texcoords=loader.texcoords.getLinkPath(),
        texturename="texture.png",
)
```

**Comment by damienmarchal** [comment]
Hi @ScheiklP 

Thanks for reporting and you are right in your conclusion (it is because that the object does not need to be initialize when created in python). 

Actually getting rid of the need to init the data is a long standing issue: see https://github.com/sofa-framework/SofaPython3/pull/173 

This PR is probably the place to have future discussion on that topic and I close the issue,
