### ISSUE TITLE
Difference between OS/compilers

### ISSUE THREAD

**Issue by alxbilger** [sofa-framework/sofa#3036]
### Problem

**Description**
The same simulation scene can lead to significative differences when executed on different OS.

**Steps to reproduce**
The regression tests currently show that `examples/Components/forcefield/MeshSpringForceField.scn` is such a scene.
The PR https://github.com/sofa-framework/sofa/pull/3035 introduces another scene.

**Expected behavior**
The same result on all OS

**Comment by damienmarchal** [comment]
Interesting. 

My first investigation trials would be to check the scene in debug vs release (be sure that --fastmath is not activated).

**Comment by alxbilger** [comment]
Another difference: https://github.com/sofa-framework/SofaPython3/actions/runs/2488100337

**Comment by alxbilger** [comment]
This PR, which introduces unit tests, shows a difference is coming from the call of the METIS library: https://github.com/sofa-framework/sofa/pull/3050

**Comment by alxbilger** [comment]
Fixed by https://github.com/sofa-framework/sofa/pull/3687
