### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [sofa-framework/sofa#3136]
/Sofa/GUI/Qt/src/sofa/gui/qt/ModifyObject.cpp line 504
Code:
  if(dialogFlags_.REINIT_FLAG)
        {
            if (node)
            {
                // if the selected object is a node
                if (node) // <-- identical
                {

**Comment by damienmarchal** [comment]
Hi @maddin200 

Thanks for reporting, 
This has been fixed in PR #3713
