### ISSUE TITLE
Precompiled version

### ISSUE THREAD

**Issue by MaksymTymkovych** [sofa-framework/sofa#3169]
### Problem

Hi all,
First of all i want to thank you for your work, and yours great framework!
Thanks!

**Description**
I want to try run latest version of Sofa-framework, but I got problem with different gcc verions.

**Steps to reproduce**
First of all I had installed SOFA by using your precompiled binary file:
`./SOFA_v21.12.00_Linux.run`
after that I run:
`./runSofa-21.12.00`
And I got the errors
```
./runSofa-21.12.00 
./runSofa-21.12.00: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/maxim/SOFA/v21.12.00/bin/../lib/libSofa.Helper.so.21.12.00)
./runSofa-21.12.00: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/maxim/SOFA/v21.12.00/bin/../lib/libSofa.SimulationCore.so.21.12.00)
./runSofa-21.12.00: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/maxim/SOFA/v21.12.00/bin/../plugins/SofaValidation/lib/../../../lib/libSofa.Type.so.21.12.00)
./runSofa-21.12.00: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/maxim/SOFA/v21.12.00/bin/../lib/../lib/libSofaBaseMechanics.so.21.12.00)
./runSofa-21.12.00: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/maxim/SOFA/v21.12.00/bin/../lib/../plugins/SofaUserInteraction/lib/../../../plugins/SofaBoundaryCondition/lib/libSofaBoundaryCondition.so.21.12.00)
./runSofa-21.12.00: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/maxim/SOFA/v21.12.00/bin/../lib/../plugins/SofaUserInteraction/lib/../../../plugins/SofaDeformable/lib/libSofaDeformable.so.21.12.00)
```
**Expected behavior**
I think It should work, at least.

---------------------------------------------

### Environment

**Context**

- System: "Ubuntu 18.04"
- Version of SOFA: SOFA_v21.12.00

**Command called**

```
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

What you think, probably is better solution to build the Sofa-framework from source (github)? Or there exist some approach to use prexompiled binaries on the Ubuntu 18.04.

**Comment by fredroy** [comment]
The binaries from the sofa-framework.org website were compiled using Ubuntu20.04, which got a glibc update.
Unfortunately, it is not possible to run executables compiled with a glibc version newer than the one on your system...

**Comment by MaksymTymkovych** [comment]
Ok, thanks.
