### ISSUE TITLE
[UX] Default values for DataFileName

### ISSUE THREAD

**Issue by marques-bruno** [sofa-framework/sofa#321]
It seems like there is no way with the current implementation to set a default value to a DataFileName field. In fact, it is not possible at all to modify a value passed through a DataFileName. Neither setValue() nor read() etc. work, as the operator=() is made private...
Did I miss anything? otherwise, especially if DataFileName should be the official way of providing a file path to a component, this should be fixed.

@damienmarchal, since it is about code cleaning and User Experience, I believe you might have nice inputs..? :)
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
@lagarkane I see no reason why it shouldn't be modifiable.  And yes it should be the official way of providing file names in component. 
But in my master' branch there is a setValue that is public...did I miss something ?

**Comment by marques-bruno** [comment]
@damienmarchal  yes, setValue is public, but if you look at the implementation of setValue():
```

    void setValue(const std::string& v)
    {
        *beginEdit()=v;
        endEdit();
    }
```
it uses the operator=() that is private (and not implemented..):
```
private:
    DataFileName(const Inherit& d);
    DataFileName& operator=(const DataFileName&);

```

**Comment by damienmarchal** [comment]
I'm totally lost... isn't the = operator supposed to work between string ?

**Comment by marques-bruno** [comment]
Shoot, my bad...
My apologies... Stupid me, I declared my DataFileName as follows:
`Data<DataFileName>` without realizing that DataFileName was already a Data... -__-
Issue closed...
Sorry @damienmarchal for making you loose your time
