### ISSUE TITLE
How to use methods proposed in paper "Preserving Topology and Elasticity for Embedded Deformable Models"

### ISSUE THREAD

**Issue by Chenw831X** [sofa-framework/sofa#3252]
Hi, I read this paper **"Preserving Topology and Elasticity for Embedded Deformable Models"**, and it's an excellent and interesting work! I want to create my own simulation scene using methods proposed in this paper, but I have no idea how to make it using **sofa**.

Any instruction or suggestion will be appreciated! Thanks a lot!

**Comment by epernod** [comment]
Hi @Chenw831X ,

thank you for your interest in SOFA.
As this is more a discussion topic to get help and advises, rather than an issue. I will convert this issue into discussion.
