### ISSUE TITLE
Cannot turn off print statements from GenericConstraintSolver

### ISSUE THREAD

**Issue by ScheiklP** [sofa-framework/sofa#3255]
Hi,
Since v22.06, I cannot turn of the print outputs from `GenericConstraintSolver`.

`root_node.addObject("GenericConstraintSolver", verbose=False, printLog=False)`

![image](https://user-images.githubusercontent.com/29635054/187037091-9c754406-1adb-4e18-a270-78748924dbe8.png)

Cheers,
Paul

---------------------------------------------

Environment
Context

System: Ubuntu 20.04
Version of SOFA: master branch at commit v22.06.00
State: "Install directory"

**Comment by alxbilger** [comment]
This has been fixed in a recent pull request: https://github.com/sofa-framework/sofa/pull/3232
Thanks for reporting anyway.

Alex
