### ISSUE TITLE
DiagonalMass.cpp

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#34]
The specialization of the 

``` cpp
void DiagonalMass<Rigid2fTypes, Rigid2fMass>::init() 
void DiagonalMass<Rigid3fTypes, Rigid3fMass>::init() 
```

is totally different to the one for:  

``` cpp
void DiagonalMass<Rigid2dTypes, Rigid2dMass>::init() 
void DiagonalMass<Rigid3dTypes, Rigid3dMass>::init() 
```

This seems weird to me. Can someone confirm this is a bug (and that probably the Rigid2f/3f should be the same as Rigid2d and Rigid3d).

**Comment by matthieu-nesme** [comment]
Good eyes!
It also seems obvious to me that the float version should be the same as the double version.

**Comment by damienmarchal** [comment]
I created a branch to fix that in: https://github.com/SofaDefrost/sofa/tree/fixing-issue34

(Using branches & pull-request for such trivial things...seems overkill and a waste of time...)
