### ISSUE TITLE
Error when creating catheter simulation: [WireRestShape(catheterRestShape)] EdgeSetController has no binding EdgeSetTopologyModifier.

### ISSUE THREAD

**Issue by beamadapter** [sofa-framework/sofa#3463]
[ERROR]   [WireRestShape(catheterRestShape)] EdgeSetController has no binding EdgeSetTopologyModifier.
import sys
import Sofa

def createScene(rootNode):

    rootNode.addObject('RequiredPlugin', pluginName='BeamAdapter SofaMeshCollision SofaBoundaryCondition SofaConstraint SofaMiscCollision SofaDeformable SofaGeneralLinearSolver SofaImplicitOdeSolver')
    rootNode.addObject('VisualStyle', displayFlags='hideVisualModels hideBehaviorModels showCollisionModels hideMappings showInteractionForceFields')

    rootNode.addObject('FreeMotionAnimationLoop')
    rootNode.addObject('DefaultVisualManagerLoop')

    rootNode.addObject('LCPConstraintSolver', mu='0.1', tolerance='1e-10', maxIt='1000', build_lcp='false')
    rootNode.addObject('DefaultPipeline', draw='0', depth='6', verbose='1')
    rootNode.addObject('BruteForceBroadPhase', name='N2')
    rootNode.addObject('BVHNarrowPhase')
    rootNode.addObject('LocalMinDistance', contactDistance='1', alarmDistance='5', name='localmindistance', angleCone='0.02')
    rootNode.addObject('DefaultContactManager', name='Response', response='FrictionContact')

    topoLines_cath = rootNode.addChild('EdgeTopology')
    topoLines_cath.addObject('WireRestShape',name='catheterRestShape',
                             straightLength=600.0, length=1000.0,
                             numEdges=200, youngModulus=12000,
                             spireDiameter=1000, numEdgesCollis=[50, 10],
                             printLog=True, template='Rigid3d', spireHeight=0.0,
                             densityOfBeams=[30, 10], youngModulusExtremity=12000)
    topoLines_cath.addObject('EdgeSetTopologyContainer', name='meshLinesCath')
    topoLines_cath.addObject('EdgeSetGeometryAlgorithms', name='GeomAlgo', template='Rigid3d')
    topoLines_cath.addObject('MechanicalObject', template='Rigid3d', name='dofTopo')

    CatheterMechanics = rootNode.addChild('CatheterModel')
    CatheterMechanics.addObject('EulerImplicitSolver', rayleighStiffness=0.2, rayleighMass=0.1, printLog='false')
    CatheterMechanics.addObject('BTDLinearSolver',verification=False, subpartSolve=False, verbose=False)
    CatheterMechanics.addObject('RegularGridTopology', name='MeshLines',nx=60, ny=1, nz=1,
                                    xmax=1.0, xmin=0.0, ymin=0, ymax=0, zmax=1, zmin=1,
                                    p0=[0,0,0])
    CatheterMechanics.addObject('MechanicalObject', showIndices=False, name='DOFs', template='Rigid3d', ry=-90)
    CatheterMechanics.addObject('WireBeamInterpolation', name='InterpolCatheter', WireRestShape='@../EdgeTopology/catheterRestShape',radius='1',printLog='0')
    CatheterMechanics.addObject('AdaptiveBeamForceFieldAndMass',name='CatheterForceField',massDensity=0.00000102, interpolation='@InterpolCatheter')
    CatheterMechanics.addObject('InterventionalRadiologyController', name='DeployController', template='Rigid3d', instruments='InterpolCatheter',
                               startingPos=[0, 0, 0, 0, 0, 0, 1], xtip=[0, 0, 0], printLog=True,
                               rotationInstrument=[0, 0, 0], step=5., speed=5.,
                               listening=True, controlledInstrument=0)
    CatheterMechanics.addObject('LinearSolverConstraintCorrection',wire_optimization='true', printLog=False)
    CatheterMechanics.addObject('FixedConstraint', indices=0, name='FixedConstraint')
    CatheterMechanics.addObject('RestShapeSpringsForceField', points='@DeployController.indexFirstNode', angularStiffness=1e8, stiffness=1e8)

    VisuCatheter = rootNode.addChild('VisuCatheter')
    VisuCatheter.activated = True
    VisuCatheter.addObject('MechanicalObject', name='Quads')
    VisuCatheter.addObject('QuadSetTopologyContainer', name='ContainerGuide')
    VisuCatheter.addObject('QuadSetTopologyModifier', name='Modifier')
    VisuCatheter.addObject('QuadSetGeometryAlgorithms', name='GeomAlgo', template='Vec3d')
    VisuCatheter.addObject('Edge2QuadTopologicalMapping', radius='1', listening='true',
                        input='@../../topoLines_guide/meshLinesGuide',
                        nbPointsOnEachCircle='10', flipNormals='true', output='@ContainerGuide')
    VisuCatheter.addObject('AdaptiveBeamMapping', interpolation='@../InterpolGuide',
                        name='visuMapGuide', output='@Quads', isMechanical=False,
                        input='@../DOFs', useCurvAbs=True, printLog=False)

    # Ogl model
    VisuOgl = VisuCatheter.addChild('VisuOgl')
    VisuOgl.addObject('OglModel', color=[0.2, 0.2, 0.8], quads='@../ContainerCatheter.quads',
                      material='texture Ambient 1 0.2 0.2 0.2 0.0 Diffuse 1 1.0 1.0 1.0 1.0 Specular 1 1.0 1.0 1.0 1.0 Emissive 0 0.15 0.05 0.05 0.0 Shininess 1 20',
                      name='Visual')
    VisuOgl.addObject('IdentityMapping', input='@../Quads', output='@Visual')

    CathterCollis = CathterMechanics.addChild('CollisionModel')
    CathterCollis.activated = True
    CathterCollis.addObject('EdgeSetTopologyContainer', name='collisEdgeSet')
    CathterCollis.addObject('EdgeSetTopologyModifier', name='colliseEdgeModifier')
    CathterCollis.addObject('MechanicalObject', name='CollisionDOFs')
    CathterCollis.addObject('MultiAdaptiveBeamMapping',controller='../DeployController', useCurvAbs=True, printLog=False, name='collisMap')
    CathterCollis.addObject('LineCollisionModel', proximity=0.0)
    CathterCollis.addObject('PointCollisionModel', proximity=0.0)

    Carotids = rootNode.addChild('Carotids')
    Carotids.addObject('MeshSTLLoader', filename='../mesh/carotids.stl', flipNormals=False, triangulate=True,
                       name='meshLoader', rotation=[10.0, 0.0, -90.0])
    Carotids.addObject('MeshTopology', position='@meshLoader.position', triangles='@meshLoader.triangles')
    Carotids.addObject('MechanicalObject', position=[0, 0, 400], scale=3, name='DOFs1', ry=90)
    Carotids.addObject('TriangleCollisionModel', moving=False, simulated=False)
    Carotids.addObject('LineCollisionModel', moving=False, simulated=False)

    return rootNode
I used python to edit a simulation similar to a catheter in the carotid artery. I'm imitating the example provided in the sofa file. But I don't know why the error occurred, and I don't know how to solve it. I hope you can give me some help. This is the sofa BeamAdapter plug-in used.

**Comment by epernod** [comment]
Hi,

you need to add a `EdgeSetTopologyModifier` in your first object:
`topoLines_cath.addObject('EdgeSetTopologyModifier', name='meshLinesModif')`

Hope it helps.

**Comment by beamadapter** [comment]
[ERROR]&nbsp; &nbsp;[SofaPython3::SceneLoader] Unable to completely load the scene from file 'D:/DefrostSofaBundle_win64_python3.8_v22.06.00-beta4/DefrostSofaBundle_win64_python3.8_v22.06.00-beta4/plugins/BeamAdapter/examples/python3/Cochlear-Implant-Insertion/cathter.py'.
Python exception:
&nbsp; ValueError: Object type Edge2QuadTopologicalMapping<&gt; was not created
The object is in the factory but cannot be created.
Requested template : None
Used template&nbsp; &nbsp; &nbsp; : None
Reason(s)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Data attribute 'input' does not point to a valid mesh topology and none can be found in the parent node context.



Thank you for your help. I found the following errors after following your reply. How to solve this problem?




方得始终
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sofa-framework/sofa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 晚上7:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sofa-framework/sofa] [ERROR]   [WireRestShape(catheterRestShape)] EdgeSetController has no binding EdgeSetTopologyModifier. (Issue #3463)





 
Hi,
 
you need to add a EdgeSetTopologyModifier in your first object:
 topoLines_cath.addObject('EdgeSetTopologyModifier', name='meshLinesModif')
 
Hope it helps.

**Comment by epernod** [comment]
Hi,
You need to add the correct plugin into your scene requiredPlugin. It should be `SofaTopologyMapping` in your version.

I'm moving this issue to the Discussions section as it is related to your scene creation rather than a bug inside SOFA.
Thanks
