### ISSUE TITLE
Triggering a doUpdate of MeshROI

### ISSUE THREAD

**Issue by ScheiklP** [sofa-framework/sofa#3484]
### Problem
Hi,
in some previous version of SOFA, the method `doUpdate` of `MeshROI` was triggered in each simulation step, if the `doUpdate` value was set to true. 
Now, it is just a check inside the method, but the method itself is never called.

Should the method be registered to some event, or should it actually be called manually on demand?

https://github.com/sofa-framework/sofa/blob/18149f4407fd78359eead7b64ae23470687c40c4/Sofa/Component/Engine/Select/src/sofa/component/engine/select/MeshROI.inl#L582-L587

**EDIT**: The data inside the component is updated, but it does not show in the GUI.

---------------------------------------------

### Environment

**Context**

- System: Ubuntu 20.04
- Version of SOFA: d152f8374bf6faf65d2e385afa78dbd57f365f6c
- State: Install directory

Cheers,
Paul

**Comment by epernod** [comment]
Hi @ScheiklP ,

`MeshROI` is a SOFA engine, it inherite from ... `DataEngine` I think (without looking at the code).
The design of the the engine is to call the method `DataEngine::update` when one of the output Data is accessed and if any of the input Data is dirty. Meaning we need to recompute the output from new input value. 

But as several mechanisms are required for this design, the `update `method is calling the method `doUpdate `which has to be implemented in each specific engine in middle of other code.

So it is normal you don't see call of doUpdate inside the MeshRoi

DO you have a scenario which doesn't work as expected?

**Comment by ScheiklP** [comment]
Hi @epernod ,
thanks a lot for the explanation! :)

The scenario that does not work is opening the ROI component from the scene graph in the GUI and looking at the data.
This does not seem to be updated.
![image](https://user-images.githubusercontent.com/29635054/201955573-bca66cef-f619-4c08-a15a-c18aa0a9ec80.png)
Moving the object through mouse interaction into and out of the ROI, these values do not change.
The values are only updated when I close the window of the component and opening it again.

So I guess I'll close this issue.
Is there another related issue? :D

**Comment by epernod** [comment]
You mean, you open the tab, simulate and there is no update?
Could you check if clicking on the refresh button on the bottom update the values?
I guess the gui is not calling "continuous update" on the Data to avoid slowing down the simulation but I'm not expert of the DataWidget.

**Comment by ScheiklP** [comment]
No, clicking refresh does not update the values. :(

**Comment by epernod** [comment]
ok, this can be the issue to create 👍
