### ISSUE TITLE
[OBJExporter] obj file not written

### ISSUE THREAD

**Issue by thomas-lemaire** [sofa-framework/sofa#355]
When the parent folder of the output file of an OBJExporter does not exist : 
- a message is output like this one: [INFO]    [OBJExporter(ObjExporter)] Exporting OBJ as: /path/to/my/mesh.obj
- no obj file is written

I think the user either expect : 

1. either to have an error/warning message instead of a success message
2. or to have the parent folder(s) created properly (and silently or not) and the mesh file written as expected

I am in favor of 2.

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
This bug has been fixed in a merged PR (with additional extra feature)
