### ISSUE TITLE
Advanced timer usage at initialization

### ISSUE THREAD

**Issue by chrijopa** [sofa-framework/sofa#357]
While there are some pretty nice ideas going on considering the improvement the output of the advanced timer #348, to my knowledge (please correct me if I am wrong!), the component has some shortcomings:
1. The timing output does not show up when using the batch gui, i.e. when specifying -g batch over the command line. Together with @ggrosshenny, we already took care of this in the work related to #348, a pull request will follow soon.
2. The advanced timer can not be used at the initialization, i.e. in methods like init and I believe as well the backward init

To resolve the second point, I propose to change the variable computationTimeSampling to an integer (see Main.cpp, line 182). When set at 
- a negative integer c, it does output the timings of the initialization, but at every time step -c
- 0, it only outputs the timings of the initialization
- a positive integer c, it does not output the timings of the initialization and at every time step c

Thus the persons having used the timer before will not have any impact on their potential scripts using the SOFA output.
An implementation already has been started with @ggrosshenny, but it is not clear where an insertion has the less impact and yields the results. @ggrosshenny, could you precise that please?

Has there been any work considering this point?
Do you have any propositions how to address it?

Label propositions: discussion, bug

**Comment by damienmarchal** [comment]
Hi,

The reference PR was merged. Do we need to close this issue or is there any news ?
