### ISSUE TITLE
"Dynamic" Data in sofa (mainly OptionsGroup)

### ISSUE THREAD

**Issue by marques-bruno** [sofa-framework/sofa#363]
Hi!

OptionsGroup in Sofa are currently created in 2 steps:

- in ctor: every option are created, from strings, usually by calling "setNames()". A default value is set, usually to 0 by calling setSelectedItem(0)
- during parsing of the scene file: user value is taken into account

This is working great, except in one case:
What if my OptionsGroup is supposed to contain a list of values retrieved from another sofa::Data (let's say a vector of strings..)?
- In the Ctor, the string data is not yet initialized, so setNames cannot be called
- in parse() I don't know about the other data so I cannot retrieve the list of values. This also means that when calling setSelectedItem with the value passed in the scene file, I will get an error message as the entry does not exist 
- at init(), my list of values is set, so I can finally call setNames, but I'll lose my default user value from the scene file.

To fix this, I modified the OptionsGroup class to store the user value in readFromString(), and added a public method: setSelectedItemToDefault() that calls setSelectedItem() with that stored user value.

This solved the issue, but only for OptionsGroup (any sofa::Data that relies on another data for its initialization will have the problem), and it's maybe not in the cleanest way..
Some would argue that listing the values to feed the OptionsGroup with is a task for SofaPython, before calling CreateObject, but I'd like to have this feature even when using XML scene files.

Do you have suggestions on how to solve this problem in a better way, and for all data? Do you think my way is clean enough to be PRed in SOFA?

@damienmarchal, maybe you have good ideas on the topic ? 

Looking forward to your feedback,
- Bruno Marques
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Hi @lagarkane 

Maybe I have not clearly understood what you want to achieve but what about something like the following:
```cpp
void YourObject::parse( BaseObjectDescription* arg )
{
    /// Initialize the possible list of options by parsing "manually" the list:
    if (arg->getAttribute("availableOptions")){
           /// vectorFromString is not existing...but this is just to give you the idea 
           OptionGroup options(vectorFromString( arg->getAttribute("availableOptions") ))) ; 
           d_myOptionGroup.setValue(options) ; 

           /// don't remove the availableOptions so that it is parsed as "usual" 
           /// and it will be correctly saved.  
    }       
    
    /// Call the normal parse function. 
    Inherit1::parse(arg) ; 
}

**Comment by marques-bruno** [comment]
Hi @damienmarchal ,
Thanks for your reply!
Indeed, that is what I would like to do... I didn't know I could call parse() per component, instead of per data.. The solution is much simpler than I thought.. sorry!
I close the topic
