### ISSUE TITLE
[Core] Link initialization fail

### ISSUE THREAD

**Issue by EulalieCoevoet** [sofa-framework/sofa#3705]
### Problem

PR #3665 seems to break the initialization of some links.  

**Description**
I have an home made mapping which inherits from `Multi2Mapping`. With the changes of #3665, the initialization of `input2` fails, `Multi2Mapping::getFromModels2()` returns an empty list. Reverting the PR fixes the issue.

**Comment by fredroy** [comment]
Hello,
would it be possible to provide a simple test?
It seems there is no unit/scene/regression tests which are using Multi2Mapping and its `input2` apparently.
And by just looking at the code, I cannot see why `input2` would be impacted by #3665 as there is no `validator` for input2 😅
It would be much easier to track down the bug, thanks !

**Comment by EulalieCoevoet** [comment]
There is the example DeformableOnRigidFrameMapping.scn, but it seems to work fine, and its pretty similar to my scene (I mean the mapping graph). So for the moment it's just my component and my scene 😩 but I'll continue to dig.

**Comment by EulalieCoevoet** [comment]
Well, it seems to work fine after a clean rebuild... I'll keep in mind to always try that before opening an issue 🤓
