### ISSUE TITLE
No idea how to build it - send help!

### ISSUE THREAD

**Issue by benny2581** [sofa-framework/sofa#3716]
### Discussed in https://github.com/sofa-framework/sofa/discussions/3715

<div type='discussions-op-text'>

<sup>Originally posted by **benny2581** March 11, 2023</sup>
Hey,
I am pretty new to sofa and all of coding, programming and basically computer stuff. I have no idea what to do to build sofa on my computer. I downloaded and installed all the programms they recommended on the website right here https://www.sofa-framework.org/community/doc/getting-started/build/windows/
But I honestly don't know what I'm supposed to do next. How to use CMake to add all that stuff? I constantly get errors saying something is invalid.
I looked at the video where a guy shows it all but the main problem appears at the very beginning - he has some folders in his path called src or sofabuild32 but on my device they are nowhere to be found so this is where I get confused. 

If anyone could write a step-by-step what to do, or even let me talk to them about how to end my computer suffering, I would be very grateful.

Have a wonderful day, 
B.</div>

**Comment by alxbilger** [comment]
Duplicate of https://github.com/sofa-framework/sofa/discussions/3715
