### ISSUE TITLE
ArticulatedSystemPlugin Index out of bound

### ISSUE THREAD

**Issue by alxbilger** [sofa-framework/sofa#3750]
https://github.com/sofa-framework/sofa/blob/18149f4407fd78359eead7b64ae23470687c40c4/applications/plugins/ArticulatedSystemPlugin/src/ArticulatedSystemPlugin/ArticulatedSystemMapping.inl#L527
I encountered a situation where `indexT` can be out of `xto`'s bounds.

Can it be checked at init? If detected, what to do?

**Comment by fredroy** [comment]
Fixed by https://github.com/sofa-framework/sofa/pull/3751
