### ISSUE TITLE
Error at component creation not reported in the log

### ISSUE THREAD

**Issue by thomas-lemaire** [sofa-framework/sofa#378]
Let's try this small scene
```xml
<?xml version="1.0" ?>
<Node name="root" >
    <MergeVectors template="tartempion" name="merge"  nbInputs="2"/>
</Node>
```
No error is triggered on the console, and obviously "tartempion" is not a valid template
However in debug, I can follow up to the line where a message is sent to object->serr in ObjectFactory.cpp around line 174
if (!usertemplatename.empty() && object->getTemplateName() != userresolved) {
            object->serr << "template <" << usertemplatename << "> incorrect, used <"
                         << object->getTemplateName() + ">";
}

maybe s.t. related to logging not initialized in the object at that time ?

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Hi Thomas,

Intriging... thanks for reporting.

**Comment by ErwanDouaille** [comment]
We tested this scene in debug and release, and  both displays a warning message.
The warning message is consistent because it use a default template (aka double)

Here is a log on debug :
`   [WARNING] [MergeVectors(merge)] Template <tartempion> incorrect, used <double>
`

**Comment by damienmarchal** [comment]
Thanks erwan for the test.
The warning is also there in release.

Maybe the problem is specific to Thomas application. 
Each application has to define and set-up its way to handle the messages. Have a look in runSofa on how it is one.

**Comment by damienmarchal** [comment]
Can we close this one ?

**Comment by thomas-lemaire** [comment]
So then it is specific to runSofa2, not a good point either !
