### ISSUE TITLE
[SOFACUDA]: Generating Error

### ISSUE THREAD

**Issue by MingshanHe** [sofa-framework/sofa#3808]
### Problem

**Description**
I configure the sofa-cuda successfully, but when I generating it I get the error like this.

"CUDA_STANDARD is set to invalid value '17'"

**Steps to reproduce**
< LIST THE STEPS TO REPRODUCE YOUR PROBLEM HERE >

**Expected behavior**
< DESCRIBE WHAT YOU THINK SHOULD HAVE HAPPEN INSTEAD >

---------------------------------------------

### Environment

**Context**

- System: < "Ubuntu 20.04">
- CUDA 12.0
- Version of SOFA: stable branch
- State: < Build>

**Command called**

```txt

< COPY-PASTE YOUR COMMAND HERE >

```

**Env vars**

```bash
python -c "exec( \"import os, sys\nprint('#################')\nprint('--- sys.version ---')\nprint(sys.version)\nprint('--- PATH ---')\ntry:\n  print(os.environ['PATH'])\nexcept Exception:\n  pass\nprint('--- SOFA_ROOT ---')\ntry:\n  print(os.environ['SOFA_ROOT'])\nexcept Exception:\n  pass\nprint('--- PYTHONPATH ---')\ntry:\n  print(os.environ['PYTHONPATH'])\nexcept Exception:\n  pass\nprint('--- sys.path ---')\ntry:\n   print(str(sys.path))\nexcept Exception:\n   pass\nprint('#################')\" )"
```

```txt

< COPY-PASTE HERE THE RESULT OF THE COMMAND ABOVE >

```

---------------------------------------------

### Logs

**Full output**

```txt

< COPY-PASTE YOUR OUTPUT HERE >

```

**Content of build_dir/CMakeCache.txt**

< DRAG AND DROP YOUR CMAKECACHE.TXT HERE >

---------------------------------------------

Thank you for your report.

**Comment by alxbilger** [comment]
According to the [documentation](https://cmake.org/cmake/help/latest/prop_tgt/CUDA_STANDARD.html), the value 17 is valid for `CUDA_STANDARD` starting cmake 3.8, but 3.18 to support any compiler. What's your version of cmake?

**Comment by MingshanHe** [comment]
> According to the [documentation](https://cmake.org/cmake/help/latest/prop_tgt/CUDA_STANDARD.html), the value 17 is valid for `CUDA_STANDARD` starting cmake 3.8, but 3.18 to support any compiler. What's your version of cmake?

my cmake version is 3.16 which is used in cmake-gui

**Comment by MingshanHe** [comment]
In terminal, I check the cmake version is 3.26 using "cmake --version". But I don't know why the cmake 3.16 is used by cmake-gui (I installed it with `sudo apt-get install cmake-gui` which is mentioned in sofa build website documentation)

**Comment by MingshanHe** [comment]
I solved this problem with remove the cmake which is installed with apt, and re-install it with source file.

Thanks for your information
