### ISSUE TITLE
FlowVR in SofaVolumetricData

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#40]
Does the files in sofa/modules/SofaVolumetricData/CMakeLists.txt really require FlowVR to compile?

**Comment by damienmarchal** [comment]
Hi Mathieu,

Thanks for the tick reporting ;). 

FlowVR is currently used in DistanceField.cpp to load .fmesh files. We can probably refine the dependency to FlowVR to allow DistanceField object to work but without the fmesh support.

This seems easy and I will try to do that.

Damien.

**Comment by damienmarchal** [comment]
The commit that fix that is 
910d498493f13ca0c670e7df32e99b8674e7c29d
in the defrost branch.

Cherry-picking it & test it is ready to go into master.

**Comment by damienmarchal** [comment]
Test OK. Pushed to master.
