### ISSUE TITLE
Python scripts execution in Sofa

### ISSUE THREAD

**Issue by sergeiNikolaev** [sofa-framework/sofa#400]
Hello. 
Does anyone knows how to run python tests in SOFA framework?

@hugtalbot 

Thank you for information.

______________________________________________________

Suggested labels:

**Comment by sergeiNikolaev** [comment]
@hugtalbot

**Comment by damienmarchal** [comment]
Hi @sergeiNikolaev 

I'm not sure what you want. 
There is actually several tests of python functionality in different plugins. 
SofaPython_test and SofaTest are good starting point. 

Now if you want to lauch automatically something like 'unittest' or 'coverage' I have no idea but this is a good question.

**Comment by sergeiNikolaev** [comment]
Hello @damienmarchal 

I tried to execute tests manually using python. And I got import errors like:
_Traceback (most recent call last):
  File "test_mass.py", line 8, in <module>
    from SofaTest.Macro import *
ImportError: No module named SofaTest.Macro_
or
_Traceback (most recent call last):
  File "test_MeshLoader.py", line 1, in <module>
    import SofaPython.MeshLoader
ImportError: No module named SofaPython.MeshLoader_

It seems I should attach some additional modules (plugins), but I don't know what exactly I should do.

**Comment by maxime-tournier** [comment]
Hi there,

You cannot load tests using the python binary because the sofa bindings are only available for the embedded interpreter. 

There are some python tests under SofaTest/python IIRC.

**Comment by sergeiNikolaev** [comment]
Ok.

Then my question is how I could load and use this embedded interpreter?
If, for example, I want to debug or to verify how some script works.

**Comment by maxime-tournier** [comment]
You can simply start a python sofa scene using the main sofa executable, either through `File/Open` or from the command line. 

A simple scene goes like this:

```python
def createScene(node):
    child = node.createChild('childname')
    object = child.createObject('MechanicalObject', name = 'mobject', size = 1)
```

Please see the docs for more details.

**Comment by sergeiNikolaev** [comment]
Do python tests work in similar way? Ok.
