### ISSUE TITLE
Wrong cmake directive for the SofaDefaultType target

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#401]
Inside the file defaulttype/CMakeLists.txt, the line
`target_include_directories(${PROJECT_NAME} PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>/../..")`
should be
`target_include_directories(${PROJECT_NAME} PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/../..>")`

This error makes IDE based on cmake bleed the symbol indexing since a relative path "../.." is wrongly added in the sofa's CMake installed filed:

```
$ grep -nr "INTERFACE.*\.\.\/\.\." build/install/lib/cmake
./SofaFramework/SofaFrameworkTargets.cmake:66:  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/../.."
```

If, for exemple, you create an external projet that depends on Sofa, and that this external project is placed inside ~/source/project, than any IDE based on cmake for symbol indexing such as CLion will try to parse ~/source/project/../.. which is the home directory. This will end up take a lot of resources just for symbol indexing of a small project.
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Thank you for reporting this kind of problem. And the explaination is very instructive.
