### ISSUE TITLE
Cutting through

### ISSUE THREAD

**Issue by vargabalint92** [sofa-framework/sofa#4071]
Hey,

I am very new in sofa, and I am looking for a simple solution for the following :) :
I would like to simulate the cutting through of a 2-d mesh (surface) with a sharp tool.
My goal is to use this simulation to test the cutting of a soft tissue with a robot.

For two reasons, I would not to use the cutting Plugin: I need it for a research project for which I do not have financial budget to buy the plugin (maybe in the future, I will). The second reason that I would like to keep the simulation very simple and operate with a low number of parameters.

My question is: which examples should I take a look at? Is there anybody, how implemented such a scenario (maybe also with SofaPython3)?

Thank you very much in advance!

**Comment by ScheiklP** [comment]
Hi @vargabalint92 ,
I actually implemented sereval cutting scenes with SofaPython3.
You can find them here: https://github.com/ScheiklP/sofa_env

Cheers,
Paul
