### ISSUE TITLE
Saving Scene file

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#41]
When saving scene file either in python and xml a lot of informations are added which ruins the initial file which make it very hard to read and manipulate. 

Fixing this would be great.

**Comment by damienmarchal** [comment]
There is a patch in the daccord repository on forge. 

Here are the  commit messages (which contains possible interaction with other sofa part):

```
[FIX]: Allow sofa to save in xml & pyscn the scene. This may break some scene. Once stabilized this may go to the main Sofa.

Several issues needed to be adresse to make this system work.

first (to try to minimize the amount of un-needed saved informations making the file unreadable) ):
   - all the Data<> are now non persistent by default.
   - a Data<> become persistent if:
           * it is loaded from a file or from a python script.
           * it is modified in the GUI

second (hacky stuff on top of old hack stuff):
   during the parsing of xml some component  "converts" XML attributes to other (and possibility none) dataField). As only the dataField can be saved...these attributes are "lost". 
  The solution was to stop doing with a minimal number of changes the Sofa behavior. 

third (quirck stuffs on pile of quirck stuffs):
   some important XML attributes are interpreted on the fly and have very specific meaning but there  is no associated data field. The solution was to add the corresponding datafield to allow them to be saved.
   This is the case for "src", "template", "name", "type" ....

Given the amount of changed on base classes logics...some scene may have problem to load or save. Please tell if this is the case.
```

The case that probably could cause some problem is the replacement of the 'src', 'template' with real data field.

**Comment by matthieu-nesme** [comment]
What is the "daccord repository"?

I would be happy to talk about saving a sofa scene (and to help making it work).

first: indeed that's critical and it would do most of the job.

second: most of the time these are other ways to describe existing Data (e.g. the Data 'translation' is a Vec3 , but the parse function is able to read scalars 'tx', 'ty' and 'tz'). In that case the Data "translation" is modified and should be saved. In Fact we could simply forbid parsing stuff that is not filling existing Data.

third:
'src'  is not a problem, it is simply a way to automatically link Data together, so if a Data is modified, it will be saved (the saved scene would not have the 'src' arguments, but all the explicit Data links).
'template' is not a problem, it is already working (you just have to always export the template name)
'name' is already a data.
what is 'type'?


I would add that saving a scene in the middle of a simulation could bring more problems:
- the states (pos,vel,rest_pos) of every *independent* dofs (only the mechanical objects at the roots of the mapping graph) should be exported.
- maybe others stuffs to find (external_forces of every dofs?)
- maybe Data links broken by a copy-on-write should be exported.

**Comment by damienmarchal** [comment]
Hi Mathieu,

Best wishes for this year. 

Daccord is an old repository on gforge storing a lot of experimental feature (UI & modelling) that are pending for integration in sofa. 

I fully agree with your suggestion for point first&second
for third:
  - what about adding a Data for template & src ? (I really would like to preserve as much as much as possible the original scene because) 
  - "type" I don't know but it handled specifically in (XML.cpp)

I started a new branch for this task so we can work and tests : 
https://github.com/SofaDefrost/sofa/tree/xmlsave

EDIT: I have updated this branch saving is now working (at least the caduceus scene). If some of you have time please give feedback.

**Comment by damienmarchal** [comment]
This work is not active on our side because saving is handled by the PSL side.
So I close the Issue.
