### ISSUE TITLE
STC#4 Coding Sprint: main issue

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#413]
Hi all,

For the next STC we are planning active coding sprint sessions to boost small tasks and have the pleasure to be working togther. 

Feel free to propose any task in the comments!

Current task list (last update 2017-09-29):
- Deprecation: https://github.com/sofa-framework/sofa/issues/426
- Pluginization + SceneCreator dependencies (must be done AFTER deprecation): https://github.com/sofa-framework/sofa/issues/427
- `issofa_*` merges: https://github.com/sofa-framework/sofa/issues/428
- Code cleaning
- Doc

TODO List before the sprint:
- [x] finish to add the set management into the CMakeLists.txt (Damien & Bruno Carrez)
- [x] make the list of component to deprecate (Fred, Stéphane, Guillaume)
- [x] create a simple example of deprecation with the WashingMachineForceField (Damien)
- [x] if needed make a list of "advices" we could add to the SceneChecker to warn user on how they can improve their scene (the StaticSolver thing) (Stéphane ?)
- ~~add an attribute to BaseObjects to attach component quality info ?~~

Feel free to add whatever I mis-understood or forgot. 
________________________________________
ping @sofa-framework/reviewers

**Comment by damienmarchal** [comment]
The details to know:
  - where (I vote for the 'salle du conseil'  :))
  - when (wednesday 4 ?)
  - who will attend to the coding sprint ? 

My dream list:
- SofaNG (pluginizing the modules)
- sofaqtquick (only if there is more than 2 QML expert)
- Sofa code cleaning (as usual) :) 
   - coding standard conformance
   - we want more tests (they are crucial for refactoring) !!!
   - remove & unify duplicated code (eg...how many fast marching algorithm do we need ?)
   - remove the not-needed includes. 
- Writing doc :)

**Comment by damienmarchal** [comment]
Citing Olivier Goury (@olivier-goury)
"A whole day of coding in SOFA? I can not say no, count me in."

**Comment by guparan** [comment]
You forgot to ask **what** and that's the main point of this issue.

- No worries about where, we handle it internally (you can use your Lillois powers to influence the choice though) ;-)
- When: tuesday 3 afternoon (setting up and starting) + wednesday 4 whole day (coding like beasts).
- Who: this may influence the tasks but doesn't avoid us to propose everything we want :-) For now I can say we should be around 20-30.

**Comment by damienmarchal** [comment]
@guparan it is out of the topic of this thread...but maybe we should also gather who is willing to make presentations of WIP or results to have an idea. 
For me I have good meat to show about:
- PSL
- SofaImplicitModelling (including superb & tricky optimization technique based on python & cython)

**Comment by damienmarchal** [comment]
To summary this morning discussion with @guparan, @fredroy, @bcarrez, @StephaneCotin, @bruno-marques , @ErwanDouaille ...let's prepare for the sprint.
 
There is a general envy from people that want to participate to put the efforts to make a lighter version of Sofa. 

To match this goal, we discussed a workflow this morning in connection with the branch 
https://github.com/SofaDefrost/sofa/tree/deprecating_components
and issue #346 

Concretely during the sprint we may prepare two kind of tasks:
- deprecating as much as component as possible
- stabilizing as much as component as possible 

To deprecate the components we need to make a list with the following information: 
- name, some info why to deprecate it bad/redundant/etc... and the string show to the user to explain what to do/replacement and so on.  

To stabilize components we need to integrate the work done in the SofaNG so I let @fredroy & @guparan say more about that.

**Comment by guparan** [comment]
Another task suggestion: go on with **`issofa_*` branch merges**.
I think at least half of these branches could be merged without big difficulties.
What do you guys think?

**Comment by damienmarchal** [comment]
As I found the fact of having contributions to sofa stick very depressing I agree with you Guillaume and this could be great if some guys want to devote a task for making progress on that.

**Comment by damienmarchal** [comment]
It is out of the topic of this issue but @guparan, @hugtalbot  is there any planning of the presentations you expect from people ? Do we have to make slides or this kind of things ?

**Comment by guparan** [comment]
I just created separated issues for our 3 main tasks: deprecation, pluginization and issofa branches. Please use the appropriate ones (not this one) for future discussions. If issues are also needed for cleaning and documentation tasks, feel free to create them.
This issue can still be used for new suggestions or remarks so I let it open.

**Comment by guparan** [comment]
A word about organization: 
- we will work by groups of 4
- we will use specific branches (ignored by the CI) on this repository for our commits + integration branches (built by the CI)
- I will create a team to handle permissions so please make sure everyone has a GitHub account

**Comment by guparan** [comment]
@damienmarchal, I move your comment here
__________________________________
To @guparan, @bcarrez, @fredroy we need to organize the merging process for efficient and smooth integration of the pending PRs.

My suggestion is to now merge in row allow the pr:fix that have the pr:fast-merge  ( #444 #443 #442 #436 #414 #422)

There is also #423 which is a fatty one for which I don't know if we have to do it now or after the integration of the coding spring pr. 

The planning I suggest is:
- integrate #444 #443 #442 #436 #414 #422  (so we have a version before deprecation)
- integrate the deprecation PR
- integrate the pluginization PRs 

Where to do #423 ?

**Comment by guparan** [comment]
@damienmarchal, splitting our sprint branch in 2 was not hard but like you I'd like to merge things correctly.
I agree with your proposal but I think we should also reopen a PR from https://github.com/SofaDefrost/sofa/commits/deprecating_components beheaded until 456d88343e210ce89d9f7436c290be92fe438313 to merge all sprint prerequisites first.
This way, the two PRs from our sprint will be very clear.
What do you think ? I am ready to do it ;-)

**Comment by damienmarchal** [comment]
Sounds great !

**Comment by guparan** [comment]
Done in #453
