### ISSUE TITLE
SofaPython3 plugins bug with Linux Binaries

### ISSUE THREAD

**Issue by pchaillo** [sofa-framework/sofa#4159]
### Problem

**Description**
I've just tried to install last SOFA version with binaries.

**Steps to reproduce**
Install SOFA with the .run files and add SofaPython3 plugin

**Expected behavior**
There is an error when I tried to add the plugin.

---------------------------------------------

### Environment

**Context**

- System: Ubuntu 22.04.1 LTS
- Version of SOFA: 23.06.00

### Logs

```txt

Plugin loading failed (/home/pchaillo/SOFA/v23.06.00/plugins/SofaPython3/lib/libSofaPython3.so): libpython3.8.so.1.0: cannot open shared object file: No such file or directory

```
**Content of build_dir/CMakeCache.txt**

< DRAG AND DROP YOUR CMAKECACHE.TXT HERE >

---------------------------------------------

Thank you for your report.

**Comment by alxbilger** [comment]
Make sure you have Python 3.8.
Overall, read carefully the documentation: https://sofapython3.readthedocs.io/en/latest/content/Installation.html

**Comment by pchaillo** [comment]
Thanks Alex, I've just forgot a line in the .bashrc file.

Now it works fine.
