### ISSUE TITLE
Help-list to make your code compile with a recent checkout from "master".

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#418]
_You made a recent checkout from master and your private plugins does not compile anymore._ 

This is an unconfortable situation and be sure a lot of effort are done to reduce the amount of time this is  happening. But whatever care we can take, this may and will happen.

Two probable cases:
- when breaking stuffs that shouldn't be there have been merged by mistake. Well, we apologize for this situation. To help, do not hesitate to participate in the reviewing of the PRs before they are merged into master to detect this situation.  
 
- when breaking change that are accepted on purpose. The reason is that there is a general consensus that Sofa is currently very "fat" and thus PRs trying to clean or make sofa lightweight to compile are positive contribution to Sofa. The drawback of that is that cleaning and modularizing Sofa have a strong impact on file/code organization and for sure is going to break external code. 

As this is going to happen I suggest in the following thread to report what he had to do to compile master when encountered a broken compilation. Anyone can contribute... 

Hope this will help. 

eg:
  - I had to add a lot of #include<fstream>  to avoid compilation problem with xxx
  - Component from #include<SofaVolumetricData> have moved and been renamed ! I had to update my 
    CMakeList.txt to add find_package(SofaImplicitField) or find_package(SofaDistanceGrid)

An html version of the this thread is at:
Website version: https://www.sofa-framework.org/community/doc/programming-with-sofa/start-coding/help-list/

To edit it checkout: https://github.com/sofa-framework/doc/blob/master/40_Programming_with_SOFA/10_Start_coding/70_Help_list.md

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Cool idea, I think this should even be a [doc page](https://github.com/sofa-framework/doc) that anyone could feed. Let's create it :-)

**Comment by guparan** [comment]
Aaaaand it's done! 
Check it out: https://github.com/sofa-framework/doc/blob/master/40_Programming_with_SOFA/10_Start_coding/70_Help_list.md

**Comment by damienmarchal** [comment]
Good Idea Guillaume.

**Comment by damienmarchal** [comment]
We are including the STC4 coding spring results into master. 
It is expected to be in a rather un-stable state due to the changed introduced to make sofa more modular. 

So please report the compilation & runtime issues you encountered.

**Comment by damienmarchal** [comment]
SceneCreator.
If you get a message saying:
```
create: component 'Euler Explicit' of type 'EulerSolver Object type EulerSolver<> creation failed  
```
Emitted by the simpleapi as in
```
source code loc: /home/sofa/jenkins_1/workspace/ubuntu_gcc-5.4_options/src/applications/plugins/SceneCreator/SimpleApi.cpp:83
```

This means that  the factory does not contains the object. This message appears because the implementation of SceneCreator is totally new and it is now based on the content of the ObjectFactory. The consequence is  that to create object the factory needs to be initialized properly (by loading the plugins/modules). 

PS: to get the emitting location you can start runSofa with the clang message formatter.

**Comment by damienmarchal** [comment]
If you have a message saying that the texture cannot be loaded. 
This is probably because now image loading (png/jpg) is now done by a single plugin called CImgPlugin.

So to load images you needs to compile CImgPlugin & load it.

**Comment by guparan** [comment]
@damienmarchal could you please use the Doc page I created instead? This issue is lost in the wild...
