### ISSUE TITLE
Can't compile Sofa on Visual studio 

### ISSUE THREAD

**Issue by Gabriele111** [sofa-framework/sofa#4246]
Hi everyone, 

i am trying to build sofa from source. I used cmake-gui and when i configure it gives me no errors, but i open Sofa.sln in VS 2022 it skips 3 compilations and so i can't find sofaRun to run the software. The 3 compilations are Examples, Documentations and INSTALL. 

I watched the video tutorial on sofa website and i noticed QGLViewer_DIR variable is not found in cmake-gui, i don't know if this could be a reason why. 

thak you for your help!

**Comment by fredroy** [comment]
Hello,

Could you post the logs of the build with VS2022 ?
