### ISSUE TITLE
STC#4 Coding Sprint: Deprecation

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#426]
The idea is to deprecate old/unused components of SOFA.

Reference doc:  https://docs.google.com/spreadsheets/d/1a4jrAeQo-OcvA8iWbAXoBxW6CNN9D1zGL4eNltA1sJ0/edit

CI: https://www.sofa-framework.org/dash/index.php?branch=origin%2Fdeprecating_components

See also an example of deprecation with the WashingMachineForceField (search for WashingMachineForceField in CMakeLists & SceneCheckAPIChanges to see)

EDIT: (I added notes about WashingMachineForceField)

**Comment by guparan** [comment]
This is a comment from @damienmarchal in #413 about deprecation task
__________________________________________
To summary this morning discussion with @guparan, @fredroy, @bcarrez, @StephaneCotin, @bruno-marques , @ErwanDouaille ...let's prepare for the sprint.
 
There is a general envy from people that want to participate to put the efforts to make a lighter version of Sofa. 

To match this goal, we discussed a workflow this morning in connection with the branch 
https://github.com/SofaDefrost/sofa/tree/deprecating_components
and issue #346 

Concretely during the sprint we may prepare two kind of tasks:
- deprecating as much as component as possible
- stabilizing as much as component as possible 

To deprecate the components we need to make a list with the following information: 
- name, some info why to deprecate it bad/redundant/etc... and the string show to the user to explain what to do/replacement and so on.  

To stabilize components we need to integrate the work done in the SofaNG so I let @fredroy & @guparan say more about that.

**Comment by damienmarchal** [comment]
To increase sofa readability also vote for removing SOFA_FLOAT () and SOFA_EXTERN_TEMPLATE (we are now c++11 so extern is supported so no need to disable them with conditional compilation)

**Comment by damienmarchal** [comment]
Why do FixPickedParticleButtonSetting is in SofaGraphSimulation ? It looks more related to SofaUserInteraction

**Comment by damienmarchal** [comment]
I wonder how de-activate a compilation option when we are in compiling Sofa with the "core" profile (Do we de-activate runSofa it makes sense as soon as some of the component it is using will be moved into deprecation.)

**Comment by bcarrez** [comment]
@damienmarchal you mean, delete cmake variables ? or something else ?

**Comment by damienmarchal** [comment]
@bcarrez I want the runSofa/qt part of the project to be disabled when in core profile.

**Comment by damienmarchal** [comment]
STC is over. 
@guparan & @bcarrez are in charge to have to split the deprecation_branch where we have worked into severals: 
(1) one that deprecate components
(2) one that pluguinize some modules. 

I assume we should have (1) done before starting to merge PR

**Comment by bcarrez** [comment]
I agree. I also have to modify the SOFA_BUILD_COMPONENTSET to change the levels from core/full/deprecated to core/light/standard/full where:
- core contains only the "glue" of sofa (simulation, framework, ...)
- light contains a restricted/basic set of components (to be defined)
- standard contains most sofa components and features
- full = standard + deprecated components/tests

Hopefully this will be done by the end of this week.

**Comment by StephaneCotin** [comment]
At the end of the STC yesterday we discussed "packaging" and "granularity" aspects of the different component sets. On the way back I remembered that we addressed this question a while back, and at the time I was proposing an approach "a la Python":
- create relatively small plugins organized by "theme" (i.e. ForceField, Mapping, Collision, etc.). This would be like a module in Python
-  group these plugins into packages through which you can access all modules or only selected ones
- in a scene file we could then include all modules from a package using <RequiredPackage packageName="..." /> or use the current <RequiredPlugin /> for specific modules

When it comes to the way files are organized it the different folders in the SOFA directory, I think most of us wanted to go back to a meaningful structure. I am proposing something like this:

- SOFA
    + Core
    + ForceFields
         + Supported
         + Unsupported
         + Deprecated
     + Mappings
         + Supported
         + Unsupported
         + Deprecated
     + ....

As a developper this would make it easier to quickly see what to use or not. From a user perspective, the packages and plugins would provide another organization, from a functional point of view.

Any thoughts and comments are welcome...

**Comment by damienmarchal** [comment]
To @guparan, @bcarrez, @fredroy we need to organize the merging process for efficient and smooth integration of the pending PRs.

My suggestion is to now merge in row allow the pr:fix that have the pr:fast-merge  ( #444 #443 #442 #436 #414 #422)

There is also #423 which is a fatty one for which I don't know if we have to do it now or after the integration of the coding spring pr. 

The planning I suggest is:
- integrate #444 #443 #442 #436 #414 #422  (so we have a version before deprecation)
- integrate the deprecation PR
- integrate the pluginization PRs 

Where to do #423 ?

**Comment by damienmarchal** [comment]
Here is our way of organizing a plugin at defrost:
```
MyPlugin/
     components/
           forcefield/
                MyForceFieldCompoent.cpp
                MyForceFieldCompoent.h
           mapping/
           visual/
     objects/
          MyClassThatIsNotAComponent.cpp
          MyClassThatIsNotAComponent.h
     deprecated/
     CMakeList.txt
```

And we mimick that into the namespaces
```cpp
namespace sofa::myplugin::components::forcefield::MyForceFieldComponent
```

Then we "export" that into sofa namespace to be consistent with the rest of sofa. 
```cpp
namespace sofa
{
   namespace components
   {
        using namespace sofa::myplugin::components
   }
}
```

I think this is very close to what Stephane is proposing (it is unclear to me what "un-supported" is)

**Comment by damienmarchal** [comment]
My contribution to the discussion:
- sofa
  - core (no more components are in the core except stuff like RequirePlugin and few others)
  - plugins (here are all the components)
     - sofastandard
         - the pluginized version of all the modules (but at first without reorganizing them) 
     - plugin1
     - plugin2
     - myplugin (organized as in my previous contribution)
     - ...
     - ...
     - 

To me this kind of first step can be make without breaking anything in sofa and with great benefit. 
Let me explaine: the include path can have SofaStandard so that external code using the "modules" (eg: #include<SofaMiscFem/TheFEMILike.h>) don't need to be updated and only adding something like find_package(SofaStandard) or more specifically find_package(SofaStandardMiscFem). 

The immediate benefit of that is:
- people that don't want all the stuff in SofaStandard can disable the plugin (and compile sofa in 1min). 
- people that want only the minimal set of good component  component in SofaStandard compile sofa with the componentset "light" (and compile sofa in 3 min)
- people that want the existing sofa with all the deprecated (but still working) compile it with the SofaStandard plugin and componentset "full" (and compile sofa in 30 min)


Of course doing this easy step shouldn't prevent us from further refactoring, people that likes the SofaStandard components can re-organize and clean things. But this can be done incrementally when ones have time to devote to that. 

DM.

**Comment by StephaneCotin** [comment]
Sounds good to me! Let's try that.

**Comment by guparan** [comment]
My two cents: if you are using core+plugins naming in SOFA, why not going for **core**+components instead of objects+components in plugins? 
Even if the name is not "core", just using **the same** in SOFA and plugins would be more consistent.

**Comment by damienmarchal** [comment]
@guparan in our plugins organization objects is there to hold c++ class that are not components while in general 'core' in sofa is for the base classes and infrastructure. Actually what we are putting in this objects directory is much closer in essence to what is actually in sofa/helper (ie utilitary classes).

But "objects" is not a very clear name after all and core is maybe not better but not worse so if you like it...let's use it ;)

**Comment by damienmarchal** [comment]
STC4 is over, this discussion is now to be continuated in SofaNG.
#247
