### ISSUE TITLE
Creating tests on Topological operations

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#43]
Hi,

several tests were already done for topological modifier, they are tested through scenes in examples/Components/Topology/TopologicalModifiers

They test: add/remove of topological elements
- Is sofaVerification still used? 
- I can easily rewrite those tests in c++ using the ::Sofa_test  api. Is it better? what is the politic between doing tests through scene or Sofa_test.

**Comment by thomas-lemaire** [comment]
The successor of sofaVerification is in SofaTest, look at 
plugins/SofaTest/SofaTest_test/Regression_test.h 

I like small test scene that also serve the purpose of being didactic examples, it also ensures that examples are up to date since they are being tested 

thomas 

----- Mail original -----

**Comment by guparan** [comment]
Are you still writing tests for Topological operations @epernod ? 
What is the status of this issue ?

**Comment by epernod** [comment]
It is in my todo list for the next 2 weeks, as Christmas gift ;)

**Comment by damienmarchal** [comment]
For small scenes I found very convenient to write the scene directly in the test...
This allow to iterate on each variation of scene elements (PointLight, DirectionalLight, SpotLight) (or templates (Vec3d, Vec3f, Rigid)) with just a simple loop and string concat. 

```cpp
void mytestThatShouldExistsForAllLights(std::string& lighttype){
std::stringstream scene ;
    scene << "<?xml version='1.0'?>                                                                            \n"
             "<Node 	name='Root' gravity='0 -9.81 0' time='0' animate='0' >               \n"
             "  <Node name='Level 1'>                                                                              \n"
             "   <MechanicalObject/>                                                                                 \n"
             "   <"<< lighttype << " name='light1'/>                                                            \n"
             "  </Node>                                                                                                      \n"
             "</Node>                                                                                                        \n" ;
Node::SPtr root = SceneLoaderXML::loadFromMemory ("testscene",
                                                      scene.str().c_str(),
                                                      scene.str().size()) ;

... the actual meat of the test....
}
```
For complex scene I think that using a template langage could be an option ...but needs more work.

**Comment by epernod** [comment]
started in #708
