### ISSUE TITLE
[CI] dashboard - view all branches

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#430]
Selecting 'ALL' for "Branch" does not work anymore, it always redirects to "origin/master".

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Hi @matthieu-nesme, I did introduce this bug. Will fix it ASAP.

**Comment by guparan** [comment]
It's fixed!

**Comment by matthieu-nesme** [comment]
merci Guillaume :)
