### ISSUE TITLE
Multithread Unit test falling

### ISSUE THREAD

**Issue by bakpaul** [sofa-framework/sofa#4323]
The unit test `ParallelImplementationsRegistry_test` is failing for CGLinearSolver, stating that it has no creator although it is clear that such a component has one.

**Comment by alxbilger** [comment]
Isn't it fixed by https://github.com/sofa-framework/sofa/pull/4307 ?

**Comment by fredroy** [comment]
> Isn't it fixed by #4307 ?

Actually this error started to appear with this PR #4307 apparently (it was not noticed while PR reviewing 🙊)

**Comment by alxbilger** [comment]
Does this test still fail? I have tested and cannot reproduce it. And I did not do anything to fix it.
