### ISSUE TITLE
sofa.helper compiler error(SOFA 22.12)

### ISSUE THREAD

**Issue by q1221sr** [sofa-framework/sofa#4329]
### Problem

**Description**
When i build sofa 22.12 in window10, i faced a issue in sofa.helper
(cmake configure and generate success, default settings, no change option after download)

4>FileSystem.cpp
4>D:\Windows Kits\10\Include\10.0.22621.0\um\objidl.h(2588,74): error C2061: syntax error : identifier “byte”
4>D:\Windows Kits\10\Include\10.0.22621.0\um\objidl.h(2602,62): error C2143: syntax error : missing ',' before '*'

What happened? it's seems that a contain error.
Thank you for your report.

**Comment by fredroy** [comment]
It seems to be  coming from a setup/system/configuration error than something related to SOFA itself, as the error is coming from the Windows SDK itself.
Which version of MS Visual Studio are you using ?

**Comment by q1221sr** [comment]
> It seems to be coming from a setup/system/configuration error than something related to SOFA itself, as the error is coming from the Windows SDK itself. Which version of MS Visual Studio are you using ?

i use vs 2022(Windows Kits\10\Include\10.0.22621.0)

**Comment by q1221sr** [comment]
> It seems to be coming from a setup/system/configuration error than something related to SOFA itself, as the error is coming from the Windows SDK itself. Which version of MS Visual Studio are you using ?

i use vs 2022(Windows SDK version 10.0.22621.0 to target Windows 10.0.19045    MSVC 19.37.32822.0)

**Comment by fredroy** [comment]
Mine, according to cmake:
```
Windows SDK version 10.0.19041.0 to target Windows 10.0.22631
MSVC 19.38.33130.0
```
Weird that our numbers are mismatched.

Anyway you may try to downgrade the Windows SDK ?

**Comment by fredroy** [comment]
I' ve updated the SDK
`Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.` 
and v22.12 successfully compiled .

As a the last resort, you may
- update everything (MSVC/SDK)
- delete the build folder

and try again

**Comment by q1221sr** [comment]
> I' ve updated the SDK `Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.` and v22.12 successfully compiled .
> 
> As a the last resort, you may
> 
> * update everything (MSVC/SDK)
> * delete the build folder
> 
> and try again

thank！vs2022 default use windows11 sdk,  and i change windows 10 sdk,
it's OKKK
