### ISSUE TITLE
TriangularFEMForceField Performance optimization

### ISSUE THREAD

**Issue by Alico10** [sofa-framework/sofa#4331]
For large displacements method:
initLarge:
"mstate->read" should return a reference instead of coord vector, this can significantly improve initialization performance, especially when the mesh is relatively large. I suggest checking the similar issues again.
applyStiffnessLarge:
TriangleInformation::rotation and its inverse right multiplication coord can be optimized，just like how we did in TriangleFEMUtils.

**Comment by alxbilger** [comment]
I agree. I'll make a Pull Request soon. Thanks.

**Comment by epernod** [comment]
@alxbilger do you confirm you fixed that in the PR and we can close this issue?
