### ISSUE TITLE
sofa/helper/Polynomial_LD.inl: possible bug

### ISSUE THREAD

**Issue by MarkusWalzth** [sofa-framework/sofa#434]
While trying to clear the build from compiler-warnings I found these pieces of code in in the metioned files:

`        if (!added) listOfMonoMial.push_back(b); nbOfMonomial++;` at 410
`        if (!added) listOfMonoMial.push_back((*itb)); nbOfMonomial++;` at 431
`        if (!added) listOfMonoMial.push_back(-(*itb)); nbOfMonomial++;` at 452

The compiler warning is indicating that the second statement is not effected by the if-statement. But from my point of view, the second statement should be included like

`if(!added)
{
  .... ;
  nbOfMonomial++;
}
`

**Comment by matthieu-nesme** [comment]
PR #442
