### ISSUE TITLE
SofaRigid/RigidMapping.inl: possible bug

### ISSUE THREAD

**Issue by MarkusWalzth** [sofa-framework/sofa#435]
While trying to clear the build from compiler-warnings I found these pieces of code in in the metioned files:

```C++
unsigned int idx = 0;
for( size_t i=0 ; i<size ; )
         for( size_t j=0; j<value && i<size ; ++j, ++i )
            rigidIndexPerPoint[i] = idx;
         ++idx;
```
(code is at line 280 in the file)
The compiler warning is indicating that the `++idx;` statement is not effected by the outer or inner for-loop. As in this case `rigidIndexPerPoint[i] = idx;` is always assigning "0" to the `rigidIndexPerPoint[i]` I would purpose either to change change the mentioned statement to `rigidIndexPerPoint[i] = idx++;` or make `idx` a constant variable.

**Comment by maxime-tournier** [comment]
Thanks for reporting. I had a quick look, but there's no comment to help whatsoever :-/

In any case, devs should really quit this nasty habit of omitting braces around for/if statements that aren't one-liners.

**Comment by matthieu-nesme** [comment]
Which compiler are you compiling with?

**Comment by MarkusWalzth** [comment]
this warning popped up with gcc 6.3.0
The warning printed caused by "-Wmisleading-indentation" 

edit: this issue is not intended to be about the warning. Its more the behaviour of the code

**Comment by matthieu-nesme** [comment]
For sure, it is a bug, we'll fix that. Thanks.

I was interested in the compiler to try it, as the versions of clang and gcc we are using do not pop these useful warnings.

**Comment by MarkusWalzth** [comment]
Nice =) thanks for the quick response!

**Comment by matthieu-nesme** [comment]
PR #441
