### ISSUE TITLE
TetrahedronFEMForcefield: VonMisesPerElement drawing is broken (since v23.06)

### ISSUE THREAD

**Issue by fredroy** [sofa-framework/sofa#4407]
after 200 steps:

v22.12
<img src="https://github.com/sofa-framework/sofa/assets/11028016/94b95e00-f68b-464e-8e19-96bb6332a282"  width="400" />

v23.06
<img src="https://github.com/sofa-framework/sofa/assets/11028016/69dde38e-8b34-4771-aa4a-09889fdea45e"  width="400" />

Moreover it asserts in Debug, while browsing the elements (so I guess it explains why the rest of tetra are blue in not debug)

**Comment by epernod** [comment]
Just checked in a recent version. The drawing is not using the same method anymore and seems fixed. 
![image](https://github.com/user-attachments/assets/f3714e26-ac07-42fe-a1f8-1d6898a701c0)
