### ISSUE TITLE
Unable to reload a Python scene because of OglSceneFrame component

### ISSUE THREAD

**Issue by sebastiennelissen** [sofa-framework/sofa#462]
The scene is generated successfully the first time with the the OglSceneFrame component correctly loaded and without warnings.
But, with or without any parameters specified in the component, I have been unable for the last few days to reload the scene. A segfault error is appearing.
I tried another scene containing this component and the result is the same.
I confirm that without this component, both scenes properly reload (using CTRL+R).

Thanks in advance for resolving this issue!

**Comment by damienmarchal** [comment]
Hi Sebastien,

Thanks for the report. 
Can you tell us which branch/revision of sofa you are using ?

**Comment by sebastiennelissen** [comment]
I am using the lastest version of the master branch of sofa-framework

**Comment by damienmarchal** [comment]
Well Sebastien why not joining us in our codin-spring so we look at that ;)

**Comment by sebastiennelissen** [comment]
Well, I kind of create a minimalist scene so that I can see where the glitch comes from. The reloading is possible with the OglSceneFrame component activated, but not if a transparent object is used.
Then, all is OK with the component :  obstacle.createObject('OglModel', color="0.5 0.5 0.5 1")
But the reloading crashes with : obstacle.createObject('OglModel', color="0.5 0.5 0.5 0.9")

**Comment by guparan** [comment]
@sebastiennelissen, any progress on this issue?
@damienmarchal could you milestone it to v17.12 or v18.06?

**Comment by damienmarchal** [comment]
Hi all,

I tried by cannot reproduce anymore the issue with
```python
import Sofa

def createScene(root):
    root.dt = 0.01
    root.gravity = [0,-9.81,0]

    root.createObject('OglModel', fileMesh="mesh/plane_loop_2.obj", color="0.5 0.5 0.5 0.9")
    root.createObject( 'OglSceneFrame', template='', name="oglSceneFrame1" , style="Cylinders" , alignment="BottomRight" )
```

So I suggest to clost it until someone can provide a failing example.

**Comment by ALIKAOoO** [comment]
[ERROR]   [SofaRuntime] ValueError: Object type OglSceneFrame<> was not created
The object 'OglSceneFrame' is not in the factory.
This component has been MOVED from SofaOpenglVisual to Sofa.GL.Component.Rendering3D since SOFA v22.06.
To continue using this component you may need to update your scene by adding
<RequiredPlugin name='Sofa.GL.Component.Rendering3D'/>

`import Sofa
import Sofa.Core
import Sofa.Gui
import Sofa.Simulation
import Sofa.SofaGL

def main():
 
    root=Sofa.Core.Node("root")
    createScene(root)

    Sofa.Simulation.init(root)

    Sofa.Gui.GUIManager.Init("myscene", "qglviewer")
    Sofa.Gui.GUIManager.createGUI(root, __file__)
    Sofa.Gui.GUIManager.SetDimension(1080, 800)
    
    Sofa.Gui.GUIManager.MainLoop(root)
    Sofa.Gui.GUIManager.closeGUI()

def createScene(rootNode):
    rootNode.addObject("VisualGrid", nbSubdiv=10, size=1000)
    confignode = rootNode.addChild("Config")
    confignode.addObject('OglSceneFrame', style="Arrows", alignment="TopRight")
    sphere = rootNode.addChild("sphere")
    sphere.addObject('MechanicalObject', name="mstate", template="Rigid3", translation2=[0., 0., 0.], rotation2=[0., 0., 0.], showObjectScale=50)
    
    sphereVisu = sphere.addChild("VisualModel")
    sphereVisu.loader = sphereVisu.addObject('MeshOBJLoader', name="loader", filename="D:\VR\SOFA\build\v24.06.00\share\sofa\mesh\\ball.obj")
    sphereVisu.addObject('OglModel', name="model", src="@loader", scale3d=[50]*3, color=[0., 1., 0.], updateNormals=False)
    sphereVisu.addObject('RigidMapping')
    return rootNode

if __name__ == '__main__':
    main()`
