### ISSUE TITLE
Enhancing Collision Physics in Unity with Sofa Framework Integration

### ISSUE THREAD

**Issue by JaggerYu928** [sofa-framework/sofa#4621]
Hi Hugo,

I'm currently trying to control the movement of a 3D model in the Sofa Framework through Unity. I've extended the SofaPhysicsAPI and implemented movement using the applyTranslation method from SofaOutputMesh. So far, I've managed to successfully move the 3D model within Unity. However, when two objects collide, there's no physical response. Could you offer any advice or suggestions for this task?

Jack Yu

**Comment by epernod** [comment]
Hi,
I suggest you give a look to this repository: https://github.com/InfinyTech3D/SofaUnity
You can also open an issue or a GH discussion on this repository related to SOFA-Unity integration.
Thank you
