### ISSUE TITLE
Update libQGLViewer to latest version

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#464]
Problem: build errors in libQGLViewer with MSVC 2015. See https://github.com/sofa-framework/sofa/pull/461
Solution (TODO): update libQGLViewer to the latest version (2.7.0).

**Comment by ErwanDouaille** [comment]
It looks like this issue have been fix

**Comment by guparan** [comment]
Not really, #461 was a quick fix.
The real fix is to update libQGLViewer to latest version.
