### ISSUE TITLE
update glew in windows dependencies

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#466]
Is it possible to update the glew version distributed in the windows dependencies?

We can get this problem with the actually distributed version 1.13: https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library#Initialization_of_GLEW_1.13.0_and_earlier

______________________________________________________

Suggested labels:

**Comment by fredroy** [comment]
I dont see any problem with updating the glew library (except if it is introducing other problems I am not aware of ;) )
@guparan I let you do it ?

**Comment by guparan** [comment]
It's done! Reopen if something is wrong ;-)

**Comment by matthieu-nesme** [comment]
Thanks !
