### ISSUE TITLE
Behavior of SphereModel::getContactPointWithSurfacePoint

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#47]
Hi all,

in SphereModel.cpp it is unclear to me why the functions 

``` cpp
Vector3 TSphere<defaulttype::getContactPointByNormal( const Vector3& );
Vector3 TSphere<defaulttype::getContactPointWithSurfacePoint(...);
```

Are specialized on Vec3fd to return the center only. 

Second question is why do the message says that SphereModel only work with a Vec3 while it seems to also accept Rigid3 types. 

Anyone can explain ?

Thank,
DM.

**Comment by matthieu-nesme** [comment]
The Rigid SphereModel was added "recently" and the comment is not up-to-date.

Rigid Spheres can rotate (Particle spheres cannot), and modeling the contact directly at their surfaces allows extra behaviors such as friction.

On the other hand, adding contact points at the surfaces of particle spheres would only add unnecessary extra cost (mapping+mstate). Creating a spring/constraint directly between the particle sphere centers is more efficient w/o restriction.

**Comment by damienmarchal** [comment]
Thank Mathieu for the info.

So you are confirming that the name getContactPointWithSurfacePoint mismatch the behavior of what is actually implemented for vec3. Shouln't we separate the two behavior in two function with clear naming ?

DM

**Comment by damienmarchal** [comment]
I created a branch for this issue in: https://github.com/SofaDefrost/sofa/tree/fixing-sphere

EDIT: The branch has been deleted.
