### ISSUE TITLE
[runSofa] InteractiveCamera doesn't work with QGLViewer

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#481]
Hey,

Trying to understand how the view/camera works, we found than InteractiveCamera is working well with OpenGL viewer but not with QGLViewer. Is this a known issue ? 

Maybe a warning or something else should be sent. I played in the past with the interactiveCamera and it was not working, I guess, due to this issue.

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Hello Erwan,

Good idea to make a warning. 

Now at the fundamental level to me all this part of Sofa is "broken". The fault is that there is no clear difference between the "in editor" camera (the ones use in the viewer/runSofa editor) and the "in-scene" camera. Making this distinction is important and I'm sure that for runSofa2 we will need to make that clear. 

To be clear...think how Unity is doing... some panel are showing "external" view of the scene for editting..while one or multiple "in-scene" cameras are used in the "game" panel for the rendering. 

Actually we also have the same problem with all the interaction.

**Comment by fredroy** [comment]
This will require some work in QGLViewer (for sure not ready before the end of 2017).
Moreover, a new GUI is supposed to replace the current one so for now, it has been decided to give up on this feature. We close this issue and but one can reopen it if he is motivated to solve it.
