### ISSUE TITLE
CMake style : c89da68 is indeed monstruous.

### ISSUE THREAD

**Issue by fjourdes** [sofa-framework/sofa#489]
On top of the many things that c89da68 does (wrong), see PR #487 for a glimpse, I noticed that the 
inclusion of unit tests executable related to a given library have been extracted outside from the CMakeLists.txt of the very library it is supposed to test. 

What I initially did was to have 
```
# MyLibrary/CMakelists.txt

addLibrary( MyLibrary SHARED ${HEADER_FILES} ${SOURCE_FILES} )

if(TARGET gtest) 
   # there is a gtest TARGET, so we are interested in having unit tests built for sure ! 
   # since we do not reditribute unit tests, doing the find_package() thing is probably 
   # overkill... If the main CMakelists.txt adds gtest to the build, then the gtest TARGET 
   # will be defined
   add_subdirectory(MyLibrary_test)
endif()
```

All the information related to the library is visible from the library `CMakelists.txt` and not hidden from the developer in some remote unrelated file, which also implies that you must include all the Sofa modules in your build.
What if I decide not to include the whole library set of Sofa and still get my precious unit tests executed ? 
Hint : I do not use the main `CMakelists.txt` provided in the master branch, and probably never will.

______________________________________________________

Suggested labels:

**Comment by fredroy** [comment]
This issue can be closed as the unittests are activated now as advised by @fjourdes since ... I dont remember but few releases ago.
