### ISSUE TITLE
CMake style : "_d" debug prefix is removed from all plugins binaries if you don't the use sofa_add_plugin macro

### ISSUE THREAD

**Issue by fjourdes** [sofa-framework/sofa#490]
This was introduced by e33ff21e75356e6967509cc0822d72c74f2d0247 
So in order to have the "_d" debug postfix in your binary, you must use the `sofa_add_plugin` macro. 
I do not use this macro, and I did not mind its existence because I thought it was only related to have a pretty presentation of the plugins in the cmake-gui.

https://github.com/fjourdes/sofa/blob/insimo_sofabuild/CMakeLists.txt is the main CMakelists.txt  I use in my fork. Could be much simpler, because I started it by modifying the CMakeLists.txt fomr master, and also I really spent 5 minutes on it. The list of projects and plugin to build is simply passed through CMake cache variables.

However now you are in the case where doing a 
`add_subdirectory(my_plugin_directory)` and 
`sofa_add_plugin(my_plugin_directory)` both works, and ends up giving different names for your binaries regarding of the config you use for building. 

I do not mind strategies like https://github.com/fjourdes/sofa/blob/insimo_sofabuild/SofaKernel/SofaCommon/CMakeLists.txt for packages that are a composition of libraries - I think it is an improvement in this particular case - but for plugins that are a single library, all the necessary information should reside on their CMakeLists.txt

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
It's not easy to have a comfortable solution for both CMake experts and non-experts but we are trying to make everyone happy by providing highly factorized macros (big refactoring happened in #1433). 
Of course you are free to use them or not.
I close this issue since it's quite old. Feel free to reopen if necessary :wink:
