### ISSUE TITLE
[SofaGraphComponent] Crash caused by check in SceneCheckAPIChanges when using RestShapeSpringsForceField

### ISSUE THREAD

**Issue by vmagno** [sofa-framework/sofa#491]
When trying to use the RestShapeSpringsForceField component (on branch master), runSofa crashes upon checking the scene. The responsible check tries to find a data called "external_rest_shape". However, that data has become a link (since after v17.06), so the function findData returns a NULL pointer.

It looks like that check cannot fulfill its purpose since the data will always be a link, no matter what the user wrote in their scene. It would need to parse the input string to verify whether the "@" is there in front of the attribute.

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Hi @vmagno,
This bug is fixed in the pending pull-request https://github.com/sofa-framework/sofa/pull/479
I add the backport label for v17.06 fixing.

**Comment by damienmarchal** [comment]
I agree with @vmagno that the check cannot fulfill its purpose and have to be handled at parsing level.
