### ISSUE TITLE
SofaPython without cpp executable

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#492]
Hi everyone,

I'm working right now on a small improvement that will allow people to directly import SofaPython plugin library (libSofaPython.so) inside their python script without the need for an external application (exemple runSofa).

A python script could than looks something like:

```
# scene.py
from libSofaPython import Sofa

root = Sofa.loadScene("examples/Demos/caduceus.scn")
root.init()
for i in range(0,2):
  ...
  root.simulationStep(0.01)
  # Some data and timing analysis in python here...
  ...
Sofa.cleanup()
```
and could be called simply with
`python scene.py`

You can follow the development on the branch
https://github.com/jnbrunet/sofa/tree/sofa_python_without_executable

For now, the primary use for us is to create a batch application directly in python for our experiments (mainly time and precision benchmarks), but maybe some day we could also use this for a complete GUI experience.

If you got any suggestion, please do not hesitate to write them here.

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Hi,


Currently to launch batch of simulation from python there is already something in tools/sofa-launcher. 
You can find example of launching the sofa simulation in integration_example.py and for the GUI I'm using Jupyter/IPython. 

The only drawback of the current sofa-launcher is that there is no way to interact with the running simulation (only start it and wait for results in the console). If I understand correctly this may be solved with your work so I'm waiting with interest your PR.

**Comment by jnbrunet** [comment]
Hi @damienmarchal ,

Yes, the main idea is to have more control over the simulation. My work will allow to use Sofa as a real python module, in contrast to launching a binary executable that than execute a python script.

It's really not a big feature since it only needs a valid entry point in the dynamic library so that python can initialise the module. After that, the wrappers will work the same way as now.

The work will then be more around expending the current wrappers to have more control over Sofa's components.

**Comment by fjourdes** [comment]
I think it is very useful to have this sort of functionality. 
For example it would be very useful for people that want to do analysis and validation of a simulation.

**Comment by maxime-tournier** [comment]
> It's really not a big feature

Granted, it's not *that* big, but still:
- you need to properly initialize/finalize sofa and core modules (see Main.cpp in the runSofa application)
- you need to handle the case where the loaded scene already has python scripts, and let the `PythonEnvironment` know the interpreter is being run from the outside when initializing (and maybe deal with all the `sys.path` / `__file__` abuses down there)
- probably have a good fight with the GIL down the road
- how should this feature integrate with existing python scenes? Should it be possible to load scenes from within python scenes? (I would probably put your feature in a module separate from `Sofa` for this reason)
- what happens when `Sofa.cleanup()` gets called but python objects still hold c++ objects that are to be destructed when python exits ?

But I am really all for it, so good luck with that :-)

**Comment by damienmarchal** [comment]
An alternative approach may be to follow the Jupyter's way:
http://jupyter.org/

**Comment by jnbrunet** [comment]
Hey @maxime-tournier ,

You bring valuable points here. You are absolutely right, it is not that trivial, I'm starting to see it now. Here is what I observed during my tests (I'm working part time on this, it is entirely possible that I come back later to correct those statements of mine :) )

> you need to properly initialize/finalize sofa and core modules (see Main.cpp in the runSofa application)

Yes. I'm usually leaning towards making most of the functions available and let the script use what it need. So if I'm writing a _runSofa_ like application in python, I should be able to init the components there, create/set the simulation, add the needed message handlers to the MessageDispatcher, and set the paths (plugin, config, sofa prefix) there. If this complicate too much the python script, than making optional python util scripts that set all of this for the user could be a clean option. But I don't think the library should do this in the user's back without transparency.

> you need to handle the case where the loaded scene already has python scripts, and let the PythonEnvironment know the interpreter is being run from the outside when initializing (and maybe deal with all the sys.path / __file__ abuses down there)

The PythonEnvironment will create an interpreter if there isn't one (like when launching for a binary executable), or use the one already defined. In this case, PythonEnvironment will use the interpreter that called the script (ex python runSofaPython.py).  No new python interpreter nor python thread a created (I've just checked to be sure).

> probably have a good fight with the GIL down the road

The current GIL usage in the plugin seems to align correctly with this feature since we "attach" the PythonEnvironment to an interpreter instead of initialising a new one. No new threads are created.

> how should this feature integrate with existing python scenes? Should it be possible to load scenes from within python scenes?

Yes, it seems to work so far. However:

- Loading the SofaPlugin library from within a python script that already imported it should be avoid for now since I'm not sure what side effects this will bring. Right now doing it seems not so bad as, again, we only attach the environment to the already created python environment. 
- A ScriptController will need to be added in order to trigger script events so that the python scene's functions (initGraph, onBeginAnimationStep, etc) are called. The createScene function is called by the SceneLoaderPY so this one is fine.

> (I would probably put your feature in a module separate from Sofa for this reason)

I think this should be entirely a part of the SofaPython plugin in order to keep what is related to sofa in python there.

> what happens when Sofa.cleanup() gets called but python objects still hold c++ objects that are to be destructed when python exits ?

This is a good question. PythonEnvironment::Release is called when python exits (called by the static raii destructor...). I'll have to check this.

> But I am really all for it, so good luck with that :-)

Thanks!

**Comment by jangirrishabh** [comment]
Hello @jnbrunet  great work on trying to address this issue, cheers! It would be very helpful in a lot of cases, I have been trying to work on one such case and using your branch, if you could point me to some docs/examples as a starting point it would be very helpful.

**Comment by jnbrunet** [comment]
Hey @jangirrishabh ,

You can already clone [this branch](https://github.com/jnbrunet/sofa/tree/sofa_python_without_executable). Once compiled, you will find the file libSofaPython.so in your **sofa_build_directory**/lib folder. Simply add this folder's path to your python sys path, and finally import the lib to your python script with `from libSofaPython import Sofa`.

If you are not on Linux, you will have to manually copy the library name to the same file name but with the ".so" extension (ex: libSofaPython.dylib -> libSofaPython.so).

Also, I've stop the development of this feature since @damienmarchal is working on a newer python plugin that will support this feature much better than what I've done here. You can follow the development [here](https://github.com/sofa-framework/sofa/pull/771).

**Comment by jnbrunet** [comment]
I'm closing this issue since SOFA is now available as a python module in the [SofaPython3](https://github.com/sofa-framework/plugin.SofaPython3) project.
