### ISSUE TITLE
SimpleGUI broken, ImageBMP.h no such file or directory

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#493]
Working on master.
SOFAGUI_GLUT turned on

#include <sofa/helper/io/ImageBMP.h> no such file or directory, same for #include <sofa/defaulttype/LaparoscopicRigidTypes.h>. Both are needed for SimpleGUI.cpp and MultithreadGUI.cpp.

Does anybody know where I can found it ? 
Plus, the need of LaparoscopicRigidTypes sounds weird to me ...

______________________________________________________

Suggested labels:

**Comment by fjourdes** [comment]
Comes from 
- PR#424 for ImageBMP, it could probably be worthy to do a grep on the whole code base to find leftovers 
- LaparscopicRigidTypes are no longer used by anyone, so someone must have removed it recently, but then again the the whole code base was not "grepped" for this string so this one at least must have been left over. 

But I wonder why I got assigned to this issue ? 
EDIT: Ok I am not assigned anymore ;)

**Comment by ErwanDouaille** [comment]
@fjourdes sorry for the assignment, miss click. I wanted to assign fredroy :/
But your answer looks good to me, thanks for the PR

I will try to fix the SimpleGUI soon.
