### ISSUE TITLE
Deprecating option macros defined in config.h

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#494]
After #475 merge, we should decide when we want the old behavior (all options in `config.h`) to stop working.
The work to adapt all config.h includes in SOFA is easy (searching for macros and including the right config/*.h file) but we have to find the best solution to permit translation for everybody around.

What do you think?

**Comment by damienmarchal** [comment]
One approach discussed this meeting was:
keep the current config.h for compatibility to external code base but in sofa progressively stop using it and replace it with specific ones eg: "config/comon_defines.h" (that does not contains the inclusion of config/build_option_opengl.h/experimental/etc..."

**Comment by guparan** [comment]
This work has been done in #1397
