### ISSUE TITLE
MarchingCube frenzy...

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#496]
I was searching for a marching cube to render an implicit field (a real one, given from any analytic formulation not just metaball or blobs union). 

I didn't find one, is there any ? 
While I was searching I found a least 4 different variations ...and thus wonder if there is no opportunity to refactor a bit. 

______________________________________________________

Suggested labels:

**Comment by jnbrunet** [comment]
+1
Having a clean, generic and intuitive method for marchingCube would be awesome.

**Comment by damienmarchal** [comment]
Thanks for the feedback Jean-Nicolas, 

Could you provide examples of what would look like a generic/inituitive version in your view ? 

On my side I'm thinking of something like:
```xml
<CustomField name="scalarfield" source="myfield.py" evalFunctionName="myImplicitFunction"/> 
<SurfaceMeshGenerationFromScalarField field="@scalarfield" output="@topology"/>

<MetaBallField name="scalarfield2" radius="0.5" positions="0 0 0"/> 
<SurfaceMeshGenerationFromScalarField field="@scalarfield2" output="@topology2"/>
```

**Comment by jnbrunet** [comment]
This is pretty close to what I had in mind. Maybe call (or alias) the component with simply... "MarchingCube". It would become easy to find for everybody. Like you said, at the same time we could clean (refactor, delete) the other implementations of MarchingCube variations . Then a simple grep on the code from a new Sofa user  would outline the "MarchingCube" component and welcome him in the community with joy :)

**Comment by damienmarchal** [comment]
Actually I have two implementation to generate surface from implicit field. One is marching cube, the other is using CGAL. This is why I gave a rather generic name instead of the name of the underlying algorithm.

**Comment by guparan** [comment]
Hey @damienmarchal is this issue over? If not, could you label it please?
BTW it would have been nice to post this on [SOFA Forum](https://www.sofa-framework.org/community/forum/) ;-)

**Comment by damienmarchal** [comment]
Done...but the PR still remains to be done :)
