### ISSUE TITLE
Is there any ways to Given a user-set initial displacement field (U) and solve a static problem to get the external force field (Fout)

### ISSUE THREAD

**Issue by SustechShenCong** [sofa-framework/sofa#4960]
The static problem can be simply described as $F_{int} = F_{out}$, and $F_{int}=F_{nl}+KU$, where $F_{nl}$ is the nonlinear internal force vector while $KU$ is the linear one. If I have a **Arbitrarily Reasonable Displacement Fields** (U), how can I input this into SOFA and compute the $F_{out}$ by solving a static problem or extract the external force from API, and the nonlinear internal force $F_{nl}$ vector is then calculated. 
Your answers will be appreciated !

**Comment by SustechShenCong** [comment]
Another accompanying issues, does SOFA consider geometric nonlinearity?

**Comment by bakpaul** [comment]
Hello ! 

Ii am sorry but this is not an issue. This is a discussion topic. Could you make a discussion topic in the forum -> https://github.com/sofa-framework/sofa/discussions ?

Thank you.

**Comment by SustechShenCong** [comment]
Thanks for your reply !
