### ISSUE TITLE
Unable to run SOFA Defrost, soft robot tutorials on my linux machine please help

### ISSUE THREAD

**Issue by discreet26** [sofa-framework/sofa#5029]
@alxbilger any help will be hughly appreciated, i am stuck.  trying to understand this https://github.com/SofaDefrost/SoftRobots/tree/master/examples/tutorials/CableGripper but i am unable to run this in my machine. Could you please guide me. Thanks in advance.

**Comment by bakpaul** [comment]
Hello,

It seems that you have already opened a discussion on this same topic : https://github.com/sofa-framework/sofa/discussions/5021. Github discussion is the only channel for such requests. 

Please remember that we are only a few dev on this open-source project, we are doing our best to develop the code and help the community. @hugtalbot already started to help you on your discussion topic so please, be patient. 

I'm closing this issue

**Comment by discreet26** [comment]
sorry for the haste, i thought that my issue was down because of no response on the discussions tab. i will keep it in mind from now onwards.
