### ISSUE TITLE
Mass spring implementation

### ISSUE THREAD

**Issue by Ceciliaaasoldii** [sofa-framework/sofa#5086]
Hi I want to implement a mass spring system of an object in collision with another one. Is it correct that while use a force field like MassSpringForceField the collision algorithm to use is the Penalty and not the Lagrange Multiplayer?

**Comment by epernod** [comment]
Hi,

please could you post your question on the github discussion: https://github.com/sofa-framework/sofa/discussions
People will help you there.

Issues are for dev topics or bug reporting inside the code base of SOFA.
Thank you
