### ISSUE TITLE
Bug opening scene file Windows  8

### ISSUE THREAD

**Issue by romainla** [sofa-framework/sofa#509]
Hello,

I am working on Windows 8 and Sofa v17.06 has a segmentation fault when opening a scene file. Consequently, the program instantly crashes.

Have you already heard about this kind of bug?

Best regards

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Hi @romainla 
Many thanks for your report. We are not aware of this bug. 
Could you detail the steps to reproduce it and the output you got?
Cheers

**Comment by ErwanDouaille** [comment]
@romainla  Can you specify which visual version are you using ? 
I will try with the binaries

**Comment by ErwanDouaille** [comment]
The 17.06 exe run fines on win8.

**Comment by guparan** [comment]
I close this for now. If you still have any issue with Windows 8, feel free to re-open with some output.
