### ISSUE TITLE
ArgumentParser, limitations with short argument name

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#512]
While trying to add new options, I encounter the problem of adding new short argument names with consistency. The thing is, right now you have to design your option by using a short name (a char) and a long name (a char*).
But many options already exist. Finding a non used char which is consistent for an option is quite difficult. By reading existents short names, I assume I'm not the first one encountering this issue.

Shouldn't it be better to let the user having the ability of using char* instead of char ? 
Of course short name still have to be "short" and we can add rules defining the maximum lenght of a short name, 3 for example.

By example : 
`    .option(&colorsStatus, "col", "colors","use colors on stdout and stderr (yes, no, auto)")
` From POV, it is more consistent than : 
`    .option(&colorsStatus,'z',"colors","use colors on stdout and stderr (yes, no, auto)")
`

Here is an overview of the function : 

```
/** Declare an optional argument
    \param ptr pointer to the variable
    \param sho short name
    \param lon long name
    \param help
    */
    template<class T> inline
    ArgumentParser& option( T* ptr, char sho, const char* lon, const char* help )
    {
        string sn, ln(lon), h(help); sn += sho;

        if( sho!=0 && shortName.find(sho) != shortName.end() )
        {
            msg_fatal("ArgumentParser") << "name " << sn << " already used !";
            exit(EXIT_FAILURE);
        }
   ....
```

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
I totally agree and would upvote such a PR. Actually I wonder how could this not have been discussed already.

**Comment by guparan** [comment]
@ErwanDouaille is the feature ready on your side? Do you plan to open a PR?

**Comment by ErwanDouaille** [comment]
I didn't do anything right now. But I was thinking how we could change it.

For the char length problem it's quite simple, but i think we need to refactor a lot of things in it.

By example, one cool feature would be to be able to add arguments without changing main.cpp. Like adding a virtual function to BaseGUI and let subclasses having the ability to add options.
The main.cpp will still have basic arguments and will be able to list registered gui options. I don't like the (aGui only) comment ... :/

I can start working on it on my free time.
