### ISSUE TITLE
MeshSpringForceField Does Not Support Index-Based Spring Creation

### ISSUE THREAD

**Issue by antennae** [sofa-framework/sofa#5135]
### Problem

**Description**
`MeshSpringForceField` fails to create springs based on specified indices. Instead, it always derives the springs directly from the topology.

This behavior appears to have changed following PR #4649.

Previously:
- `MeshSpringForceField::init()` created springs based on topology, then called `StiffSpringForceField::init()`.
- `StiffSpringForceField::init()` replaced these topology-based springs with new ones derived from the specified indices.

Currently:
- `MeshSpringForceField::init()` still creates springs based on topology, but now calls `SpringForceField::init()`.
- `SpringForceField::init()` keeps the topology-based springs, basically ignoring any specified indices.

As a result, it is no longer possible to create springs based on indices using `MeshSpringForceField`. However, SOFA does not provide a warning or error when indices are specified but unused, which can lead to confusion.

**Steps to reproduce**
Attempt to add springs using `MeshSpringForceField` by specifying indices and lengths.

**Expected behavior**
Springs should be created using the specified indices and lengths.

---------------------------------------------

### Example

**Context**

- System: Ubuntu 24.04
- Version of SOFA:master branch at commit 4bfb1d5

Below are screenshots comparing the behavior of `MeshSpringForceField` and `SpringForceField` when trying to create a spring between points 1 and 3.

**using `MeshSpringForceField`:**
![Screenshot from 2024-11-21 16-28-44](https://github.com/user-attachments/assets/c1a4a988-7d3c-4f3c-8912-fd08126cf851)

**using `SpringForceField`:**
![Screenshot from 2024-11-21 16-28-34](https://github.com/user-attachments/assets/798fff49-d853-4423-a758-6ebebb92e47e)

Example Scene:
```python
import Sofa


def createScene(rootNode):
    # required plugins:
    rootNode.addObject("RequiredPlugin", name="Sofa.Component.AnimationLoop")
    rootNode.addObject(
        "RequiredPlugin",
        name="Sofa.Component.Constraint.Lagrangian.Correction",
    )
    rootNode.addObject(
        "RequiredPlugin", name="Sofa.Component.Constraint.Lagrangian.Solver"
    )
    rootNode.addObject("RequiredPlugin", name="Sofa.Component.IO.Mesh")
    rootNode.addObject(
        "RequiredPlugin", name="Sofa.Component.LinearSolver.Direct"
    )
    rootNode.addObject(
        "RequiredPlugin", name="Sofa.Component.ODESolver.Backward"
    )
    rootNode.addObject(
        "RequiredPlugin", name="Sofa.Component.SolidMechanics.Spring"
    )
    rootNode.addObject("RequiredPlugin", name="Sofa.Component.StateContainer")
    rootNode.addObject(
        "RequiredPlugin", name="Sofa.Component.Topology.Container.Constant"
    )
    rootNode.findData("gravity").value = [0, 0, 0]
    rootNode.addObject(
        "VisualStyle",
        displayFlags="showVisualModels showBehaviorModels showCollisionModels \
            hideBoundingCollisionModels showForceFields \
                showInteractionForceFields hideWireframe",
    )
    rootNode.findData("dt").value = 0.01
    rootNode.addObject("FreeMotionAnimationLoop")
    rootNode.addObject(
        "GenericConstraintSolver",
        name="ConstraintSolver",
        tolerance=1e-10,
        maxIterations=2000,
        multithreading=True,
    )

    solver_node = rootNode.addChild("solver_node")
    solver_node.addObject(
        "EulerImplicitSolver",
        firstOrder=False,
        rayleighStiffness=0.05,
        rayleighMass=0.02,
    )
    solver_node.addObject(
        "SparseLDLSolver",
        name="Solver",
        template="CompressedRowSparseMatrixd",
    )
    solver_node.addObject(
        "GenericConstraintCorrection",
        name="ConstraintCorrection",
        linearSolver=solver_node.Solver.getLinkPath(),
    )
    solver_node.addObject(
        "MeshSTLLoader",
        name="SurfaceMeshLoader",
        filename="./test.stl",
    )
    solver_node.addObject(
        "MeshTopology", name="topology", src="@SurfaceMeshLoader"
    )
    solver_node.addObject(
        "MechanicalObject",
        name="states",
        showObject=True,
        showIndices=True,
        showIndicesScale=0.1,
    )
    solver_node.addObject(
        "MeshSpringForceField",
        name="spring",
        stiffness=1000,
        indices1=1,
        indices2=3,
    )
    # solver_node.addObject(
    #     "SpringForceField",
    #     name="spring",
    #     stiffness=1000,
    #     indices1=1,
    #     indices2=3,
    #     lengths=2.82843,
    # )
```

Example Mesh:
```stl
solid 
facet normal 0 0 1
 outer loop
  vertex -1 -1 0
  vertex 1 -1 0
  vertex 1 1 0
 endloop
endfacet
facet normal -0 0 1
 outer loop
  vertex -1 -1 0
  vertex 1 1 0
  vertex -1 1 0
 endloop
endfacet
endsolid 
```

---
### Proposed fix
- Restore support for creating springs using indices in `MeshSpringForceField`.
- Or introduce a warning when `indices1` and `indices2` are specified but ignored.

**Comment by bakpaul** [comment]
Hello, 

It seems like the `SpringForceField` is doing what you expect from the `MeshSpringForcefield`. The `MeshSpringForcefield`, as its name states, is meant to add springs on edges based on the mesh. The mesh is its input data to create the springs. If you don't want to use the mesh to define the springs and want to define them by hand, then you should use the `SpringForceField`. 

Maybe I didn't understand your need well, if so, please tell me why you can't use the `SpringForceField` and need to use the `MeshSpringForcefield` but without taking the mesh information into account ?

**Comment by damienmarchal** [comment]
> Hello,
> 
> It seems like the `SpringForceField` is doing what you expect from the `MeshSpringForcefield`. The `MeshSpringForcefield`, as its name states, is meant to add springs on edges based on the mesh. The mesh is its input data to create the springs. If you don't want to use the mesh to define the springs and want to define them by hand, then you should use the `SpringForceField`.
> 
> Maybe I didn't understand your need well, if so, please tell me why you can't use the `SpringForceField` and need to use the `MeshSpringForcefield` but without taking the mesh information into account ?

I think the point is that the behavior changed on MeshSpringForceField between the old and new version without a warning to users.

**Comment by antennae** [comment]
Hi,

Yes, `SpringForceField` is doing what i expected and it works well. 

I was actually working with a scene that was created in an older SOFA version, which creates springs using indices with `MeshSpringForceField`. And in the newer SOFA version, the behaviour of `MeshSpringForceField` changed and the scene doesn't work anymore. I have to do some research to find out why. 
So in my opinion, this behaviour change can be confusing for users working with older scenes and a clearer guidance could be very useful.

**Comment by bakpaul** [comment]
OK I get it, we can add a warning message in the init of MeshSpringForcefield to warn when the data is set. Thank you !

**Comment by bakpaul** [comment]
TEll me if that solves you issue : https://github.com/sofa-framework/sofa/pull/5136

**Comment by antennae** [comment]
Thanks for the updates!  I just tested and it did solve my issue.
