### ISSUE TITLE
Call for new having new EXPERIMENTAL features in 17.12

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#517]
Hello,

I think it would be great (if not mandatory) to have in this release of Sofa new features and not only bug fixes. 

To make that possible I suggest to use the  SOFA_WITH_EXPERIMENTAL_FEATURES options to conditionally activate plugins or component that are in their way for integration but are not considered as stable enough or that may be subject to API change in 18.06. Those should print a warning message in their init function if used. 

If agreed on the principle of allowing EXPERIMENTAL new components in 17.12 I have the following features/component to propose (all are located in plugins):
- In plugin/PSL:
     - the PSL scene file format
- In plugin/SofaImplicitField: 
     - CustomField (to implement implicit field in python and/or cython)
     - SurfaceMeshFromImplicitField (to generate a surface mesh from an implicit field using a marching cube)
     - ImplicitFieldViewer (to visualize the implicit surface)
     - python/difigeom (a complete library to make complex procedural geometry using 
                                  distance field and python+cython)    
- In plugin/CGAL: 
    - SurfaceMeshFromImplicitField (generate a surface mesh from an implicit field using CGAL)
    - VolumeMeshFromImplicitField (generates a tetrahedral mesh from implicit field using CGAL) 

And you ? Do you have things that you would like to have integrated ? 

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Do any of you have any suggestion for this topic 
@hugtalbot, @guparan, @bcarrez, @fredroy, @epernod  and others ?

**Comment by bcarrez** [comment]
I think this has some benefits:
- the features are already merged in the master branch and *should* work without the hassle of merging different dev branches
- they are OFF by default, so they are not disturbing anyone

But we should take care of the following:
- they must be tested (at least ONE ci config should activate them)
- they are not meant to stay "experimental" forever, so there is an implicit contract to move them to "non-experimental" as soon as they are ready and working. "EXPERIMENTAL_FEATURES" must not be the carpet above the decisions we don't make. Typically, an "experimental" feature in release N should be merged in release N+1.

**Comment by damienmarchal** [comment]
Some news from DEFROST for 17.12
- I'm still working hard one SofaImplicitField & PSL 
- Bruno will make an extra effort to finalize the PR of a SofaPython3 plugin.
- Erwan will do the same for the Communication plugin. 
And Eulalie splitted ou soft-robots plugins in a public and a private part (the pattented one) so we can release it.  

And you.. what are your plan for 17.12 ?

**Comment by ErwanDouaille** [comment]
Let's add https://github.com/sofa-framework/sofa/issues/537 ? (linux only)

**Comment by damienmarchal** [comment]
@guparan, @hugtalbot  
I really would like to see new features for the 17.12 release and to me this is more important that having the 17.12 release released in 2017 ;) 

So please @ErwanDouaille , @bcarrez (and me) please finish your work.
For those that have nearly finish work please make a PR in the WIP state so that we can see. 

For the binary distribution... i think that the pre-build binaries may/should not include the experimental feature but at least the tagged version on the repository may have them. 

EDIT: @fredroy the sofa from python integration should be also a nice addendum, but there is no PR yet.

**Comment by ErwanDouaille** [comment]
@damienmarchal, headlessrecorder is ready.

For the communication plugin I found à bug in zmq matrix support. And I'm in holiday.

**Comment by damienmarchal** [comment]
News feature  are now for 18.06. I close the issue
