### ISSUE TITLE
Data field as private in a class

### ISSUE THREAD

**Issue by untereiner** [sofa-framework/sofa#529]
I am wondering why the fields `nbPoints` and `points`in [PointSetTopologyContainer](https://github.com/sofa-framework/sofa/blob/463ad43061881fb94efc4366a80e3d1f9e99c4a1/SofaKernel/modules/SofaBaseTopology/PointSetTopologyContainer.h) are of type Data _and_ private in the class. They can not be directly accessed from the outside. They could also be a simple `unsiged int` and `helper::vector`... Is it for serialisation ?

______________________________________________________

Suggested labels:

**Comment by epernod** [comment]
This comes from comit 570b09b

> UPDATE: PointSetTopologyContainer maintains a list of point indices, accessible through the data points. Move data nbPoints to private so that only dedicated methods setNbPoints and getNbPoints are accessible to derived / friend classes.

Indeed, not sure if Data is needed

**Comment by untereiner** [comment]
Thanks for the replay! 

> Indeed, not sure if Data is needed

That was the point of my question!

**Comment by untereiner** [comment]
@epernod is it still relevant or can it be closed ?

**Comment by epernod** [comment]
can be closed, In fact, I think it was removed
