### ISSUE TITLE
Duplication line in Cmakelist qt

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#535]
https://github.com/sofa-framework/sofa/blob/44c4f5bce79acdb36c120148d2cea1717c0c2c58/applications/sofa/gui/qt/CMakeLists.txt#L203

I don´t know why but two lines are identical. With or without the if, they both does the same result.
The spotted one and the line above it.

**Comment by ErwanDouaille** [comment]
@thomas-lemaire can you help ?
Related to : https://github.com/sofa-framework/sofa/commit/d24626e94b4153632897de1c43cfd30a88062a00#diff-f49ce4e9ac50104a4e4d86c9bf4036fb

Thanks

**Comment by thomas-lemaire** [comment]
Sorry, I am not using any more this qt part of sofa
just reading, obviously just remove the if(), it does not help in anything !

**Comment by guparan** [comment]
Indeed with https://github.com/sofa-framework/sofa/commit/d24626e94b4153632897de1c43cfd30a88062a00#diff-f49ce4e9ac50104a4e4d86c9bf4036fb the whole if block should have been removed :-)
