### ISSUE TITLE
[runSofa] HeadlessRecorder 

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#537]
HeadlessRecorder is, as its name suggest, a new gui plugin who allow users to records sofa visualisation without any windows (batch only)

⚠ Linux only ⚠

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Could we close this issue as it seems redundant with #538 ?

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]
