### ISSUE TITLE
Why LightManager test fails ?

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#54]
Hi all,

One test related to LightManager is failing only on windows eg:
https://github.com/sofa-framework/sofa/commit/6d3e1398363cc617124fd25522193ef20b1b7b1c

The failing scene is rather simple: 
```xml
<Node name='Root' gravity='0 -9.81 0' time='0' animate='0' >
    <Node name='Level 1'>
        <MechanicalObject template='Vec3d'/>
        <LightManager name='lightmanager'/>
    </Node>
</Node>
```
Any one know why the test on Windows behave differently to to other plateforms ? 

DM.

**Comment by guparan** [comment]
Some more info about this test...  
Fails on master since b70b477f
Error appeared in `defrost` branch between 4b1f289 and a33b4b1.
First CI build with error: https://ci.inria.fr/sofa-ci/job/windows7_VS-2015_default_amd64/546/  
Error message:  
```
J:\job\origin\master\modules\SofaOpenglVisual\SofaOpenglVisual_test\LightManager_test.cpp:65
Expected: (lm) != (nullptr), actual: NULL vs 8-byte object <00-00 00-00 00-00 00-00>
```
Full output:  
```
Running SofaOpenglVisual_test.exe
Seed Value used for the tests = 1478637948
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TestLightManager
[ RUN      ] TestLightManager.checkAttributes
[ERROR]   [DAGNode "Level 1"] Object type "MechanicalObject" creation Failed
                              Emitted from 'J:\job\origin\master\SofaKernel\modu
                              les\SofaSimulationCommon\xml\NodeElement.cpp' line 
                              92
[ERROR]   [DAGNode "Level 1"] Object type "LightManager" creation Failed
                              Emitted from 'J:\job\origin\master\SofaKernel\modu
                              les\SofaSimulationCommon\xml\NodeElement.cpp' line 
                              92
[ERROR]   [SceneLoaderXML] Node initialization failed.
                           Emitted from 'testscene' line 1
J:\job\origin\master\modules\SofaOpenglVisual\SofaOpenglVisual_test\LightManager_test.cpp(65): error: Expected: (lm) != (nullptr), actual: NULL vs 8-byte object <00-00 00-00 00-00 00-00>
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] TestLightManager.checkAttributes (9 ms)
[----------] 1 test from TestLightManager (9 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (10 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestLightManager.checkAttributes
```

**Comment by damienmarchal** [comment]
Thanks Guillaume for the feedback.

I'm very surprise this fails since 
https://github.com/sofa-framework/sofa/commit/b70b477f9cdae6a1d31d4f462f23780d3bdbcde1

because I see no link between the two.... this is very strange to me.

**Comment by guparan** [comment]
Actually the commit hint is not accurate because we don't have a CI build for each commit.
Sure thing: error appeared between 4bee6c8d and b70b477.
Between this two, there are 35 commits corresponding to `defrost` branch.

**Comment by guparan** [comment]
According to origin/defrost on the Dashboard, error appeared between 4b1f2897 and a33b4b12.
There are some LightManager changes here, we are close ;)
I update my "summary" post.

EDIT: This range is where the test was created. **This test fails on Windows since its creation.**
Please @damienmarchal give this type of information (if you know it) when you create your issue so that no time is lost searching for error appearance.

**Comment by damienmarchal** [comment]
Hi Guillaume,

Thank for the fix. Sorry about the the tailing tests since the beginning... I was assuming that Jenkins would correctly report this information with its regression/failure status & tracking. 

DM.
