### ISSUE TITLE
[runsofa] -a start option does not work with qt views

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#551]
-a start option does not work with qt view
The parameter is well set to true with argument parser but not correctly used by qt.

@damienmarchal I think we already talk about that, like qt create the button then set false the animation with the signal. 

______________________________________________________

Suggested labels:

**Comment by m4n4n** [comment]
@ErwanDouaille I am trying to fix this issue.
Does RealGUI.cpp handle the argument parsed (runSofa -a)?

**Comment by m4n4n** [comment]
@damienmarchal Can you help me start with it?

**Comment by ErwanDouaille** [comment]
@m4n4n every arguments are parsed using : https://github.com/sofa-framework/sofa/blob/master/SofaKernel/framework/sofa/helper/ArgumentParser.h

In the case of Realgui, the -a option is parsed by the main of runSofa :  https://github.com/sofa-framework/sofa/blob/master/applications/projects/runSofa/Main.cpp#L219

**Comment by m4n4n** [comment]
Thanks @ErwanDouaille . Working on it.
