### ISSUE TITLE
Check how positions should be set in CubeTopology

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#574]
Historically Setting a CubeTopology with nx, ny, nz was creating the topology elements but not the positions vectors.

This has been changed in commit: https://github.com/sofa-framework/sofa/commit/47ef2e63a80cda787fd4c61c04580e22ecd56e2e

Need to check code if it was a bug or if the component needs to be used in another way.

```
void CubeTopology::updatePoints()
 {
    SeqPoints& points = *seqPoints.beginEdit();
    points.resize(nbPoints) ;
    for(int i;i<nbPoints;i++)
    {
        points[i] = getPoint(i);
    }
    seqPoints.endEdit();
}
```

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
No one answer ...maybe we could consider closing it ?

**Comment by epernod** [comment]
no news, will see in the future if this is raised again. closing it for the stats.
