### ISSUE TITLE
[runSofa] Unable to find file from GuiDataRepository

### ISSUE THREAD

**Issue by margaretkoehler** [sofa-framework/sofa#577]
I'm using Windows and compiling with Visual Studio. Thanks for the fixes made with PR #568 . I think there's one line that still needs to changed. When I ran the updated version, I received the following error: 

[ERROR]   [FileRepository] File docs/runsofa.html NOT FOUND in :C:\git\sofaframework\sofa\master\build\bin/share/sofa/gui/runSofa/resources/:C:/git/sofaframework/sofa/master/build/share/sofa/gui/qt/resources

I think the issue is in line 154 of sofa/applications/projects/runSofa/Main.cpp. 
Instead of:
GuiDataRepository.addFirstPath(SetDirectory::GetRelativeFromProcess("../share/sofa/gui/runSofa/resources/")) ;
    
I think it should be:
GuiDataRepository.addFirstPath(Utils::getSofaPathTo("share/sofa/gui/runSofa/resources/").c_str()) ; 

______________________________________________________

Suggested labels:

**Comment by ErwanDouaille** [comment]
Thanks for reporting this issue @margaretkoehler. 

> GuiDataRepository.addFirstPath(Utils::getSofaPathTo("share/sofa/gui/runSofa/resources/").c_str()) ;

Does it fix the problem ? If yes, we need to test it on other OS. 

I will investigate it tomorrow afternoon during the coding friday. Feel free to join us for helping :)

**Comment by guparan** [comment]
Thanks for pointing that @margaretkoehler. I tried to propagate my change everywhere but it seems I forgot some part 😅

**Comment by guparan** [comment]
Fixed by #578
