### ISSUE TITLE
[SofaKernel] Node.h animate function commented

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#589]
Just browsing Node.h, I found there is an animate function which is commented. I browsed the file history but didn't find when it have been comment.

What was the use of it ? Should we remove it (cleaning :) )?

Line : https://github.com/sofa-framework/sofa/blob/master/SofaKernel/framework/sofa/simulation/Node.h#L133
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
I think we should remove all commented code. If one day we need it..then it will be worth re-adding it.
