### ISSUE TITLE
UserInterface: Unifying the way to specify colors in the scene

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#64]
In sofa, some component allows to specify colors by writing color="1,0,0" and "red" while others just allow color="1,0,0".

This is a consistency issue (very very bad for the user experience). 
So we should unify this in all sofa for the next release. 

DM.

**Comment by damienmarchal** [comment]
Actually we also have the same problem for 'ambient' and other color related data fied.

There is also inconsistencies in 'filename' that can be either of String or DataFilename type.

**Comment by guparan** [comment]
TODOs have been added by pull request #65

**Comment by guparan** [comment]
@damienmarchal could you set priority and difficulty tags for this task? Thanks :)

**Comment by damienmarchal** [comment]
@guparan It is relatively easy because there is already good examples in some Sofa components. So it is more a factor of refactoring/reorganize/reuse existing code. 

I consider that anything that has consequence on the User Experience is of high priority (in order to get more and more happy sofa users). Data fields are a big part of the sofa User Interface.

**Comment by damienmarchal** [comment]
Hi all

I started implementing something for this but I'm facing a weird compilation issue on VS2015 for which I have no idea on how to solve it https://github.com/sofa-framework/sofa/pull/119

If you have an idea, please share.

**Comment by damienmarchal** [comment]
This PR solve the issue https://github.com/sofa-framework/sofa/issues/124
So when merged... we can close that.
