### ISSUE TITLE
Quit Sofa with Cmd+Q in Mac raises Warnings

### ISSUE THREAD

**Issue by quentinfrancois0** [sofa-framework/sofa#647]
Hello everyone,

I have detected an error when I close a sofa scene on my Mac with Cmd + Q. Here is attached the list of warnings raised when I close a scene. 

[Terminal.txt](https://github.com/sofa-framework/sofa/files/1950734/Terminal.txt)

I'm using MacOS 10.13.4 and Sofa 17.12.

**Comment by techytoes** [comment]
It raises similar warnings in my machine too. I am using MacOS 10.13.4 and Sofa 17.06.
![screen shot 2018-05-07 at 4 17 05 pm](https://user-images.githubusercontent.com/25312754/39698362-2a31270c-5212-11e8-9f08-321fa4353681.png)

**Comment by guparan** [comment]
Seems fixed in recent versions of SOFA.
