### ISSUE TITLE
Refactor opengl rendering code

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#678]
As pointe by @marques-bruno and @fredroy our Opengl rendering code is getting old and less and less compatible with modern architecture and OS. So it may be time for a serious update.
What is your opinion and suggestion that ?

______________________________________________________

Suggested labels:

**Comment by marques-bruno** [comment]
Are you mentioning the "overall" rendering problem of having deprecated OpenGL code in Sofa, or the more specific issue of the hard-coded controls of the "everything-but-interactive" InteractiveCamera Component?
On the latter, having a "CameraController", capable of changing the perspective, modelview etc programatically is a must-have feature, at least for me, and I've been hacking around SOFA 2 years now to get that working...

**Comment by damienmarchal** [comment]
The issue is about 'Refactor opengl rendering code' ...the CameraController is something different :)

**Comment by marques-bruno** [comment]
In that case, I fully agree with @fredroy's opinion on letting a third-party library handle the rendering code. Sofa is not a rendering tool after all, and given the pace at which frameworks evolve (and even replace each other..) I think it draws too much workload away from the actual SOFA stuff

**Comment by marques-bruno** [comment]
https://www.tomshardware.co.uk/khronos-meta-api-vulkan-metal-directx12,news-55170.html

**Comment by damienmarchal** [comment]
To me it is important to clarify  (a one more ambiguity) about sofa where the same code is used for both editing scenes and for final scene rendering in a simulator application. 

To me these two are different concerns which should be clearly separated in our code base. 
Currently the same code is use for both concerns which make things very confusing while it may be organized that way:
- The 'final scene' rendering code should be externalized from the objects (from the draw/drawVisual function) and put in a specific plugin. The plugin may contain a complete rendering stack using whatever API. Of course ones that do not want not to use this code can just don't use it and if nobody wants it nobody implement it.  

- The 'in-editor' rendering is a bit different as we need it for at least to implement runSofa/runSofa2 editing features. So I think this rendering code will still need to be provided (probably as part of runSofa more than of Sofa). 

One my side one big difference between the 'in-editor' and 'scene' rendering is that 
the 'in-editor' rendering code shouldn't appears in the scenegraph.

**Comment by fredroy** [comment]
This is more or less done with:
 - the isolation of the SofaOpenGlVisual (and Sofa.GL)
 - anything else than components of SofaOpenGlVisual now use only DrawTool (well... I am sure exceptions exist 😒)

A good application of this refactor task is the RHI plugin, which provides an other implementation of DrawTool and RhiModel (instead of OglModel). 

Closing for now, if anybody wants to add something, one can re-open it.
