### ISSUE TITLE
[Example] TopologySurfaceDifferentMesh.scn not working as intended

### ISSUE THREAD

**Issue by tgaugry** [sofa-framework/sofa#681]
The blue cloth in this example explode a few ticks after the start of the simulation.
Seems to impact master and 17.12.01
To reproduce, just launch the scenario examples/Tutorials/Topologies/TopologySurfaceDifferentMesh.scn
See image for reference 
![2018-06-07_15 58 25](https://user-images.githubusercontent.com/6662010/41105372-e21440a2-6a6d-11e8-8790-674b67ac229c.png)

______________________________________________________

Suggested labels:

**Comment by epernod** [comment]
Hi @tgaugry , I'm checking the scene.
Do you know if other tutorials are broken?

**Comment by tgaugry** [comment]
none that i'm aware of, except this one.

**Comment by epernod** [comment]
ok thx I'll push a fix for that scene.
