### ISSUE TITLE
onScriptEvent / sendScriptEvent not functional anymore

### ISSUE THREAD

**Issue by marques-bruno** [sofa-framework/sofa#723]
The event signal mechanism between PythonScriptControllers does not work anymore.
In the scene fontain.scn, particles flagged as 'below_floor' should be removed from the scene and spawned back in the "well", which does not happen

To reproduce the bug, just launch fontain.scn

@damienmarchal @bcarrez maybe you can take a look?
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Hi Bruno, 

We have recently merged a lot of breaking things so I'm not surprise several things breaks. So thank very much you for submitting the encountered issue. 

I will give it a look.

**Comment by marques-bruno** [comment]
Thanks @damienmarchal,
I don't know this code very well, but with my understanding of how events are propagated in Sofa, I'm surprised if the current implementation of fontain.py ever worked:

The "Particle" script controller sends an event from its current node - which is a subnode of the rootNode - to the "Fontain" script controller, which is in the rootNode.

After taking a look at the sendScriptEvent bindings, I noticed that these events are propagated like any other event in Sofa, through the node's propagateEvent method. This method only propagates top-bottom, so I don't see how the Fontain's handleEvent method could ever receive the sent event in the first place...?

Or maybe I missed something..? :/

**Comment by epernod** [comment]
![image](https://user-images.githubusercontent.com/21199245/45017005-b105e700-b026-11e8-9257-41d8325eea42.png)

you mean normally the particles outside the floor should not be there in the image but directly  respawn?
I tested the scriptEvent directly inside c++ code between 2 components and this works.
