### ISSUE TITLE
[UniformMass] Warnings popping up when they shouldn't

### ISSUE THREAD

**Issue by marques-bruno** [sofa-framework/sofa#724]
> 
> [WARNING] [UniformMass(UniformMass)] totalMass value overriding the value of the attribute vertexMass. 
> vertexMass = totalMass / nb_dofs. 
> To remove this warning you need to set either totalMass or vertexMass data field, but not both.

This warning should show up when both vertexMass and totalMass are set. Though setting totalMass alone still triggers the warning
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Hi Bruno,

We have recently merged a lot of breaking things so I'm not surprise several things breaks. So thank very much you for submitting the encountered issue.

This is something on which Mr @hugtalbot  should look at :)

**Comment by epernod** [comment]
Hi @marques-bruno , I also experienced that behavior but only on very specific case. 
Could you put the scene where you have this warning? or do you always have that?

In my case it is in a scene with a **MechanicalStateController** and I suspect this component to force the **vertexMass** in background... But didn't had time to investigate.

**Comment by marques-bruno** [comment]
Thanks for your feedbacks,
I've encountered the problem with the Fontain.scn scene in sofa python examples. I don't think there's a mechanical state controller there though
