### ISSUE TITLE
Improving the python binding for Data. 

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#767]
Just want to share some experiment done today.

In its current state the binding for the data suffer from several drawback among which:
- inconsistent API 
- poor performances because there is a lot of copies and data conversion

```py
m = createObject("MechanicalObject", position=[0,0,0, 1, 1, 1, 2, 2, 2])

# The following code is actually doing 
# findData("position") + conversion of everything into a python list 
# (linear search into the datas) + linear conversion of the data into python object
a = m.position 

print(str(type(m.position)))  ## print 'list'
                                         ## so we have lost the data type and got a python "converted" list. 

print(str(m.position))  ## print [0,0,0, 1,1,1, 2,2,2] 
                                   ## so we have lost the inner structure of the data field. 

# Doing  
m.position = [0,0,0,1,1,1,2,2,2] # Will work

# One may expect that changing a single value using the following syntax will not work
m.position[2] = 3.0      # But it does not because it change the copy of the vector

# To change a single value we need the much less readable version:
m.getData("position").setValue(2, 3.0)

# So here is what we have to do to increment a single value in an efficient way:
d = m.getData("position")
d.setValue(2, d.getValue(2) + 1.0)
 ```

This may be look not really important but to me this results in writing things like the following code
(taken form the fountain.scn example discussion) which is inefficient and bad looking:
```py
    # called on each animation step
    def onBeginAnimationStep(self,dt):
        position = self.particleObject.findData('position').value                    # Complete copy of the state vector.  
        if position[0][1] < -5.0:                                                                      # To check one value
            self.myNode.getParents()[0].sendScriptEvent('below_floor',self.myNode.name)
        return 0 
```

So I made small changes to the API here is what I can come up with:
```py 
m = createObject("MechanicalObject", position=[0,0,0, 1, 1, 1, 2, 2, 2])

print(repr(type(m.position)))  ## print Sofa.Data as we returns the Data, not a generated list. 

print(str(m.position))     ## print [[0,0,0], [1,1,1], [2,2,2]] 
                                     ## the inner structure of the data field is not list 

m.position.toList()         ## create and returns the list [[0,0,0], [1,1,1], [2,2,2]] 

## Index based access of any 'dimmensions'
m.position = [[0,0,0],[1,1,1],[2,2,2]]     
m.position[0] = [3,3,3]    # will change the first vector in the array. 
m.position[0,1] = 3.0      # change the first index of the first vector. 

## Slice based access
m.position[:,:1] = 3.0     # Will write 3.0 in the y component on every "vector" 

## Custom access using generator
def OnDiagonal(o):
     idx = max(o.shape[0], o.shape[1])
     for i in xrange(0, idx): 
            yield (idx,idx)

m.position[OnDiagonal] =  1.0  

### Functional style... 
def myFunction(i, j):
     if i == j:
            return 1.0
     return 0.0

m.position.apply(myFunction)
```

It is possible to implement all that without breaking the API except for the unified accessor syntax
```py
m.position = [[0,0,0],[1,1,1],[2,2,2]]     
m.position[0] = [3,3,3]                                          # Having this syntax will be breaking  
m.position[0,1] = 3.0                                            # Having this syntax will be breaking

# The non breaking version I can come up is the following:
m.position = [[0,0,0],[1,1,1],[2,2,2]]     

m = m.getData("position")
m[0] = [3,3,3]    
m[0,1] = 3.0      
# Which is less nice. 
```

A lot more can be done but I found the result interesting and want to share. 

I will now focus on having the Data object returned to implement the buffer+memoryview protocol (https://docs.python.org/3/c-api/buffer.html) of python to have copy less interoperability with python objects that implement the protocol (array.array, numpy.array, cython memory view, etc...). 

Feedback are welcome... 

______________________________________________________

Suggested labels:

**Comment by marques-bruno** [comment]
@damienmarchal thanks for sharing!
Are your API changes available somewhere in the sofa repository?
I really don't know much about python (almost never used it outside of Sofa...) so I'm a bit puzzled with the syntax here: `m.position[OnDiagonal] = 1.0` / `m.position.apply(function)`
But I sure love the idea of returning an actual Sofa.Data pointer instead of a copied list!
This was all done using python's C-api or did you sneak in some cython? =)

**Comment by damienmarchal** [comment]
Hello Bruno,

Functional programming is very standard and part of the language:
http://book.pythontips.com/en/latest/map_filter.html 
as well as part of libraries:
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.functional.html

So functional programming is a must (and cheap thing) to have but to be honest the syntax:
```py
m.position[OnDiagonal] = 0.0
```
was just there for fun and to see if it was possible (actually I see it as a generalization of the slice syntax array[2:1] that is part of the language where instead of iterating between the slice interval you can provide funny iteration scheme). But I fear how slow may be generators compared to more classical iteration mechanisms. 

About your question regarding the implementation: 
I wrote most of the change using the C-python API but after some time I was fed-up on how ugly it is and terminated the implementation using python. Mixing the python and c++ code was actually very simple thanks to the cython ability to generate dual-bindings... where a c++ function is exposed in python as well as having python functions exposed to C++ (so a .h is generated to include and use the python code in your c++ code base).  
That's said cython is not magic and the generated .cpp/.h are containing 100% python C-api ...so everything implemented in cython could be implemented exactly the same using the C-python API. 
It is just 10x longer to write an equivalent code. 

As you ask I pushed a branch (https://github.com/SofaDefrost/sofa/tree/sofa_refactorSofaPython) with the implementation don't expect the branch to compile today as it contains irrelevant code that are wip to support the buffer protocol for seamless integration with numpy. 

For the syntax about Data...everything is implemented in 'Binding_Data.cpp'. 
The function  SofaData_asMapping_ass_subscript is the one called when using the [aaa] =  operation. 
```cpp
static int SofaData_asMapping_ass_subscript(PyObject *o, PyObject *key, PyObject *value)
{
    ....
    /// This line is actually calling the "python" part implementation because I was too lazy
    /// to implement it using C-Python API.  So the function is really implemented partially with python 
    /// and partially with c++ :) 
    if( Data_ass_subscript(o,key,value) )
        return 0;
     
     /// after that it is a lot of ugly c-python api code. 
     ....
```

And the corresponding cython code (in Binding_DataArray.pyx)
```python
def sliceToRange(c, end):
        start = 0
        stop = end
        if c.start != None:
                start = c.start
        if c.stop != None:
                stop = c.stop
        return xrange(start, stop) 

cdef public bool Data_ass_subscript(o,key,value):
        if isinstance(key, slice):
                start, stop, step = key.start, key.stop, key.step
                for i in xrange(start,stop):
                        Data_helper(o, i, value)
                return True
        elif callable(key):
                g = key(o)        
                for i in g:
                        Data_helper(o, i, value)
                return True
        elif isinstance(key, tuple):
                if isinstance(key[0], slice) and isinstance(key[1], slice):
                        igen =  sliceToRange(key[0], o.shape[0])
                        jgen =  sliceToRange(key[1], o.shape[1])
                        for i in igen:
                                for j in jgen:
                                        Data_helper(o,(i,j),value)                     
                        return True                        
        return False
```

Mixing code to implement a single function is clearly not the way to go. But i found that implementing complete complex function using the C-python api in cython is way more easier than writing them in C.

**Comment by damienmarchal** [comment]
I'm closing this issue because this is now handlede into the sofapython3 refactoring.
