### ISSUE TITLE
 Regression: OglModel won't load stl file

### ISSUE THREAD

**Issue by EulalieCoevoet** [sofa-framework/sofa#768]
Hi,

So the component OglModel won't load stl file.
I think the issue comes from PR #661, in particular the changes made in VisualModelImpl.

Eulalie
______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Thank Eulalie for this report.

After discussion with Erik, STL was remove on purpose but the error message is not clear on that and on how to fix the Scene. We will fix that this friday.

DM.

**Comment by epernod** [comment]
you can let it open, we will close this issue when the error message will be added. (very soon)

**Comment by epernod** [comment]
otherwise I will forgot ...
