### ISSUE TITLE
Scene crashing in GUI mode only: can't make a test that fails

### ISSUE THREAD

**Issue by olivier-goury** [sofa-framework/sofa#79]
Hello. I made a test with the following scene. It actually pass in the current testing framework despite crashing upon loading in the GUI mode. 
```
<?xml version='1.0'?>
<Node 	name='Root'>
    <VisualStyle displayFlags='showForceFields'/>
    <Node name='FEMnode'> 
        <MechanicalObject/>  
        <TetrahedronFEMForceField/> 
    </Node>
</Node>
```

**Comment by damienmarchal** [comment]
This bug is fixed. 

Fundamentally the problem is that when there is not topology associated to the force field a warning message is printed...but the draw function is still working "as" if there were.
