### ISSUE TITLE
Cannot install from source when using Qt

### ISSUE THREAD

**Issue by vmagno** [sofa-framework/sofa#794]
When doing `make install`, the installation fails for components SofaGuiQt et QGLViewer because the Qt "plugins" directory is not found.

A more robust way to do it would be to query the path for each needed plugin (as in http://doc.qt.io/qt-5/cmake-manual.html), but I'm not sure which plugins are needed, or if their installation is really necessary (it is not, on my system).

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Fixed by #959
