### ISSUE TITLE
Reactivate regression tests in CI

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#801]
We definitely need to get timing and position regression feedback from (at least a few) scene tests.

Already existing tools for position regressions:
- applications/plugins/SofaTest/SofaTest_test/Regression_test
- applications/projects/sofaVerification

TODO:
- [x] Choose one tool to update and reactivate
- [ ] Add execution time measure
- [x] Integrate it in CI

**Comment by epernod** [comment]
This will be done in https://github.com/sofa-framework/sofa/pull/830

**Comment by epernod** [comment]
- info on time is already dumped at each scene test but not used on the CI.
- State is now tested using the project: https://github.com/sofa-framework/regression
Done in PR #830
Tested in PR #857
