### ISSUE TITLE
Remove useless template instantiation that are not needed

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#806]
In nearly every .cpp there is explicit template spcialization with such kind of lines:

```cpp
#ifndef SOFA_FLOAT
template class SOFA_GENERAL_ENGINE_API PointsFromIndices<Vec3dTypes>;
#endif //SOFA_FLOAT
#ifndef SOFA_DOUBLE
template class SOFA_GENERAL_ENGINE_API PointsFromIndices<Vec3fTypes>;
#endif //SOFA_DOUBLE
```

Aren't these lines useless given that the template are already specialized when they are added 
in the factory:

```cpp
int PointsFromIndicesClass = core::RegisterObject("Find the points given a list of indices")
#ifndef SOFA_FLOAT
        .add< PointsFromIndices<Vec3dTypes> >()
// .add< PointsFromIndices<Rigid3dTypes> >()
#endif //SOFA_FLOAT
#ifndef SOFA_DOUBLE
        .add< PointsFromIndices<Vec3fTypes> >()
// .add< PointsFromIndices<Rigid3fTypes> >()
#endif //SOFA_DOUBLE
```
If this is the case why not simply removing them ? 
______________________________________________________

Suggested labels:

**Comment by VannesteFelix** [comment]
working on it for stc6

**Comment by damienmarchal** [comment]
Well it may be usefull to check what I'm saying from time to time :)
Thank felix for reporting the problems.

**Comment by guparan** [comment]
@damienmarchal What was the answer here? Why couldn't this be done?

**Comment by damienmarchal** [comment]
No idea, it juste don't work;
