### ISSUE TITLE
check for package dependencies (windows) at cmake

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#807]
If possible, it would be great to have a check for package dependencies at cmake stage.
right now cmake pass and compilation failed due to glew missing for example (30 mins later)

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Wow, very old issue. Indeed CMake generation must tell you if some dependency is not satisfied. I think it has been fixed for a long time but feel free to reopen if not! Cheers :wink:
