### ISSUE TITLE
remove MultiGroup in LinearSolver 

### ISSUE THREAD

**Issue by ChristianDuriez** [sofa-framework/sofa#816]
In  the component MatrixLinearSolver, there is the option "multi group"  (false by default) that complexity the code unnecessarily. 
The goal of this option was to solve each Mechanical Object under the LinearSolver  as if there were independant manner.  I**n practice, the approach is not compatible with multi-mapping** (and was maybe coded at the time when the scene graph was a tree...).

If no one stop us... we will remove it soon.

https://github.com/sofa-framework/sofa/blob/a21a0a33812f9a1b3f0d1f30fdc8d61aad560150/SofaKernel/modules/SofaBaseLinearSolver/MatrixLinearSolver.h#L182

@sofa-framework/reviewers

**Comment by damienmarchal** [comment]
And as you are in this file...can you also apply cosmetic cleaning as:
- move code from .h to put in .inl 
- remove commented code the .inl 
- ...
