### ISSUE TITLE
Detect missing python27.dll in installer

### ISSUE THREAD

**Issue by Neustradamus** [sofa-framework/sofa#879]
runSofa.exe system error :
- python27.dll is missing

**Comment by damienmarchal** [comment]
Hi @Neustradamus,

Thank you a lot for taking time to report the issue. 

I think @guparan  is the one to handle this issue.
@guparan  any update ?

**Comment by guparan** [comment]
Hi guys, sorry for the late answer. 

We do not ship Python with SOFA. You have to install it yourself. 
Be sure to select the appropriate version and platform: [2.7.15_64-bit](https://www.python.org/ftp/python/2.7.15/python-2.7.15.amd64.msi) or [2.7.15_32-bit](https://www.python.org/ftp/python/2.7.15/python-2.7.15.msi). 
When asked by the installer, accept to add Python to your PATH.

Hope that helps :+1:

**Comment by Neustradamus** [comment]
Why it is not possible to have with?

Solution:
The installer can detect:
- if there is on the machine, good
- if not, inform the user to download the good package...

**Comment by damienmarchal** [comment]
Hi Neustradamus,

Improving the packaging and installation process of binary version of Sofa is something we really would like to improve. @guparan already made great work on that  but as we are short on man-power this is very slow, small step are done at each Sofa release. 

Thanks for you suggestion to auto-install python (and numpy), this would definitely be nice feature.  
In case you have knowledge to do such a thing and are you interested in helping I think @guparan have dedicated github branches with the additional CMAKE scripts he use for packaging the release.

**Comment by Neustradamus** [comment]
@guparan: It is solved?

**Comment by guparan** [comment]
Hi @Neustradamus,
Shipping Python with SOFA binaries is not a priority for now but I will definitely improve the installation instructions to make it very clear that users have to set their Python env by themselves and how to do it.
But actually I may have closed this one too quickly, the solution you proposed should be implemented. Let's re-open and put a more generic title. No promise on when I will tackle this though.
Do not hesitate to help in any way :+1:

**Comment by fredroy** [comment]
SofaPython (using python2) is not supported anymore (like python2 itself actually), so a doubt anybody will fix this issue any day....
