### ISSUE TITLE
[SofaTest] Init MessageDispatcher to prevent side effects

### ISSUE THREAD

**Issue by guparan** [sofa-framework/sofa#94]
`MessageDispatcher::clearHandlers()` can have side effects on other tests in same suite.
See #83 for error case.

SofaTest API should ensure that each test starts with a clean MessageDispatcher containing always the same set of MessageHandlers.

**Comment by damienmarchal** [comment]
The pull-request #95 contains code that automatically install the dispatcher needed in tests. 
So normally it is not needed any more to clearHandlers (unless you really want a specific behavior). 

EDIT: The Pull request #95 was not clean so I did a new one, sorry for the noise.
