### ISSUE TITLE
Issue with null pointer in CollisionVisitor

### ISSUE THREAD

**Issue by courtecuisse** [sofa-framework/sofa#961]
Hi,

I have an issue with commit cbee54ca9953f514da374d92253f9ca6e54df51f line 77.
It seems that a function has been added to get the number of primitives from the narrowphase without checking if the narrow phase is not NULL i.e. 
    m_primitivesTest += obj->getNarrowPhaseDetection()->getPrimitiveTestCount();

I use such pipeline without narrowphase, which mechanically creates a segfault in my scenes. I fixed the problem adding if (obj->getNarrowPhaseDetection()) before the previous line but it will result in m_primitiveTestCount = 0. I don't know if it will raise other issues.

Hadrien. 

______________________________________________________

Suggested labels:

**Comment by damienmarchal** [comment]
Definitely to fix.

**Comment by fspadoni** [comment]
Thank Hadrien, the fix is fine.

The m_primitiveTestCount  is  used only for statitistics to know how many collision tests are performed.
There should be no other crash if m_primitiveTestCount  is = 0.

**Comment by damienmarchal** [comment]
This was fixed in https://github.com/sofa-framework/sofa/pull/962
We can close the issue.
