### ISSUE TITLE
BarycentricMapping - Triangles into Hexahedra

### ISSUE THREAD

**Issue by remibessard** [sofa-framework/sofa#988]
When trying to map a surface mesh (triangles) into a set of hexahedra using the BarycentricMapping component, mapping fails and deform the triangle mesh unexpectedly.

Such issue appears in release v18.12 and master while it seemed to work fine in release v18.06.
Cf. [scene&screenshots](https://mybox.inria.fr/d/7a20cfaa26/
)

Thank you for your help.
@hugtalbot @EulalieCoevoet 
______________________________________________________

**Comment by epernod** [comment]
@remibessard thanks for the report, could you post the scene and screenshot directly here in the issue. I can't acces the inria dropbox.

**Comment by remibessard** [comment]
![CubeMapping_sofa_1812 master](https://user-images.githubusercontent.com/19310913/55941516-a2c61c00-5c42-11e9-9fd7-d3e8510f4e0d.png)

![CubeMapping_sofa_1806](https://user-images.githubusercontent.com/19310913/55941519-a3f74900-5c42-11e9-874c-c24eeeedf341.png)

**Comment by remibessard** [comment]
_(clicking on "Edit" you will see the whole scene description, here you only see a sub-part of it)_ 
`<Node dt="0.04" gravity="0 -0.1 0" name="root">
    <VisualStyle displayFlags="showVisual showCollisionModels hideBehaviorModels showForceFields showInteractionForceFields showWireframe" />

    <Node name="Topo">
		<RegularGridTopology name="RGT" min="-6 -6 -6" max="6 6 6" n="4 4 4" />    
	    <Node name="Surface">
			
			<MeshObjLoader name="loader" filename="mesh/liver.obj" />
			<MechanicalObject name="DOF" src="@loader" showObject="false"/>    
		</Node>
	</Node>

    <Node name="Cube">
		<EulerImplicit />
		<CGLinearSolver iterations="500" name="linear solver" tolerance="1.0e-9" threshold="1.0e-9" />

		<HexahedronSetTopologyContainer name="HSTC" src="@../Topo/RGT" />
		<HexahedronSetGeometryAlgorithms name="HSGA" />
		<MechanicalObject name="DOF" position="@../Topo/RGT.position" showObject="true"/>
		<HexahedronFEMForceField name="HFF" youngModulus="20"  poissonRatio="0.2" />
		<DiagonalMass totalMass="5" />

		<PlaneForceField normal="0 1 0" d="-7"  draw="true"/>
	    <Node name="Cube">
	   	    <VisualStyle displayFlags="hideWireframe" />
			<TriangleSetTopologyContainer name="TSTC" src="@../../Topo/Surface/loader" />
			<TriangleSetGeometryAlgorithms name="HSGA" />
			<MechanicalObject name="DOF" position="@../../Topo/Surface/loader.position" showObject="true"/>    
			<Triangle/>
			<BarycentricMapping />
		</Node>
	</Node>

</Node>`

**Comment by epernod** [comment]
I don't really see why, but it might be a side effect of some renumbering change I did in tetra and triangles.
I will check the scene.

or side effect of the hashing map from @EulalieCoevoet  yes!

**Comment by damienmarchal** [comment]
Hi Remi, thanks for the bug report and the scene.
@epernod, @EulalieCoevoet  can you say which change is the latest so we can test before this version if the code work ?

**Comment by damienmarchal** [comment]
Any news here ?
