### ISSUE TITLE
[SofaGuiGlut] Lonely #endif without its #ifdef in SimpleGUI.cpp

### ISSUE THREAD

**Issue by p-shg** [sofa-framework/sofa#989]
Hi,
I've noticed a trailing `#endif` in [SimpleGUI.cpp](https://github.com/sofa-framework/sofa/blob/master/applications/projects/SofaGuiGlut/SimpleGUI.cpp), which on my machine seems to break compilation.

Is this normal? and if not, why does the CI build without errors?
Is SofaGuiGlut even compiled on the CI?

Cheers

______________________________________________________

Suggested labels:

**Comment by epernod** [comment]
Hi, I suppose you are speaking about this one:
https://github.com/sofa-framework/sofa/blob/801cda5c4042438f49970fc8233d915f60e334d1/applications/projects/SofaGuiGlut/SimpleGUI.cpp#L232

I think you are right, this is a bug.
I just checked the [configure file of the ci](https://github.com/sofa-framework/sofa/blob/master/scripts/ci/configure.sh) it doesn't seems to have the option SOFAGUIGLUT to ON and the option is set to false by default, so I don't think it is compiled on the CI. @guparan do you confirm?

**Comment by guparan** [comment]
Indeed. Note though that the ci scripts are in https://github.com/sofa-framework/ci :wink: 
AFAIK, glut support has been stopped in SOFA. 
@fredroy should confirm :+1:

**Comment by guparan** [comment]
This shall be fixed and set to deprecated during STC#7
